fhir-model/src/main/java/com/ibm/watson/health/fhir/model/generator/FHIRXMLGenerator.java
fhir-model/src/main/java/com/ibm/watson/health/fhir/model/util/XMLSupport.java

Issue #9 - non-closing stream writer delegate

---

fhir-server-test/src/test/java/com/ibm/watson/health/fhir/cli/test/FHIRCliTest.java
fhir-server-test/src/test/java/com/ibm/watson/health/fhir/server/test/ServerSpecTest.java
fhir-server/src/main/java/com/ibm/watson/health/fhir/server/resources/FHIRResource.java

- updated removed reference to Cloud
- removed reference to two unused variables
- update tests to reflect the changes

re-factored the code to remove unused internal resource types

---

docs/FHIRServerUsersGuide.md

Update metadata at top of FHIRServerUsersGuide.md

---

fhir-server/src/main/java/com/ibm/watson/health/fhir/server/listener/FHIRServletContextListener.java

- removed hard dependency on userlib
- removed reference ato derby-sproc*.jar

On startup, the userlib is required for derbySproc #23

---

fhir-bulkimportexport-webapp/src/main/liberty/config/server.xml
fhir-bulkimportexport/src/main/java/META-INF/batch-jobs/FhirBulkExportBatchJob.xml
fhir-bulkimportexport/src/main/java/META-INF/batch-jobs/FhirBulkExportChunkJob.xml
fhir-bulkimportexport/src/main/java/com/ibm/waston/health/fhir/bulkcommon/COSUtils.java
fhir-bulkimportexport/src/main/java/com/ibm/waston/health/fhir/bulkcommon/Constants.java
fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkexport/BulkExportBatchLet.java
fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkexport/CheckPointAlgorithm.java
fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkexport/ChunkProcessor.java
fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkexport/ChunkReader.java
fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkexport/ChunkWriter.java
fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkexport/TransientUserData.java

Issue #32 Enhance Bulk JavaBatch to use single COS object.

---

fhir-model/src/test/java/com/ibm/watson/health/fhir/model/examples/test/AppointmentTest.java
fhir-model/src/test/java/com/ibm/watson/health/fhir/model/examples/test/DiagnosticReportTest.java
fhir-model/src/test/java/com/ibm/watson/health/fhir/model/examples/test/PatientTest.java

Simple examples to highlight the use of the builder for consumers. 

Create Examples using Builders #63

---

README.md
fhir-parent/pom.xml
fhir-server/liberty-config/server.xml

* Removed "Watson Health" from name of server in the README (name still getting finalized)
* Added bulkimportexport projects to parent pom
* Replace tabs with spaces in server.xml

Update readme and parent pom

---

fhir-bulkimportexport/src/main/java/META-INF/batch-jobs/FhirBulkExportChunkJob.xml
fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkexport/ChunkReader.java

issue #67 fix fhir tenant issue

---

fhir-operation-bulkdata/src/main/java/com/ibm/watson/health/fhir/operation/bullkdata/client/BulkDataClient.java
fhir-operation-bulkdata/src/main/java/com/ibm/watson/health/fhir/operation/bullkdata/model/BulkExportJobInstanceRequest.java
fhir-server-test/src/test/java/com/ibm/watson/health/fhir/server/test/ExportOperationTest.java

Connectathon Issues with Bulkdata #67

---

fhir-operation-bulkdata/src/main/java/com/ibm/watson/health/fhir/operation/bullkdata/client/BulkDataClient.java

issue #67 change file path in COS

---

fhir-bulkimportexport/src/main/java/META-INF/batch-jobs/FhirBulkImportChunkJob.xml
fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkimport/ChunkWriter.java

issue #67 change importchunkjob to take tenant and storeID

---

fhir-bulkimportexport-webapp/pom.xml

issue #67 add org.json to javabatchjob war

---

fhir-config/src/main/java/com/ibm/watson/health/fhir/config/FHIRRequestContext.java
fhir-install/Dockerfile
fhir-operation-bulkdata/src/main/java/com/ibm/watson/health/fhir/operation/bullkdata/util/BulkDataUtil.java
fhir-operation/src/main/java/com/ibm/watson/health/fhir/operation/util/FHIROperationUtil.java
fhir-server/liberty-config/server.xml

75 - Custom operation should support more types being passed from URI
76 - Bulk should accept _outputFormat requets with enencoded "+"

Issues 75 and 76 - support calling $export via GET

---

fhir-operation-bulkdata/src/main/java/com/ibm/watson/health/fhir/operation/bullkdata/client/BulkDataClient.java
fhir-operation-bulkdata/src/main/java/com/ibm/watson/health/fhir/operation/bullkdata/config/BulkDataConfigUtil.java
fhir-operation-bulkdata/src/test/resources/testdata/config/default/bulkdata.json

- updates to use a contextRoot
- updates the bulkdata.json

Issue 67 - fix ndjson workaround absolute url issue #79

---

fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkexport/ChunkProcessor.java
fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkexport/ChunkWriter.java
fhir-operation-bulkdata/src/main/java/com/ibm/watson/health/fhir/operation/bullkdata/client/BulkDataClient.java
fhir-operation-bulkdata/src/main/java/com/ibm/watson/health/fhir/operation/bullkdata/config/BulkDataConfigUtil.java
fhir-operation/src/main/java/com/ibm/watson/health/fhir/operation/util/FHIROperationUtil.java

* fix ndjson implementation
* return absolute url for job status checks
the latter is just a quickfix.  we need https://github.com/IBM/FHIR/issues/66 for the proper fix.

Issue 67 - fix ndjson workaround absolute url issue

---

fhir-operation-bulkdata/src/main/java/com/ibm/watson/health/fhir/operation/bullkdata/util/BulkDataUtil.java
fhir-server-test/src/test/java/com/ibm/watson/health/fhir/server/test/ExportOperationTest.java

- fix for decode=false on URL's query parameters

Bulk should accept _outputFormat requests with encoded "+" #76

---

fhir-core/pom.xml
fhir-notification/pom.xml
fhir-operation-apply/pom.xml
fhir-operation/pom.xml
fhir-persistence/pom.xml
fhir-provider/pom.xml
fhir-server/pom.xml

fix for ear creation #57

---

MAINTAINERS.md
README.md

- added whitespace <space><space> in order to format the markdown

Enable Travis for the `FHIR` Repository #13

---

CONTRIBUTING.md

Minor change to point at the right spot for docs.

Fix reference to docs

---

fhir-registry/src/main/java/com/ibm/watson/health/fhir/registry/FHIRRegistry.java
fhir-registry/src/main/java/com/ibm/watson/health/fhir/registry/resource/FHIRRegistryResource.java
fhir-registry/src/test/java/com/ibm/watson/health/fhir/registry/resource/test/VersionTest.java

Issue #28 - updated version comparison

---

fhir-registry/src/main/java/com/ibm/watson/health/fhir/registry/FHIRRegistry.java
fhir-registry/src/main/java/com/ibm/watson/health/fhir/registry/resource/FHIRRegistryResource.java
fhir-registry/src/test/java/com/ibm/watson/health/fhir/registry/spec/test/FHIRRegistryTest.java

Issue #28 - fixed version compare added lexical compare option

---

README.md

Add note for issue 114 package name change

---

.github/workflows/maven.yml
fhir-model/pom.xml
fhir-parent/pom.xml
fhir-persistence-jdbc/pom.xml
fhir-persistence/pom.xml
fhir-search/pom.xml
fhir-server-test/pom.xml

Also includes a change to configure the fhir-examples dependency version in the fhir-parent pom.

introduce github action for performing maven build on pull_requests

---

fhir-operation-validate/src/main/java/com/ibm/fhir/operation/validate/ValidateOperation.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRValidateOperationTest.java

issue #131 change validation response to 200 for invalid resources

---

fhir-model/src/main/java/com/ibm/fhir/model/path/visitor/FHIRPathVoidParameterAbstractNodeVisitor.java
fhir-model/src/main/java/com/ibm/fhir/model/path/visitor/FHIRPathVoidParameterNodeVisitorAdapter.java
fhir-model/src/test/java/com/ibm/fhir/model/path/test/NodeVisitorTest.java
fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java

Issue #125 - FHIRValidator refactor to use FHIRPathNodeVisitor

---

fhir-benchmark/pom.xml

Resolve GITHUB Action with Workflow between oss/repo1 #141 

Resolve GITHUB Action with Workflow between oss/repo1 #141

---

fhir-parent/pom.xml

Revert maven-jar-plugin to 2.6 #146

---

fhir-benchmark/pom.xml

Fix issue with benchmark finding the right dependencies #141

---

fhir-examples/src/main/resources/json/minimal.txt
fhir-examples/src/main/resources/xml/minimal.txt
fhir-model/src/main/java/com/ibm/fhir/model/util/ModelSupport.java
fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
fhir-validation/src/main/java/com/ibm/fhir/validation/util/ConstraintGenerator.java
fhir-validation/src/main/java/com/ibm/fhir/validation/util/ProfileSupport.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/BodyWeightProfileTest.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/VitalSignsProfileTest.java

Issue #125 - ProfileSupport refactor, NPE fix, update minimal examples

---

fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java

issue #172 500-server-error when running json patch test cases

---

fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java

issue #177 Fix KS password for FhirServerTestBase

---

fhir-server/src/main/java/com/ibm/fhir/server/util/ReferenceMappingVisitor.java

Issue 180 - Check for null before checking for value

---

fhir-validation/pom.xml
fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/BundleValidationTest.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/ExplanationOfBenefitTest.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/FHIRValidatorTest.java
fhir-validation/src/test/resources/JSON/explanationofbenefit.json

Issue #182 -  update FHIRValidator.getResource to handle contained resources properly

---

fhir-config/src/main/java/com/ibm/fhir/config/ConfigurationService.java
fhir-config/src/main/java/com/ibm/fhir/config/mock/MockPropertyGroup.java
fhir-config/src/test/java/com/ibm/fhir/config/test/MockPropertyGroupTest.java
fhir-config/src/test/java/com/ibm/fhir/config/test/PropertyGroupTest.java
fhir-model/src/main/java/com/ibm/fhir/model/util/FHIRUtil.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/FHIRModelTestBase.java
fhir-server-test/src/test/java/com/ibm/fhir/client/test/FHIRClientTest.java
fhir-server-test/src/test/java/com/ibm/fhir/client/test/FHIROAuth2Test.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRValidateOperationTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/ServerSpecTest.java

issue #197 use JsonBuilder and JsonReaderFactory to improve performance

---

fhir-parent/pom.xml
fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRNotificationServiceClientEndpoint.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/WebSocketNotificationsTest.java

- updated to 1.15 of tyrus with websockets
- remove unusable properties
- update the endpoint

WebSocket IT Fails intermittently #210

---

fhir-client/src/main/java/com/ibm/fhir/client/FHIRRequestHeader.java
fhir-config/src/main/java/com/ibm/fhir/config/PropertyGroup.java

Replace xmp tag to create valid javadoc #208

---

fhir-connectathon-clients/src/test/java/com/ibm/fhir/connectathon/patient/PatientTrackTest.java
fhir-model/src/test/java/com/ibm/fhir/model/spec/test/R4ExamplesDriver.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/FHIRModelTestBase.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/BundleTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRToCdaOperationTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/ServerSpecTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/SimpleRouterTest.java

JavaDoc has some consistency changes needed #218

---

fhir-parent/pom.xml

- put profile in the right location.

Manage M2E Settings for fhir-parent #206

---

fhir-validation/pom.xml
fhir-validation/src/main/assembly/create-validation.md
fhir-validation/src/main/assembly/distribution.xml

FHIR Validation Profile to Generate a Zip File #229

---

fhir-server-test/src/test/java/com/ibm/fhir/server/test/WebSocketNotificationsTest.java

issue #184 #210 websocket test timeout issue

---

fhir-parent/pom.xml
fhir-persistence-jdbc/pom.xml
fhir-persistence-schema/pom.xml

Clean Cached Derby Data #244

---

fhir-model/src/test/java/com/ibm/fhir/model/util/test/XMLSupportTest.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchTokenTest.java

also pushed an unrelated change to verify what happens when parsing a div with no namespace

issue #268 - Stop indexing the system for ContactPoint

---

.github/ISSUE_TEMPLATE/release-checklist.md
CONTRIBUTING.md
MAINTAINERS.md
README.md
docs/CHANGELOG.md
docs/Conformance.md
docs/DB2OnCloudSetup.md
docs/FHIRServerUsersGuide.md
docs/raspberry-pi-4/howto.md
docs/template.md
fhir-examples/src/main/resources/json/spec/LICENSE.md
fhir-examples/src/main/resources/json/spec/README.md
fhir-install/README.md
fhir-install/src/main/resources/docs/README.txt
fhir-parent/pom.xml
fhir-persistence-schema/README.md
fhir-search/src/main/resources/search-parameters.md
fhir-server-test/src/test/java/com/ibm/fhir/cli/test/FHIRCliTest.java
fhir-server-webapp/pom.xml
fhir-server-webapp/src/main/webapp/WEB-INF/web.xml
fhir-server/liberty-config-tenants/config/tenant2/readme.md
fhir-server/liberty-config/config/default/extension-search-parameters-valuetypes.md
fhir-server/liberty-config/config/default/extension-search-parameters.md
fhir-server/liberty-config/server.xml
fhir-server/pom.xml
fhir-server/src/main/java/com/ibm/fhir/server/listener/FHIRServletContextListener.java
fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java

Change name to IBM FHIR Server #114

---

.github/workflows/build.yml

https://help.github.com/en/articles/workflow-syntax-for-github-actions#onpushpull_requestpaths

Update build.yml to ignore docs path #145

---

fhir-client/src/main/java/com/ibm/fhir/client/impl/FHIRClientImpl.java
fhir-client/src/test/java/com/ibm/fhir/client/test/mains/JaxrsClientTestMain.java
fhir-client/src/test/java/com/ibm/fhir/client/test/mains/ReadClaimTestMain.java
fhir-client/src/test/java/com/ibm/fhir/client/test/mains/UpdateTestMain.java
fhir-provider/src/main/java/com/ibm/fhir/provider/FHIRJsonProvider.java
fhir-provider/src/main/java/com/ibm/fhir/provider/FHIRProvider.java
fhir-server/src/main/java/com/ibm/fhir/server/FHIRApplication.java

Issue #193 - client swallows IO exceptions

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPagingTest.java
fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java

Issue #329 - skip resource query if pageSize == 0

---

docs/readme.md

perviously it all showed up on one wrapped line, making it basically unreadable

fix formatting in "Building the Site" section

---

fhir-examples/src/main/resources/json/ibm/basic/BasicDate.json
fhir-examples/src/main/resources/json/ibm/basic/BasicNumber.json
fhir-examples/src/main/resources/json/ibm/basic/BasicReference.json
fhir-examples/src/main/resources/json/ibm/basic/BasicString.json
fhir-examples/src/main/resources/json/ibm/basic/BasicToken.json
fhir-examples/src/main/resources/json/ibm/basic/BasicURI.json
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java

* Removed extra single quote from log message
* Updated BasicX.json examples to avoid invalid combinations of data types and search parameter types

Issue 355 - additional tweaks to logging and jdbc search tests

---

docs/src/pages/TipsAndTricks.mdx

issue #362

---

fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaGenerator.java

had these leftover formatting tweaks from today's session.  you can decide if its worth merging them :-)

minor formatting tweaks

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/InclusionQuerySegmentAggregator.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractIncludeRevincludeTest.java

The fixes:
(1) Paging on the main resource only.
(2) Make sure Include/revinclude resources are related to the main resources in the same page.

issue #346 paging fix for include/revinclude search

---

fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractIncludeRevincludeTest.java

add the missing request to get the second page

issue #346 fix test

---

fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/api/IDatabaseAdapter.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/api/IDatabaseTypeAdapter.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/db2/Db2Adapter.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyAdapter.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java

issue #377 changes for the db schema tool

---

fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/api/IDatabaseTypeAdapter.java

issue #377 minor change

---

fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/Main.java

issue #391 enabled jdbc performance metrics for db2

---

.github/workflows/build.yml
fhir-model/src/test/java/com/ibm/fhir/model/path/test/FHIRPathSpecTest.java
fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/Main.java

conditionally execute more tests from the github action

---

fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/Main.java
fhir-persistence-jdbc/src/test/resources/test.jdbc-perform.properties
fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchPerformaceTest.java

issue #400 #406 minor changes for 400 and add simpe testng performance test for search

---

fhir-examples/pom.xml
fhir-parent/pom.xml
fhir-parent/src/javadocs/stylesheet.css
fhir-tools/pom.xml

```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/
mvn site javadoc:aggregate -f fhir-parent/pom.xml -DskipTests  -X
```
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for IBM FHIR Server 4.0.0-SNAPSHOT:
[INFO]
[INFO] IBM FHIR Server .................................... SUCCESS [28:11 min]
[INFO] fhir-core .......................................... SUCCESS [ 21.551 s]
[INFO] fhir-database-utils ................................ SUCCESS [01:23 min]
[INFO] fhir-config ........................................ SUCCESS [ 21.890 s]
[INFO] fhir-audit ......................................... SUCCESS [ 23.351 s]
[INFO] fhir-model ......................................... SUCCESS [22:56 min]
[INFO] …
```

Javadocs #145

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/DerbyResourceDAO.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchQuantityTest.java
fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersUtil.java

see https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Quantity.20search.20and.20display.20units/near/180734154

issue #410 - index the display unit field even when a coded unit is present

---

fhir-examples/src/main/resources/json/all.txt
fhir-examples/src/main/resources/json/performance.txt

issue #427 update index files - all.txt and performance.txt

---

fhir-install/README-DB2.md

clean up documentation to make tag visible #270
-rm  seemed to be a stray entry into the docker commands

clean up documentation to make tag visible #270

---

fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathResourceNode.java
fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathType.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ConformsToFunction.java
fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
fhir-profile/src/main/java/com/ibm/fhir/profile/ProfileSupport.java
fhir-registry/src/main/java/com/ibm/fhir/registry/FHIRRegistry.java

Issue #475 - implement support for conformsTo function

---

fhir-path/src/main/java/com/ibm/fhir/path/function/IntersectFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/UnionFunction.java

Issue #403 - implement 'intersect' function

---

.github/workflows/site.yml

Fix workflow to remove forbidden shell scripts

---

fhir-registry/src/main/java/com/ibm/fhir/registry/FHIRRegistry.java

Issue #403 - tweak FHIRRegistry.hasResource method

---

fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/BodyWeightProfileTest.java

Issue #438 - initial version of 'memberOf' function

---

fhir-model/src/main/java/com/ibm/fhir/model/util/ValidationSupport.java
fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathTree.java
fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
fhir-path/src/test/java/com/ibm/fhir/path/test/FHIRPathTestResourceProvider.java
fhir-path/src/test/java/com/ibm/fhir/path/test/MemberOfFunctionTest.java
fhir-path/src/test/resources/META-INF/services/com.ibm.fhir.registry.spi.FHIRRegistryResourceProvider
fhir-path/src/test/resources/fhir-path.test.index
fhir-path/src/test/resources/resources/CodeSystem-cs1.json
fhir-path/src/test/resources/resources/ValueSet-vs1.json
fhir-profile/pom.xml
fhir-profile/src/main/java/com/ibm/fhir/profile/CodeSystemSupport.java
fhir-profile/src/main/java/com/ibm/fhir/profile/ValueSetSupport.java
fhir-profile/src/test/java/com/ibm/fhir/profile/test/FHIRProfileTestResourceProvider.java
fhir-profile/src/test/java/com/ibm/fhir/profile/test/ValueSetExpansionTest.java
fhir-profile/src/test/resources/META-INF/services/com.ibm.fhir.registry.spi.FHIRRegistryResourceProvider
fhir-profile/src/test/resources/fhir-profile.test.index
fhir-profile/src/test/resources/resources/CodeSystem-cs1.json
fhir-profile/src/test/resources/resources/CodeSystem-cs2.json
fhir-profile/src/test/resources/resources/CodeSystem-cs3.json
fhir-profile/src/test/resources/resources/CodeSystem-cs4.json
fhir-profile/src/test/resources/resources/CodeSystem-cs5.json
fhir-profile/src/test/resources/resources/ValueSet-vs1.json
fhir-profile/src/test/resources/resources/ValueSet-vs2.json
fhir-profile/src/test/resources/resources/ValueSet-vs3.json
fhir-profile/src/test/resources/resources/ValueSet-vs4.json
fhir-profile/src/test/resources/resources/ValueSet-vs5.json
fhir-registry/src/main/java/com/ibm/fhir/registry/FHIRRegistry.java
fhir-registry/src/main/java/com/ibm/fhir/registry/resource/FHIRRegistryResource.java

Issue #483 - 'memberOf' function refactor

---

fhir-path/src/main/java/com/ibm/fhir/path/function/ResolveFunction.java

Issue #512 - loosen reference type validation

---

docs/src/pages/index.mdx

Now it won't go stale every month

Change touchstone link to show all published results

---

.github/workflows/site.yml

Update workflow for valid user id

Update workflow for valid userid

---

fhir-server/liberty-config/config/default/fhir-server-config.json

Remove duplicate comment on fhir-server-config.json

---

fhir-operation/src/test/java/com/ibm/fhir/operation/test/CrashingOperation.java

javadoc:aggregate died on this file. 
I removed the non-javadoc and (cleaned up the @author per our style).  It now passes. 

build and post latest javadocs #533

---

.github/workflows/site.yml

Fix Site Automation

---

docs/src/pages/index.mdx

Forcing a Site / Docs build

---

.github/workflows/build.yml

Ignore buildpath

---

.github/workflows/build.yml
.github/workflows/site.yml

Upgrade to actions/checkout@v2

---

.github/workflows/javadocs.yml
fhir-parent/pom.xml

build and post latest javadocs

---

fhir-parent/pom.xml

Update JavaDoc plugin with comment on supporting 3.1 + 

---

fhir-server-webapp/src/main/webapp/WEB-INF/web.xml

Allow to run the Server without TLS #331

---

fhir-parent/pom.xml

Focus-stealing on the MacOSX Platform #570

---

build/bintray/upload-javadoc-source.sh

Source and Javadoc Jars are missing from 4.0.0 release artifactory #572

---

fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/db2/Db2GetTableInfo.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/db2/Db2GetTenantVariable.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/DatabaseObject.java
fhir-install/src/main/assembly/distribution.xml
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/SetTenantDAO.java
fhir-persistence-schema/README.md
fhir-persistence-schema/pom.xml
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/SchemaPrinter.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/AdminSchemaGenerator.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaGenerator.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/derby/DerbyFhirDatabase.java
fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/control/ParallelBuildTest.java

Introduce fhir-persistence-schema assembly and document usage #573

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/InclusionQuerySegmentAggregator.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/SortedQuerySegmentAggregator.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchIdAndLastUpdatedTest.java

_sort Search with Compartment fails due to unordered adding of parameters #590

---

fhir-server/src/test/java/com/ibm/fhir/server/test/ReferenceMappingVistorTest.java

- bad test
- blocked logging out the test data

update for #145

---

docs/src/pages/guides/FHIRServerUsersGuide.md
fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java

Issue #318 - additional tweaks / enhancements, updated documentation

---

.github/workflows/site.yml

Update site.yml for behavior change in checkout v2

---

docs/src/pages/guides/FHIRValidationGuide.md

Issue #565 - Initial draft of FHIR Validation Guide

---

.github/workflows/site.yml

Update site.yml to use v2 of checkout (missed one spot)

---

.github/workflows/javadocs.yml
fhir-examples/pom.xml
fhir-tools/pom.xml

Update for Failure in Workflow #145

---

docs/src/data/nav-items.yaml

Add NavItem for Validation Guide #612

---

.github/workflows/site.yml
build/release/release.sh
docs/readme.md
fhir-install/pom.xml
fhir-install/src/main/assembly/distribution.xml
fhir-persistence-schema/README.md
fhir-swagger-generator/README.md

Remove Duplicate fhir-persistence-schema dependency

---

.github/workflows/build.yml

With checkout@v2 we started getting `fatal: bad revision 'origin/master'`...this should fix that

Fetch target branch before diffing

---

.github/workflows/javadocs.yml
.github/workflows/site.yml

Verified on my repo - https://prb112.github.io/FHIR/build.txt 

Update Automation for GH Pages Triggers #620

---

.github/workflows/build.yml
fhir-model/src/main/java/com/ibm/fhir/model/util/ModelSupport.java
fhir-persistence-schema/pom.xml

added javadoc to all public methods in ModelSupport

---

build/release/release.sh

poms are missing from bintray #625

---

docs/readme.md

Trigger Site rebuild

---

docs/src/pages/guides/FHIRServerUsersGuide.md

issue #630 fix one doc error about javabatch config

---

fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/jdbc/ResultSetStub.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/jdbc/StatementStub.java
fhir-server/src/test/java/com/ibm/fhir/server/test/FHIRHttpServletRequestWrapperTest.java

Code Cleanliness: Address reported Errors in taglist report. #187

---

docs/src/pages/guides/FHIRServerUsersGuide.md

Fix link to Db2OnCloudSetup and point to fhir-persistence-schema doc

---

docs/src/data/nav-items.yaml

alternatively, we could update the content to cover setting up any db2, but thats more work

update navitem to clarify its for db2 on cloud

---

fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/group/ChunkReader.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/ExportOperationTest.java

issue #653 fix nest group expansion issue for group export and add tests

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java

System-Count when no data in system #656

---

docs/src/pages/Conformance.md
docs/src/pages/guides/FHIRSearchConfiguration.md

Document prefer header settings and clarify related search behavior

---

docs/src/data/nav-items.yaml
docs/src/pages/guides/BringYourOwnPersistence.md

issue #644 - fix BYOP nav-item and normalize the names

---

.github/workflows/build.yml

issue #668 - add http flags to try avoiding timeouts

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/NumberParmBehaviorUtil.java
fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/NumberParmBehaviorUtilTest.java
fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/QuantityParmBehaviorUtilTest.java

issue #707 - fix implicit range computations for scientific notation

---

fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java

I found out that if the originalRequestUri is relative, then JAX-RS will
add it to the base path instead or replacing the base path.
For example, a orginalRequestUri header value like `/original` would end
up producing a path like `http://host/fhir-server/api/v4/original`
instead of just `http://host/original`

issue #66 - validate the originalRequestUri and make it absolute

---

fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java

also replaced deprecated use of `FHIRUtil.getResourceTypeName(resource)`
with `ModelSupport.getTypeName(resource.getClass())`

issue #17 - update log msg and increase level for failed audit writes

---

CONTRIBUTING.md

I thought I had added this in the past, but apparently not

link to our dedicated zulip stream

---

fhir-model/src/test/java/com/ibm/fhir/model/test/CheckReferenceTypeTest.java
fhir-model/src/test/java/com/ibm/fhir/model/test/ResourceCoverageTest.java

issue #733 - fix

---

fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulktools/Main.java
fhir-client/src/main/java/com/ibm/fhir/client/impl/FHIRClientImpl.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchAllTest.java

issue #675 enable tenant/datastore support for searchalltest

---

fhir-server-test/src/test/java/com/ibm/fhir/server/test/BundleTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchAllTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchNearTest.java

Tests Log an Inordinate amount to Console #751

---

build/tests.ps1
fhir-server-test/src/test/java/com/ibm/fhir/server/test/UpdateTest.java

e2e windows tests report success even when e2e tests fail #698

---

fhir-examples/src/main/resources/json/ibm/basic/BasicQuantity.json
fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchQuantityTest.java
fhir-persistence/src/test/resources/config/quantity/extension-search-parameters.json

Increase Quantity Test Coverage #762

---

README.md

Let's try remembering to update our README when we add, remove, or change the scope a module

added fhir-operation-convert to readme

---

fhir-model/src/main/java/com/ibm/fhir/model/util/ValidationSupport.java

The current message was very confusing in the case the passed
Reference.type is itself not an allowed type

Rework ValidationSupport error messages

---

fhir-server/liberty-config/batchDs.xml

Use proper env var syntax in batchDs.xml sample config

---

fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
fhir-registry/src/main/java/com/ibm/fhir/registry/FHIRRegistry.java

Issue #661 - updated copyright and fixed Javadoc

---

fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaGenerator.java

addLatLngValuesTypes is dead code #799

---

docs/src/pages/guides/FHIRValidationGuide.md

Issue #661 - minor markdown tweaks

---

fhir-persistence-schema/src/main/resources/add_any_resource.sql

remove stale content from comment

---

fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ConformsToFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/util/FHIRPathUtil.java
fhir-path/src/test/java/com/ibm/fhir/path/test/MemberOfFunctionTest.java

Issue #684 - add support for value set membership check with in operator

---

fhir-install/README.md

updated stale content

---

fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/Table.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/VersionedSchemaObject.java

migration issue with embedded versions (hard coded in two spots)

---

fhir-install/docker/Dockerfile-ol

lock in to open-liberty 19.0.0.12

---

fhir-install/README-DB2.md
fhir-install/docker/Dockerfile-ol

DB2 docker file name incorrect (#824)

---

fhir-persistence-schema/docs/DB2SchemaMigration.md

Fix FHIRResourceType.ValueSet issue in docs

---

fhir-persistence-schema/README.md

--add-tenant-key missing in docs #846

---

docs/src/pages/guides/DB2OnCloudSetup.md

Enhance documentation for Db2 on Cloud Field Mapping #821

---

docs/src/pages/guides/DB2OnCloudSetup.md

Fix for macro error on Gatsby #821

---

fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java

we already had a flag for this, i just made it true by default
i also updated the definition to say it returns HTTP 204 (No Content) on
success (vs 200 OK)

issue #851 - add delete to the pre-packed openapi

---

fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java

We found that certain Swagger/OpenAPI tooling was attempting to generate
examples if none were provided in the Swagger/OpenAPI definitions.
Unfortunately, the infinite recursion in the FHIR schema was tripping them up.
A more complete fix would be to generate our own examples for all FHIR
data types, but this change (just adding a couple selective examples)
should be sufficient for avoiding the MAX_DEPTH_ERROR we've seen in
API Connect.

Generate examples for Element.extension and Identifier.assigner

---

fhir-ig-carin-bb/pom.xml
fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/ConstraintGeneratorTest.java
fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java

Issue #871, Issue #872 - fix constraint generation issues

---

README.md

Update Readme.md with additional components

---

fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/BaseObject.java
fhir-database-utils/src/main/java/com/ibm/fhir/task/core/impl/TaskManager.java

issue #843 - update log message to make it more clear that it retries

---

.github/workflows/javadocs.yml
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyMaster.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/Sequence.java
fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesProcessor.java
fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesTest.java
fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/DerbyInitializer.java
fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/NumberParmBehaviorUtilTest.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/derby/DerbyFhirDatabase.java

- Update for Javadocs.yml to move to correct folder
- Update the Code to Support multiple runs of Builds
- Sequence only accepts a first version
- DerbyMaster is optimized

Update for 4.1.0 Release

---

docs/src/pages/guides/FHIRServerUsersGuide.md

Clarified per question from a user. 

Clarifying $healthcheck

---

docs/src/pages/guides/DB2OnCloudSetup.md

Update DB2OnCloudSetup.md #893

---

docs/src/pages/Conformance.md
fhir-config/src/main/java/com/ibm/fhir/config/FHIRRequestContext.java

issue #823 - documented extended operations in Conformance.md

---

fhir-ig-carin-bb/src/main/java/com/ibm/fhir/ig/carin/bb/BBResourceProvider.java
fhir-ig-mcode/src/main/java/com/ibm/fhir/ig/mcode/MCODEResourceProvider.java
fhir-ig-us-core/src/main/java/com/ibm/fhir/ig/us/core/USCoreResourceProvider.java
fhir-path/src/test/java/com/ibm/fhir/path/test/FHIRPathTestResourceProvider.java
fhir-profile/src/test/java/com/ibm/fhir/profile/test/FHIRProfileTestResourceProvider.java
fhir-registry/src/main/java/com/ibm/fhir/registry/FHIRRegistry.java
fhir-registry/src/main/java/com/ibm/fhir/registry/core/CoreResourceProvider.java
fhir-registry/src/main/java/com/ibm/fhir/registry/spi/FHIRRegistryResourceProvider.java
fhir-registry/src/main/java/com/ibm/fhir/registry/util/FHIRRegistryUtil.java
fhir-registry/src/main/java/com/ibm/fhir/registry/util/Index.java
fhir-registry/src/main/java/com/ibm/fhir/registry/util/PackageRegistryResourceProvider.java

Issue #832 - FHIRRegistry refactoring

---

build/pre-integration-test.ps1
fhir-install/src/main/resources/scripts/install.bat
fhir-install/src/main/resources/scripts/install.sh
fhir-parent/pom.xml

Update to liberty 20.0.0.3

---

fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java

Liberty openapi processor complains of invalid UTF-8 on windows #902

---

README.md

fix link to dockerhub repo

---

fhir-ig-carin-bb/src/main/java/com/ibm/fhir/ig/carin/bb/BBResourceProvider.java
fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/BBResourceProviderTest.java
fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/ConstraintGeneratorTest.java
fhir-ig-mcode/src/main/java/com/ibm/fhir/ig/mcode/MCODEResourceProvider.java
fhir-ig-mcode/src/test/java/com/ibm/fhir/ig/mcode/test/ConstraintGeneratorTest.java
fhir-ig-mcode/src/test/java/com/ibm/fhir/ig/mcode/test/MCODEResourceProviderTest.java
fhir-ig-us-core/src/main/java/com/ibm/fhir/ig/us/core/USCoreResourceProvider.java
fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/USCoreResourceProviderTest.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ConformsToFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
fhir-path/src/test/java/com/ibm/fhir/path/test/FHIRPathTestResourceProvider.java
fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
fhir-profile/src/main/java/com/ibm/fhir/profile/ProfileSupport.java
fhir-profile/src/main/java/com/ibm/fhir/profile/ValueSetSupport.java
fhir-profile/src/test/java/com/ibm/fhir/profile/test/FHIRProfileTestResourceProvider.java
fhir-registry/src/main/java/com/ibm/fhir/registry/FHIRRegistry.java
fhir-registry/src/main/java/com/ibm/fhir/registry/core/CoreResourceProvider.java
fhir-registry/src/main/java/com/ibm/fhir/registry/resource/FHIRRegistryResource.java
fhir-registry/src/main/java/com/ibm/fhir/registry/spi/FHIRRegistryResourceProvider.java
fhir-registry/src/main/java/com/ibm/fhir/registry/util/FHIRRegistryUtil.java
fhir-registry/src/main/java/com/ibm/fhir/registry/util/PackageRegistryResource.java
fhir-registry/src/main/java/com/ibm/fhir/registry/util/PackageRegistryResourceProvider.java
fhir-registry/src/test/java/com/ibm/fhir/registry/core/test/CoreResourceProviderTest.java
fhir-registry/src/test/java/com/ibm/fhir/registry/core/test/FHIRRegistryTest.java
fhir-registry/src/test/java/com/ibm/fhir/registry/core/test/VitalSignsProfileTest.java
fhir-server/src/main/java/com/ibm/fhir/server/listener/FHIRServletContextListener.java

Issue #832 - additional refactoring

---

fhir-model/src/main/java/com/ibm/fhir/model/type/Base64Binary.java
fhir-model/src/test/java/com/ibm/fhir/model/test/Base64BinaryTest.java
fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java

Issue #918 - added validation for incorrect padding

---

fhir-server/liberty-config/jvm.options
fhir-server/liberty-config/server.xml

As recommended at https://www.hl7.org/fhir/security.html#http

issue #941 - force the use of TLSv1.2

---

fhir-model/src/main/java/com/ibm/fhir/model/type/Base64Binary.java
fhir-model/src/main/java/com/ibm/fhir/model/util/ValidationSupport.java
fhir-model/src/test/java/com/ibm/fhir/model/test/Base64BinaryTest.java
fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java

Issue #918 - additional validation added and moved to ValidationSupport

---

docs/src/pages/guides/FHIRServerUsersGuide.md
fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
fhir-profile/src/main/java/com/ibm/fhir/profile/ProfileSupport.java
fhir-registry/src/main/java/com/ibm/fhir/registry/FHIRRegistry.java
fhir-registry/src/main/java/com/ibm/fhir/registry/spi/FHIRRegistryResourceProvider.java
fhir-registry/src/main/java/com/ibm/fhir/registry/util/FHIRRegistryUtil.java
fhir-registry/src/main/java/com/ibm/fhir/registry/util/PackageRegistryResource.java
fhir-registry/src/main/java/com/ibm/fhir/registry/util/PackageRegistryResourceProvider.java
fhir-server/liberty-config/config/default/fhir-server-config.json
fhir-server/src/main/java/com/ibm/fhir/server/listener/FHIRServletContextListener.java
fhir-server/src/main/java/com/ibm/fhir/server/registry/ServerRegistryResource.java
fhir-server/src/main/java/com/ibm/fhir/server/registry/ServerRegistryResourceProvider.java

Issue #889 - Initial implementation of ServerRegistryResourceProvider

---

fhir-profile/src/main/java/com/ibm/fhir/profile/ProfileSupport.java
fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/BundleValidationTest.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/FHIRValidatorTest.java

Issue #933 - add profile reference validation to FHIRValidator

---

fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java

Issue #933 - Remove printStackTrace from catch block

---

docs/src/pages/guides/FHIRValidationGuide.md

Issue #832 - updated validation documentation

---

fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java
fhir-server/src/main/java/com/ibm/fhir/server/listener/FHIRServletContextListener.java

Cleanup NPE when the server starts with no fhir-server-config

---

.github/workflows/build.yml
fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionAnalyzer.java
fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionCollector.java

Fixed: aggregated the in-fly import rate calculation across all the partitions.

issue #941 aggregate in-fly metrics across all the partitions

---

fhir-model/src/main/java/com/ibm/fhir/model/visitor/PathAwareVisitor.java
fhir-model/src/test/java/com/ibm/fhir/model/test/PathAwareVisitorTest.java
fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
fhir-path/src/test/java/com/ibm/fhir/path/test/FHIRPathEvaluatorTest.java
fhir-path/src/test/java/com/ibm/fhir/path/test/FHIRPathSpecTest.java
fhir-path/src/test/java/com/ibm/fhir/path/test/FHIRPathTreeTest.java
fhir-path/src/test/java/com/ibm/fhir/path/test/ResolveFunctionTest.java
fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
fhir-search/src/test/java/com/ibm/fhir/search/test/ExtractParameterValuesTest.java
fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/ActivityDefinitionTest.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/BloodPressureObservationTest.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/BundleValidationTest.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/CareTeamTest.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/FHIRValidatorTest.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/PlanDefinitionTest.java

Issue #932, Issue #933 - changed console debug to JUL logging

---

fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/BBValidationTest.java
fhir-ig-carin-bb/src/test/resources/JSON/eob-no-identifier-asserted.json
fhir-ig-carin-bb/src/test/resources/JSON/eob-no-identifier-not-asserted.json
fhir-ig-carin-bb/src/test/resources/XML/eob-no-identifier-asserted.xml
fhir-ig-carin-bb/src/test/resources/XML/eob-no-identifier-not-asserted.xml
fhir-ig-mcode/src/main/resources/hl7/fhir/us/mcode/package/StructureDefinition-mcode-cancer-disease-status.json
fhir-ig-mcode/src/test/java/com/ibm/fhir/ig/mcode/test/MCODEValidationTest.java
fhir-ig-mcode/src/test/resources/JSON/mcode-cancer-disease-status-no-subject-asserted.json
fhir-ig-mcode/src/test/resources/JSON/mcode-cancer-disease-status-no-subject-not-asserted.json
fhir-ig-mcode/src/test/resources/XML/mcode-cancer-disease-status-no-subject-asserted.xml
fhir-ig-mcode/src/test/resources/XML/mcode-cancer-disease-status-no-subject-not-asserted.xml
fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/ConformsToTest.java
fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/USCoreValidationTest.java
fhir-ig-us-core/src/test/resources/JSON/us-core-patient-no-name-asserted.json
fhir-ig-us-core/src/test/resources/JSON/us-core-patient-no-name-not-asserted.json
fhir-ig-us-core/src/test/resources/XML/us-core-patient-no-name-asserted.xml
fhir-ig-us-core/src/test/resources/XML/us-core-patient-no-name-not-asserted.xml
fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
fhir-validation/src/main/java/com/ibm/fhir/validation/util/FHIRValidationUtil.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/FHIRValidatorTest.java
fhir-validation/src/test/resources/JSON/bp-missing-code-asserted.json
fhir-validation/src/test/resources/JSON/bp-missing-code-not-asserted.json
fhir-validation/src/test/resources/XML/bp-missing-code-asserted.xml
fhir-validation/src/test/resources/XML/bp-missing-code-not-asserted.xml

Issue #926 - created more examples / unit tests for profile validation

---

docs/src/pages/guides/FHIRServerUsersGuide.md

Replace TODO with a link to the Validation Guide

---

docs/src/pages/guides/FHIRValidationGuide.md

More info on packaging registry resource providers for the server

---

fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/api/IDatabaseTypeAdapter.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/ClobColumn.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgresql/PostgreSqlAdapter.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgresql/PostgreSqlResourceDAO.java

Added postgresql support for clob column with mapping to TEXT.

issue #969 support clob column for postgresql

---

fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/USCoreEthnicityExtensionTest.java
fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/USCoreRaceExtensionTest.java
fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java

Issue #959 - added us-core extension unit tests

---

fhir-profile/src/main/java/com/ibm/fhir/profile/ValueSetSupport.java

Issue #971 - add logic determine the expandability of value sets

---

docs/src/pages/guides/DB2OnCloudSetup.md
docs/src/pages/guides/FHIRServerUsersGuide.md
fhir-persistence-schema/README.md

1. update DB2OnCloudSetup docs to include schema deployment
2. minor updates to the user's guide and persistence-schema readme

Update db2-related docs

---

fhir-path/src/main/java/com/ibm/fhir/path/function/ConformsToFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
fhir-profile/src/main/java/com/ibm/fhir/profile/ValueSetSupport.java

Issue #971 - Javadoc typo and minor tweak

---

fhir-server/liberty-config/configDropins/defaults/bulkdata.xml

issue #977 remove derby config from bulkdata.xml

---

fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/Sequence.java
fhir-model/src/main/java/com/ibm/fhir/model/util/ValidationSupport.java
fhir-notification/src/main/java/com/ibm/fhir/notification/FHIRNotificationService.java

the FHIRNotificationServer edits are just some style changes I had sitting around; I got sick of carrying them to each branch

NPE fix in Sequence.apply, minor javadoc fix,  and minor style changes to FHIRNotificationService

---

fhir-persistence-schema/README.md

 fhir-persistence-schema - Update for additional property #986

---

fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
fhir-config/src/test/resources/fhirConfig.json
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
fhir-server/liberty-config/config/default/fhir-server-config-db2.json
fhir-server/liberty-config/config/default/fhir-server-config-postgresql.json
fhir-server/liberty-config/config/default/fhir-server-config.json

remove defunct truststore properties from FHIRConfiguration and sample configs

---

fhir-install/Dockerfile

this fixes the docker build issue reported in #999 

Issue 999 - added --nobest to yum update in dockerbuild

---

docs/src/pages/guides/FHIRServerUsersGuide.md
fhir-server/src/main/java/com/ibm/fhir/server/listener/FHIRServletContextListener.java

make useTLS true if the config prop is missing and fix docs

---

fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
fhir-path/src/test/java/com/ibm/fhir/path/test/FHIRPathExistsTest.java

Issue #1011 - fixed bug in exists function

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/DerbyBootstrapper.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java

If the FHIR datamodel already exists, it may have different resource
type ids (or parameter name ids) already, so we only want to pre-populate NEW deployments.

issue #811 - add guard to prevent populate logic for existing dbs

---

docs/src/pages/guides/FHIRServerUsersGuide.md
fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
fhir-config/src/main/java/com/ibm/fhir/config/FHIRRequestContext.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FHIRDbDAOImpl.java
fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java

Improve the Exception Case for Db2 Configured Multitenancy #1018

---

fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/derby/DerbyFhirDatabase.java

Duplicate Entry on Execution of Batch with Build #1024

---

.github/workflows/javadocs.yml

Fix for Javadoc Ordering

---

.github/workflows/release.yml
build/release/diagnostics.sh
build/release/release.sh

Fix Build Issue with Size of Upload

---

build/release/docker-push.sh

add explicit build and tag steps in docker-push.sh

---

fhir-model/src/main/java/com/ibm/fhir/model/visitor/PathAwareVisitor.java
fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java

reduce log level of validation and fhirpath evaluation

---

fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
fhir-config/src/main/java/com/ibm/fhir/config/FHIRRequestContext.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FHIRDbDAOImpl.java
fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java

Set Context Invalid in Multi-tenant Db2 #1032

---

fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathAbstractTemporalValue.java
fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathDateTimeValue.java
fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathDateValue.java
fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathTemporalValue.java
fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathTimeValue.java
fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
fhir-path/src/main/java/com/ibm/fhir/path/function/BetweenFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ConvertsToBooleanFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ConvertsToDateFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ConvertsToDateTimeFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ConvertsToTimeFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/NotFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/NowFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/TimeOfDayFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ToBooleanFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ToDateFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ToTimeFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/TodayFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/registry/FHIRPathFunctionRegistry.java
fhir-path/src/main/java/com/ibm/fhir/path/util/FHIRPathUtil.java
fhir-path/src/test/java/com/ibm/fhir/path/test/BetweenFunctionTest.java
fhir-path/src/test/java/com/ibm/fhir/path/test/BooleanEvaluationTest.java
fhir-path/src/test/java/com/ibm/fhir/path/test/DateTimeComparisonTest.java
fhir-path/src/test/resources/FHIRPath/tests-fhir-r4.xml
fhir-path/src/test/resources/fhir-path-patch-tests.CHANGELOG

Issue #1014 - added between function

---

.github/workflows/build.yml
.github/workflows/release.yml

Update release.yml (cleanup name on release package)

---

docs/src/pages/guides/FHIRServerUsersGuide.md
fhir-operation-bulkdata/src/test/resources/testdata/config/default/fhir-server-config.json
fhir-server/liberty-config/config/default/fhir-server-config-db2.json
fhir-server/liberty-config/config/default/fhir-server-config-postgresql.json
fhir-server/liberty-config/config/default/fhir-server-config.json

Configs and Docs reference updates to fhirTrustStore.p12 #1045

---

docs/src/data/nav-items.yaml
docs/src/pages/Conformance.md
docs/src/pages/guides/FHIRBulkOperations.md

Document the Export Import Usage #1047

---

fhir-model/src/main/java/com/ibm/fhir/model/util/ValidationSupport.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ResolveFunction.java

Issue #1062 - info messages only when reference and/or type not null

---

fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/version/VersionHistoryService.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/DerbyBootstrapper.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/SchemaPrinter.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/derby/DerbyFhirDatabase.java
fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/derby/DerbyMigrationTest.java

the update-schema is stopped. #1065

Upon Second Schema deployment, VersionHistoryService reports error and

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/FHIRResourceDAOFactory.java

Updated FHIRResourceDAOFactory to make it more robust/accurate to DB types.

issue #1064 make FHIRResourceDAOFactory more robust/accurate to db type

---

fhir-server/src/main/java/com/ibm/fhir/server/registry/ServerRegistryResourceProvider.java

Issue #1069 - make registry resource cache tenant-aware

---

fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/FHIRValidatorTest.java

Issue #1072 - move extension validation (conformsTo) to FHIRValidator

---

fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java

Fix for testTenant issue

---

build/release/release.sh

Update release.sh to push validation package

---

build/release/build.sh
docs/src/pages/guides/CreateFHIRValidationAssembly.md
fhir-validation/pom.xml

Update release to include ig in the release

---

docs/src/pages/guides/FHIRServerUsersGuide.md
fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
fhir-server/liberty-config/config/default/fhir-server-config-db2.json
fhir-server/liberty-config/configDropins/disabled/cloud.xml
fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java

- Update cloud.xml to point to the location ( per warning in eclipse)
- Update Capabilities statement to use a concurrent hash map
- Cache time is one hour

Add cache support for the capabilites request #734

---

fhir-benchmark/src/main/java/com/ibm/fhir/benchmark/FHIRParserValidatorGeneratorBenchmark.java
fhir-benchmark/src/main/java/com/ibm/fhir/benchmark/FHIRPatchBenchmark.java
fhir-benchmark/src/main/java/com/ibm/fhir/benchmark/FHIRPathEvaluatorBenchmark.java
fhir-benchmark/src/main/java/com/ibm/fhir/benchmark/FHIRValidatorBenchmark.java
fhir-benchmark/src/main/java/com/ibm/fhir/benchmark/FHIRValueSetBenchmarks.java
fhir-benchmark/src/main/java/com/ibm/fhir/benchmark/runner/FHIRBenchmarkRunner.java

Issue #1091 - fix broken benchmarks

---

fhir-install/pom.xml

Add plan-net to the server distribution

---

fhir-registry/src/main/java/com/ibm/fhir/registry/FHIRRegistry.java
fhir-registry/src/test/java/com/ibm/fhir/registry/test/FHIRRegistryLatestVersionTest.java

Issue #1092 - look at all providers to determine latest version

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchNearTest.java

- Fix for Chained Parameters
- Fix for Location Search

NPE during chained location search #1098

---

fhir-operation-bulkdata/src/main/resources/import.json
fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/support/bulkdata/helpers/ImportOperationDefinitionGenerator.java

Fix name for import

---

fhir-examples/src/main/java/com/ibm/fhir/examples/Index.java
fhir-examples/src/main/resources/json/profiles/fhir-ig-carin-bb/Coverage-Coverage1.json
fhir-examples/src/main/resources/json/profiles/fhir-ig-carin-bb/ExplanationOfBenefit-EOB1.json
fhir-examples/src/main/resources/json/profiles/fhir-ig-carin-bb/Organization-Org1.json
fhir-examples/src/main/resources/json/profiles/fhir-ig-carin-bb/Organization-Org45.json
fhir-examples/src/main/resources/json/profiles/fhir-ig-carin-bb/Patient-Patient1.json
fhir-examples/src/main/resources/json/profiles/fhir-ig-carin-bb/PractitionerRole-PractitionerRole1.json
fhir-examples/src/main/resources/json/profiles/fhir-ig-carin-bb/README.md
fhir-examples/src/main/resources/profiles-fhir-ig-carin-bb-json.txt
fhir-examples/src/main/resources/profiles-fhir-ig-carin-bb-xml.txt
fhir-examples/src/main/resources/xml/profiles/fhir-ig-carin-bb/Coverage-Coverage1.xml
fhir-examples/src/main/resources/xml/profiles/fhir-ig-carin-bb/ExplanationOfBenefit-EOB1.xml
fhir-examples/src/main/resources/xml/profiles/fhir-ig-carin-bb/Organization-Org1.xml
fhir-examples/src/main/resources/xml/profiles/fhir-ig-carin-bb/Organization-Org45.xml
fhir-examples/src/main/resources/xml/profiles/fhir-ig-carin-bb/Patient-Patient1.xml
fhir-examples/src/main/resources/xml/profiles/fhir-ig-carin-bb/PractitionerRole-PractitionerRole1.xml
fhir-examples/src/main/resources/xml/profiles/fhir-ig-carin-bb/README.md
fhir-ig-carin-bb/pom.xml
fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/ExamplesValidationTest.java

Add Carin IG FHIR Examples

---

build/release/build.sh
docs/src/pages/guides/CreateFHIRValidationAssembly.md
fhir-install/pom.xml
fhir-install/src/main/assembly/distribution.xml
fhir-validation/pom.xml

Distribution

---

docs/src/pages/guides/FHIRValidationGuide.md
fhir-examples/src/main/resources/profiles-fhir-ig-carin-bb-json.txt
fhir-examples/src/main/resources/profiles-fhir-ig-carin-bb-xml.txt
fhir-ig-carin-bb/pom.xml
fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/BBValidationTest.java
fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/ExamplesValidationTest.java
fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java

Issue #1107 - add support for Identifier pattern value constraints

---

fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/FHIRValidationTestResourceProvider.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/ProfileConstraintTest.java
fhir-validation/src/test/resources/META-INF/services/com.ibm.fhir.registry.spi.FHIRRegistryResourceProvider
fhir-validation/src/test/resources/fhir/validation/test/package/.index.json
fhir-validation/src/test/resources/fhir/validation/test/package/my-coverage.json
fhir-validation/src/test/resources/fhir/validation/test/package/my-extension.json
fhir-validation/src/test/resources/fhir/validation/test/package/period-with-my-extension.json

Issue #1117 - generate constraints for profiled types

---

build/release/build.sh

Fix for missing installable

---

build/release/release.sh

Fix for Release

---

fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
fhir-term/src/main/java/com/ibm/fhir/term/service/provider/DefaultTermServiceProvider.java
fhir-term/src/main/java/com/ibm/fhir/term/spi/FHIRTermServiceProvider.java

Issue #1142 - move code validation logic to DefaultTermServiceProvider

---

fhir-validation/src/test/java/com/ibm/fhir/validation/test/ValidationProcessor.java

Turn down logging for ValidationProcessor #1133

---

fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
fhir-term/src/main/java/com/ibm/fhir/term/service/provider/DefaultTermServiceProvider.java
fhir-term/src/main/java/com/ibm/fhir/term/spi/FHIRTermServiceProvider.java

Issue #1142 - add isExpandable to FHIRTermServiceProvider

---

fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathNumberValue.java
fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
fhir-term/src/main/java/com/ibm/fhir/term/service/provider/DefaultTermServiceProvider.java
fhir-term/src/main/java/com/ibm/fhir/term/spi/FHIRTermServiceProvider.java
fhir-term/src/main/java/com/ibm/fhir/term/util/ConceptMapSupport.java
fhir-term/src/test/java/com/ibm/fhir/term/service/test/FHIRTermServiceTest.java
fhir-term/src/test/resources/fhir/term/service/test/package/.index.json
fhir-term/src/test/resources/fhir/term/service/test/package/ConceptMap-snomed-ucum.json
fhir-term/src/test/resources/fhir/term/service/test/package/conceptmap-ibm-snomed-ucum.json

Issue #1148 - default translate implementation

---

fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
fhir-term/src/main/java/com/ibm/fhir/term/service/provider/DefaultTermServiceProvider.java
fhir-term/src/main/java/com/ibm/fhir/term/spi/FHIRTermServiceProvider.java
fhir-term/src/main/java/com/ibm/fhir/term/spi/Match.java
fhir-term/src/main/java/com/ibm/fhir/term/util/ConceptMapSupport.java
fhir-term/src/test/java/com/ibm/fhir/term/service/test/FHIRTermServiceTest.java

Issue #1148 - introduced class to represent match result for translate

---

fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/group/ChunkReader.java
fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/patient/ChunkReader.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ExportOperationTest.java

issue #1111 export patient resources for patient/group exports

---

fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaConstants.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaGenerator.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/OAuthSchemaGenerator.java

fhir-persistence-schema GRANT must consider resource #1169

---

fhir-client/pom.xml
fhir-provider/pom.xml

issue #1166 - exclude unnecessary LGPL CXF dependencies

---

fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java

issue #1180 - use sp code instead of name in CapabilityStatement

---

docs/src/pages/guides/FHIRBulkOperations.md

issue #767 user guide update for job auto-restart

---

README.md

and updated the fhir-term description

added fhir-operation-term to the module list

---

fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/CodeSystemValidateCodeOperation.java
fhir-path/pom.xml
fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathNode.java
fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathTermServiceNode.java
fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathTree.java
fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathType.java
fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ConformsToFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ExpandFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/FHIRPathAbstractFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/FHIRPathAbstractTermFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/LookupFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ResolveFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/SubsumedByFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/SubsumesFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/TranslateFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ValidateCSFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ValidateVSFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/registry/FHIRPathFunctionRegistry.java
fhir-path/src/test/java/com/ibm/fhir/path/test/FHIRPathTermFunctionTest.java
fhir-path/src/test/resources/fhir/path/test/package/.index.json
fhir-path/src/test/resources/fhir/path/test/package/CodeSystem-cs1.json
fhir-path/src/test/resources/fhir/path/test/package/CodeSystem-cs5.json
fhir-path/src/test/resources/fhir/path/test/package/ConceptMap-snomed-ucum.json
fhir-term/src/main/java/com/ibm/fhir/term/service/util/FHIRTermServiceUtil.java
fhir-term/src/main/java/com/ibm/fhir/term/spi/LookupOutcome.java

Issue #1184 - FHIRPath terminology functions

---

fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/CodeSystemValidateCodeOperation.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ValidateCSFunction.java

Issue #1184 - minor validation logic cleanup

---

docs/src/data/nav-items.yaml
docs/src/pages/guides/FHIRTerminologyGuide.md

Issue #1182 - created FHIRTerminologyGuide

---

fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathTermServiceNode.java
fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ExpandFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/FHIRPathAbstractTermFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/LookupFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/SubsumedByFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/SubsumesFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/TranslateFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ValidateCSFunction.java
fhir-path/src/main/java/com/ibm/fhir/path/function/ValidateVSFunction.java

Issue #1184 - refactored FHIRPathAbstractTermFunction

---

docs/src/pages/guides/FHIRTerminologyGuide.md

Issue #1182 - updates to the FHIR Terminology Guide

---

fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/ObservationProfileTest.java
fhir-validation/src/test/resources/fhir/validation/test/package/.index.json
fhir-validation/src/test/resources/fhir/validation/test/package/my-observation.json

Issue #1221 - added short-circuit logic for cardinality constraint

---

fhir-model/src/main/java/com/ibm/fhir/model/parser/FHIRJsonParser.java
fhir-parent/pom.xml
fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java

Issue #1215 - improved JSON parser error handling / messages

---

fhir-model/src/main/java/com/ibm/fhir/model/generator/FHIRXMLGenerator.java
fhir-model/src/main/java/com/ibm/fhir/model/util/XMLSupport.java

Issue #1226 - ensure that the correct implementation classes are used

---

.github/workflows/build.yml
build/tests.ps1
fhir-server-test/src/test/java/com/ibm/fhir/server/test/websocket/WebSocketNotificationsTest.java
fhir-server-test/src/test/resources/test.properties
fhir-server/liberty-config/config/default/fhir-server-config.json

issue #1214 - disable websockets notifications in the default config

---

.github/workflows/build.yml
.github/workflows/javadocs.yml
build/release/build.sh
build/release/check-dependency-security.sh
build/release/clean.sh
build/release/code-coverage.sh
build/release/docker-push.sh
build/release/release.sh

Fix for Maven Wagon Pool failures, add a retry

---

fhir-profile/src/main/java/com/ibm/fhir/profile/ProfileSupport.java

not contain a snapshot #1230
- Added a Snapshot/Elements check to Profile Support

NPE exception when attempting to validate against a profile that does

---

.github/workflows/build.yml
fhir-parent/pom.xml

Fix for Maven Build Wagon/Connection Reset and Timeout Issues

---

conformance/fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/USCoreValidationTest.java
fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java

Issue #1243 - include slice discriminator in optional constraints

---

.github/workflows/build.yml

add more project paths to the list of forcing ALL index

---

operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java

Fix for Bad Srv Inst

---

build/release/release.sh

Fix 4.3.0 Release

---

build/release/release.sh

Fix for 430 release

---

build/release/release.sh

Fix for bad pom directory

---

build/release/release.sh

Fix Release

---

.github/workflows/build.yml
build/release/release.sh

Add Upload for two zip files outside of the loop

---

build/db2-migration-test-docker.sh
build/docker/deploySchemaAndTenant.sh
build/pre-integration-test-docker.sh
build/pre-integration-test.sh

Fix for Build Slowdowns with db2 #1251

---

docs/src/gatsby-theme-carbon/components/AutolinkHeader/AutolinkHeader.js
docs/src/gatsby-theme-carbon/components/AutolinkHeader/AutolinkHeader.module.scss

 All subsection links are broken in the FHIR Server User's Guide #1261

---

fhir-term/src/main/java/com/ibm/fhir/term/service/provider/DefaultTermServiceProvider.java

Issue #1278 - updated buildValidationOutcome to avoid potential NPE

---

build/persistence/postgres/pre-integration-test.sh
fhir-model/src/main/java/com/ibm/fhir/model/resource/Resource.java
fhir-model/src/main/java/com/ibm/fhir/model/type/Element.java
fhir-server/src/main/java/com/ibm/fhir/server/resources/WellKnown.java
fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java

Also includes a minor update to our WellKnown document to exclude
registration_endpoint when its not configured.

Add javadoc for the toBuilder methods

---

build/db2-migration-test-docker.sh
build/pre-integration-test-docker.sh
build/pre-integration-test.sh

Update per build failures

---

fhir-model/src/main/java/com/ibm/fhir/model/util/ValidationSupport.java
fhir-term/src/main/java/com/ibm/fhir/term/service/provider/DefaultTermServiceProvider.java
fhir-term/src/test/java/com/ibm/fhir/term/service/test/TranslationPerformanceTest.java

Issue #1288 - performance improvements

---

fhir-model/src/main/java/com/ibm/fhir/model/resource/DiagnosticReport.java
fhir-model/src/main/java/com/ibm/fhir/model/resource/GuidanceResponse.java
fhir-model/src/main/java/com/ibm/fhir/model/resource/TestReport.java
fhir-tools/dependency-reduced-pom.xml
fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java

Issue #1295 - fixed hashCode method generation

---

fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
fhir-path/src/test/java/com/ibm/fhir/path/test/MemberOfFunctionTest.java
fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java

Issue #1213 - added support for value set binding on quantity

---

fhir-model/src/main/java/com/ibm/fhir/model/generator/GeneratingVisitor.java
fhir-model/src/main/java/com/ibm/fhir/model/util/ModelSupport.java
fhir-model/src/test/java/com/ibm/fhir/model/test/ChoiceElementNameTest.java

Issue #1302 - updated choice element name logic in GeneratingVisitor

---

fhir-server-test/src/test/java/com/ibm/fhir/server/test/BundleTest.java
fhir-server/liberty-config-tenants/config/tenant1/fhir-server-config.json
fhir-server/liberty-config/config/default/fhir-server-config.json
fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java

Issue #1319 - conditional update where new resource has no id

---

fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/ExtensionTest.java
fhir-validation/src/test/resources/fhir/validation/test/package/.index.json
fhir-validation/src/test/resources/fhir/validation/test/package/test-extension.json

Issue #1321 - add type check to required vocab constraints

---

operation/fhir-operation-apply/src/main/java/com/ibm/fhir/operation/apply/ApplyOperation.java
operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/model/PollingLocationResponseTest.java

- Remove Insecure Configuration with e.printStackTrace in ApplyOperation
- Fix issue with build in IST

Fix for Code Scans and IST Build Issues

---

operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/model/PollingLocationResponseTest.java

Fix issue with build in IST

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/SortedQuerySegmentAggregator.java

issue-1327 Use EXISTS instead of DISTINCT for better performance

---

build/release/release.sh

Fix for 4.3.1 Build

---

fhir-parent/pom.xml
fhir-server-test/pom.xml

We have a mix of slf4j versions, this fixes the versions to one version. 

Fix levels for slf4j

---

fhir-path/src/main/java/com/ibm/fhir/path/function/ResolveFunction.java

Duplicate Condition in Resolve

---

fhir-persistence-schema/README.md

README Update from Customer Feedback

---

conformance/fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/USCoreEthnicityExtensionTest.java
conformance/fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/USCoreRaceExtensionTest.java
fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/FamilyMemberHistoryTest.java
fhir-validation/src/test/resources/JSON/familymemberhistory.json
fhir-validation/src/test/resources/fhir/validation/test/package/.index.json
fhir-validation/src/test/resources/fhir/validation/test/package/my-family-member-history.json

Issue #1346 - generate exists clause for required repeating elements

---

fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgresql/PostgreSqlTranslator.java
fhir-persistence-schema/README.md

Fix for PostgresTranslator to Support Advanced Connections Properties

---

docs/src/pages/guides/DB2OnCloudSetup.md
docs/src/pages/guides/FHIRServerUsersGuide.md
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/connection/FHIRDbConnectionStrategy.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/connection/FHIRDbConnectionStrategyBase.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/connection/FHIRDbTestConnectionStrategy.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/connection/QueryHints.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/FHIRDbDAO.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FHIRDbDAOImpl.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/InclusionQuerySegmentAggregator.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregatorFactory.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/SortedQuerySegmentAggregator.java
fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/NumberParmBehaviorUtilTest.java
fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/QuantityParmBehaviorUtilTest.java
fhir-server/liberty-config/config/default/fhir-server-config-db2.json
fhir-server/liberty-config/config/default/fhir-server-config.json

issue #1354 add REOPT optimizer hint to Db2 search queries for better performance

---

README.md

Clarify what "API-stable" means

---

docs/src/pages/guides/FHIRBulkOperations.md
fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/jbatch/bulkdata/common/BulkDataUtils.java

Clarify support for http and https and cleanup logged error

---

build/persistence/postgres/README.md

Fix Readme.md

---

fhir-model/pom.xml
fhir-parent/pom.xml
fhir-path/pom.xml

Update to new version of jcip

---

.github/workflows/build.yml
operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java

replace '/' with '_' in bulkdata.path.prefix to avoid potential S3 exception

---

docs/gatsby-config.js

Fix for icon

---

fhir-server/src/main/java/com/ibm/fhir/server/util/FHIROperationUtil.java

Issue #1377 - added check to avoid NPE in FHIROperationUtil

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterDAOImpl.java
fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
fhir-search/src/test/java/com/ibm/fhir/search/parameters/MultiTenantSearchParameterTest.java
fhir-search/src/test/resources/config/default/extension-search-parameters.json
fhir-search/src/test/resources/config/tenant1/extension-search-parameters.json
fhir-search/src/test/resources/config/tenant3/extension-search-parameters.json
fhir-search/src/test/resources/config/tenant4/extension-search-parameters.json
fhir-search/src/test/resources/config/tenant5/extension-search-parameters.json
fhir-search/src/test/resources/config/tenant6/extension-search-parameters.json
fhir-search/src/test/resources/config/tenant6/fhir-server-config.json
fhir-server/liberty-config-tenants/config/tenant1/extension-search-parameters.json
operation/fhir-operation-healthcheck/src/main/resources/healthcheck.json
operation/fhir-operation-test/src/test/resources/operationdefinition-bad.json

extension-search-parameter.json using wildcard RESOURCE do not get extracted #1380

---

.github/workflows/build.yml
build/docker/docker-compose.yml

create a 200MB file and then remove it to reduce allocating writes during pipeline

reserve disk space early in build

---

build/docker/deploySchemaAndTenant.sh

- Cleanup bad condition in the script deploySchemaAndTenant.sh

---

fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/ReferenceExtensionTest.java
fhir-validation/src/test/resources/fhir/validation/test/package/.index.json
fhir-validation/src/test/resources/fhir/validation/test/package/test-reference-extension-with-target-profile.json
fhir-validation/src/test/resources/fhir/validation/test/package/test-reference-extension.json

Issue #1386 - fixed constraint generation issue

---

fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/api/IDatabaseAdapter.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/CommonDatabaseAdapter.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/CreateIndex.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/DataModelVisitor.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/DataModelVisitorBase.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/IndexDef.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceTableGroup.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaVersion.java

Issue 1331 need index for last_updated based search queries

---

fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersMap.java

add closing bracket to log message

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchAdvancedExpressionTest.java
fhir-server/liberty-config-tenants/config/tenant1/extension-search-parameters.json

- Demonstrates the advanced capabilities in FHIR Path (iff) and a custom
function (between) - extract-search-parameters.json
- Implements a Search Test using the advanced expression
- Fix NPE in the mapping to the DTO value from the extracted value

Add Advanced FHIR Path Expression Extraction and Search Test #1403

---

.github/workflows/build.yml
.github/workflows/integration.yml
.github/workflows/migration.yml

fix: Increase the Retry Handler Count for Wagon

---

fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfigHelper.java
fhir-parent/pom.xml
fhir-server/liberty-config/configDropins/disabled/keycloakRP.xml
fhir-smart/pom.xml
fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
fhir-smart/src/main/java/com/ibm/fhir/smart/Scope.java
fhir-smart/src/main/resources/META-INF/services/com.ibm.fhir.persistence.interceptor.FHIRPersistenceInterceptor
fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java

in this initial version, fhir-smart includes a single PersistenceInterceptor which uses java-jwt to decode
a passed token, parses the patient context from a "patient_id" claim, parses the granted scope string,
and checks these values against the interaction being performed.

issue #1352 - introduce fhir-smart component

---

fhir-model/src/main/java/com/ibm/fhir/model/util/ValidationSupport.java
fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
fhir-path/src/test/java/com/ibm/fhir/path/test/MemberOfFunctionTest.java
fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/DeviceProfileTest.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/MaxValueSetTest.java
fhir-validation/src/test/resources/fhir/validation/test/package/.index.json
fhir-validation/src/test/resources/fhir/validation/test/package/test-device.json
fhir-validation/src/test/resources/fhir/validation/test/package/test-language-others-opt-extension.json
fhir-validation/src/test/resources/fhir/validation/test/package/test-language-others-req-extension.json
fhir-validation/src/test/resources/fhir/validation/test/package/test-language-primary-extension.json
fhir-validation/src/test/resources/fhir/validation/test/package/test-language-secondary-extension.json
fhir-validation/src/test/resources/fhir/validation/test/package/test-language-tertiary-extension.json

This change adds validation of the maxValueSet defined for a binding, and validation of language codes against BCP-47 when all-languages is the value set.

issue #693 - memberOf handles maxValueSet and all-languages value set

---

fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/ReferenceExtensionTest.java
fhir-validation/src/test/resources/fhir/validation/test/package/.index.json
fhir-validation/src/test/resources/fhir/validation/test/package/test-reference-extension-with-multiple-target-profiles.json

Issue #1426 - fixed generation issue related to reference targets

---

.github/workflows/build.yml
.github/workflows/integration.yml
.github/workflows/migration.yml
.github/workflows/persistence.yml
.github/workflows/windows.yml

fix ignore path for workflows

---

README.md
docs/src/gatsby-theme-carbon/components/Footer.js
docs/src/gatsby-theme-carbon/components/Header.js

Update Site and Links per IBM Legal

---

build/security/asoc.sh
build/security/setup.sh

Implement Static Source Code Scanning #801

---

fhir-profile/src/main/java/com/ibm/fhir/profile/ProfileSupport.java
fhir-validation/src/test/java/com/ibm/fhir/validation/test/ProfileSupportTest.java
fhir-validation/src/test/resources/fhir/validation/test/package/.index.json

Issue #1447 - added null checking to ProfileSupport.isApplicable

---

build/security/asoc.sh

Fix for db2 jars being added

---

fhir-term/src/main/java/com/ibm/fhir/term/service/provider/DefaultTermServiceProvider.java
fhir-term/src/main/java/com/ibm/fhir/term/util/CodeSystemSupport.java
fhir-term/src/test/java/com/ibm/fhir/term/service/test/FHIRTermServiceTest.java
fhir-term/src/test/resources/fhir/term/service/test/package/CodeSystem-cs1.json
fhir-term/src/test/resources/fhir/term/service/test/package/CodeSystem-cs2.json

Issue #1454 - honor CodeSystem.caseSensitive element

---

fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
fhir-model/src/main/java/com/ibm/fhir/model/config/FHIRModelConfig.java

Issue #1421 - fix typo in extendedCodeableConceptValidation name

---

fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java

fix: double practitioner in SearchTest #1262

---

fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
fhir-search/src/test/java/com/ibm/fhir/search/test/InclusionParameterParseTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
fhir-server-test/src/test/resources/testdata/PractitionerRole.json
fhir-server-test/src/test/resources/testdata/Provenance.json

Issue #1262 - enable wildcard search for _include, _revinclude

---

fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java

valueUrl is used incorrectly in the CapabilityStatement #1496

---

fhir-examples/src/main/resources/json/profiles/fhir-ig-us-core/Bundle-66c8856b-ba11-4876-8aa8-467aad8c11a2.json
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/ProfilesTestBase.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreAllergyIntoleranceTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreDiagnosticReportLabTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreDiagnosticReportNoteTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreDocumentReferenceTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreEncounterTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreGoalTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreImmunizationTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreImplantableDeviceTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreLocationTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreMedicationRequestTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreMedicationTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreObservationLabTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreObservationPediatricBMIForAgeTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreObservationPediatricHeadOccipitalFrontalCircumferencePercentileTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreObservationPediatricWeightForHeightTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreObservationPulseOximetryTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreObservationSmokingStatusTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreOrganizationTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCorePatientTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCorePractitionerAndPractitionerRoleTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreProcedureTest.java

Created Tests for the following US Core profiles which exercise the
behaviors expected with the STU3 profile:
- US Core AllergyIntolerance Profile
- US Core CarePlan Profile
- US Core CareTeam Profile
- US Core Condition Profile
- US Core DiagnosticReport Profile for Laboratory Results Reporting
- US Core DiagnosticReport Profile for Report and Note exchange
- US Core Encounter Profile
- US Core Goal Profile
- US Core Immunization Profile
- US Core Implantable Device Profile
- US Core Laboratory Result Observation Profile
- US Core Location Profile
- US Core Medication Profile
- US Core Organization Profile
- US Core Pediatric BMI for Age Observation Profile
- US Core Pediatric Head Occipital-frontal Circumference Percentile
Profile
- US Core Pediatric Weight for Height Observation …

US-Core: Create Integration Tests for STU3 Release 3.1.1 #1311

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/connection/FHIRDbConstants.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/connection/FHIRDbProxyDatasourceConnectionStrategy.java

Remove unused constants from FHIRDbConstants #1305

---

docs/src/pages/guides/FHIRServerUsersGuide.md

Document postgresql as a persistence layer option

---

.github/workflows/build.yml
.github/workflows/integration.yml
.github/workflows/migration.yml
.github/workflows/windows.yml
build/docker/copy-test-operations.sh
build/persistence/bin/setup-prerequisites.sh
build/persistence/postgres/pre-integration-test.sh
build/pre-integration-test.sh
docs/src/pages/guides/FHIRServerUsersGuide.md
docs/src/pages/guides/FHIRValidationGuide.md
fhir-install/pom.xml
fhir-install/src/main/assembly/distribution.xml
fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/CarinBlueButtonTest.java

Added maven profile, include-fhir-igs, to include IGs optionally as part of build.

issue #1511 - Include FHIR IGs based on Maven profile

---

conformance/fhir-ig-davinci-pdex-formulary/pom.xml
conformance/fhir-ig-davinci-pdex-formulary/src/test/java/com/ibm/fhir/ig/davinci/pdex/formulary/test/ExamplesValidationTest.java

Had this sitting in my local workspace; I think I meant to commit it in
the past...

Add PDEX Formulary examples validation test

---

docs/src/pages/Conformance.md

changed two links to the new locations

doc: changed two links to the new locations

---

docs/src/gatsby-theme-carbon/components/AutolinkHeader/AutolinkHeader.js

fix: bad links

---

docs/src/gatsby-theme-carbon/components/AutolinkHeader/AutolinkHeader.js

fix: fat fingered the import

---

docs/src/pages/guides/FHIRServerUsersGuide.md

doc: fix link to cadf section

---

docs/src/data/nav-items.yaml
docs/src/pages/guides/FHIROperationFramework.md

doc: fhir operation framework

---

docs/src/pages/Conformance.md

Signed-off-by: Dag Roppe <roppe@us.ibm.com>

Added all non supported token modifiers in the list of not supported

---

fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/BaseObject.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java

fix: stored procedures are not updatable due to a missing boolean = true

---

docs/src/pages/guides/FHIRBulkOperations.md

Documentation for BulkImport javabatch job #809

---

docs/src/pages/guides/DB2OnCloudSetup.md

doc: update referenced db2 in the db2 on cloud setup

---

docs/src/pages/guides/FHIRServerUsersGuide.md
fhir-model/src/test/java/com/ibm/fhir/model/test/TestUtil.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/TimestampPrefixedUUID.java
fhir-persistence-scout/src/main/java/com/ibm/fhir/persistence/scout/FHIRPersistenceScoutImpl.java
fhir-persistence/src/main/java/com/ibm/fhir/persistence/FHIRPersistence.java
fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/LogicalIdentityProvider.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/MockPersistenceImpl.java
fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
fhir-server/src/test/java/com/ibm/fhir/server/test/FHIRRestHelperTest.java
fhir-server/src/test/java/com/ibm/fhir/server/test/MockPersistenceImpl.java
fhir-server/src/test/java/com/ibm/fhir/server/test/MockTransactionAdapter.java

Issue #1504 - properly process local references in transaction bundles

---

fhir-persistence/src/main/java/com/ibm/fhir/persistence/FHIRPersistence.java
fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
fhir-server/src/test/java/com/ibm/fhir/server/test/FHIRRestHelperTest.java

Issue #1504 - add back in sort for PUT/DELETE requests

---

docs/src/pages/guides/FHIRServerUsersGuide.md
fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java

and add `fhirServer/security/oauth/smart/capabilities` to the docs

issue #1589 - fix FHIRConfiguration smart properties

---

fhir-search/src/test/resources/config/default/fhir-server-config.json
fhir-search/src/test/resources/config/tenant1/fhir-server-config.json
fhir-search/src/test/resources/config/tenant2/fhir-server-config.json
fhir-search/src/test/resources/config/tenant4/fhir-server-config.json
fhir-search/src/test/resources/config/tenant5/fhir-server-config.json
fhir-search/src/test/resources/config/tenant6/fhir-server-config.json
fhir-search/src/test/resources/config/tenant7/extension-search-parameters.json
fhir-search/src/test/resources/config/tenant7/fhir-server-config.json
fhir-server/liberty-config-tenants/config/tenant1/fhir-server-config.json

fix: replace tabs with four spaces

---

build/release/build.sh

fix: add missing igs to the  maven profiles in the release process

---

fhir-model/src/main/java/com/ibm/fhir/model/util/FHIRUtil.java
fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
fhir-server/src/test/java/com/ibm/fhir/server/test/FHIRRestHelperTest.java
fhir-server/src/test/java/com/ibm/fhir/server/test/MockPersistenceImpl.java

Issue #1594 - fix overwriting of validate warnings in bundle processing

---

fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
fhir-server/liberty-config/config/default/fhir-server-config-db2.json
fhir-server/liberty-config/config/default/fhir-server-config-postgresql.json

also added security to the db2 and postgres sample configs

issue #1272 - use new config approach while applying search param filter

---

build/release/build.sh
fhir-validation/pom.xml

ci: wrong profile and dependency name

---

docs/src/pages/guides/FHIRValidationGuide.md

update declared profile support

---

docs/src/styles/index.scss

doc: resolve issues wiht layout

---

fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java

Issue #1630 - added logic to handle slices with type discriminator

---

.github/ISSUE_TEMPLATE/feature_request.md

Update feature request to include acceptance criteria

---

docs/src/pages/performance/performance-450.md

fix: website requires balanced xhtml

---

fhir-bulkimportexport-webapp/src/main/java/META-INF/batch-jobs/FhirBulkImportChunkJob.xml
fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/jbatch/bulkdata/export/system/ChunkReader.java
fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/jbatch/bulkdata/load/ChunkWriter.java
operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/processor/impl/CosExportImpl.java

Bulk Data $import and $export must inject the incomingURL to support Reference processing

---

docs/src/pages/guides/FHIRServerUsersGuide.md
fhir-server/liberty-config/configDropins/defaults/transaction-manager.xml
fhir-server/liberty-config/configDropins/disabled/transaction-manager-long.xml

Would like an easy way to extend the IBM FHIR Server TransactionManager timeout interval #1660

---

fhir-bucket/src/main/java/com/ibm/fhir/bucket/api/Constants.java

@punktilious not sure if you had a plan for these, but I had removed them locally just to keep my head straight.

remove unused COS constants from main constants file

---

fhir-install/Dockerfile

fix: change to use a single RUN and change deprecated command in lieu of a label

---

docs/src/pages/Conformance.md
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/AbstractQueryBuilder.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractReverseChainTest.java
fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
fhir-search/src/main/java/com/ibm/fhir/search/exception/SearchExceptionUtil.java
fhir-search/src/main/java/com/ibm/fhir/search/parameters/QueryParameter.java
fhir-search/src/main/java/com/ibm/fhir/search/uri/UriBuilder.java
fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
fhir-search/src/test/java/com/ibm/fhir/search/test/RevChainParameterParseTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchReverseChainTest.java

Issue #1218 - enable reverse chain (_has) search

---

fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/PopulateParameterNames.java
fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/PopulateResourceTypes.java

fix: allocate-tenant fails when run twice

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
fhir-persistence-jdbc/src/test/java/testng.xml
fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchCompositeTest.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractReverseChainTest.java

Issue #1669 - fix composite search queries

---

fhir-install/Dockerfile
fhir-install/licenses/LICENSE

fix: consistency with licenses #1695

---

docs/src/pages/guides/FHIRServerUsersGuide.md

docs: add docker section

---

fhir-search/src/main/java/com/ibm/fhir/search/compartment/CompartmentUtil.java
fhir-server/src/main/java/com/ibm/fhir/server/util/FHIROperationUtil.java
fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java

Guard against filtered inclusion criteria

---

docs/src/pages/guides/FHIRServerUsersGuide.md
fhir-server/liberty-config/server.xml

Externalize the Credentials in the server.xml #1716

---

docs/src/pages/guides/FHIRServerUsersGuide.md
fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
fhir-server/src/test/java/com/ibm/fhir/server/test/MockRegistryResourceProvider.java
fhir-server/src/test/java/com/ibm/fhir/server/test/ProfileValidationConfigTest.java
fhir-server/src/test/resources/config/profileValidationConfigTest/fhir-server-config.json

Issue #1547 - enable validation of profile assertions

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractReverseChainTest.java
fhir-server-test/pom.xml
fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchChainTest.java
fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchReverseChainTest.java

Issue #1706 - fix chaining/reverse chaining searches with _lastUpdated

---

docs/src/pages/MustGather.md

doc: MustGather.md

---

fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchCompositeTest.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchNumberTest.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchQuantityTest.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchReferenceTest.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchStringTest.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchTokenTest.java
fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchURITest.java

Issue #1569 - fix :missing modifier queries

---

build/release/docker-push.sh
fhir-install/src/main/docker/ibm-fhir-schematool/.gitignore
fhir-install/src/main/docker/ibm-fhir-schematool/DESIGN.md
fhir-install/src/main/docker/ibm-fhir-schematool/DEVELOPMENT.md
fhir-install/src/main/docker/ibm-fhir-schematool/Dockerfile
fhir-install/src/main/docker/ibm-fhir-schematool/README.md
fhir-install/src/main/docker/ibm-fhir-schematool/build.sh
fhir-install/src/main/docker/ibm-fhir-schematool/examples/db2/persistence-debug-custom.json
fhir-install/src/main/docker/ibm-fhir-schematool/examples/db2/persistence-debug-example.json
fhir-install/src/main/docker/ibm-fhir-schematool/examples/db2/persistence-offboard-example.json
fhir-install/src/main/docker/ibm-fhir-schematool/examples/db2/persistence-onboard-example.json
fhir-install/src/main/docker/ibm-fhir-schematool/examples/postgres/persistence-debug-custom.json
fhir-install/src/main/docker/ibm-fhir-schematool/examples/postgres/persistence-debug-example.json
fhir-install/src/main/docker/ibm-fhir-schematool/examples/postgres/persistence-offboard-example.json
fhir-install/src/main/docker/ibm-fhir-schematool/examples/postgres/persistence-onboard-example.json
fhir-install/src/main/docker/ibm-fhir-schematool/run.sh

IBM FHIR Schema Tool - Docker Container and Brief Documentation
Automation to come in separate PR

IBM FHIR Schema Tool - Docker Container and Brief Documentation

---

docs/src/pages/guides/FHIRServerUsersGuide.md
fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
fhir-server/src/test/java/com/ibm/fhir/server/test/ProfileValidationConfigTest.java
fhir-server/src/test/resources/config/profileValidationConfigTest/fhir-server-config.json

Issue #1725 - handle versions with asserted profile validation

---

fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
fhir-search/src/test/java/com/ibm/fhir/search/test/InclusionParameterParseTest.java
fhir-server/src/test/java/com/ibm/fhir/server/test/MockRegistryResourceProvider.java

Issue #1629 - return error if bad resource type on revinclude

---

.github/workflows/windows.yml

e2e windows fails to upload logs #1609

---

fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
fhir-validation/src/test/resources/fhir/validation/test/package/my-observation.json

Issue #1727 - added error handling to ConstraintGenerator.getTypes(...)

---

fhir-term/src/main/java/com/ibm/fhir/term/util/ValueSetSupport.java

Issue #1736 - Added display property to ValueSet expansions.

---

docs/src/pages/guides/FHIRSearchConfiguration.md

otherwise it doesn't show up right

add newline before table

---

fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java
fhir-smart/src/test/resources/logging.properties

To aid in debug when we're not sure why a given request is being
rejected.

Improve AuthzPolicyEnforcement logging

---

build/release/build.sh
fhir-examples/src/main/resources/profiles-hrex-json.txt

and a minor update to the HREX index to include the 2 new resources

issue #1606 - add pdex and hrex to the release

---

docs/src/pages/guides/FHIRSearchConfiguration.md

correct reindex param names and point to fhir-bucket readme for usage info

---

fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/CommonDatabaseAdapter.java

fix: update the word to reflect what is actually happening

---

build/release/docker-push.sh

ci: update docker-push.sh to manage the paths to workspace correctly

---

fhir-persistence-schema/README.md

fix typo in examples

---

fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/version/GetLatestVersionDAO.java
fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/version/VersionHistoryService.java

issue #1793 Derby bootstrap error when updating existing database

---

docs/src/pages/MustGather.md

doc: update must gather to include open shift details

---

docs/src/pages/guides/FHIRSearchConfiguration.md

Issue #1780 - add compartment search/search parameter config section

---

docs/src/pages/MustGather.md

doc: compilation errors are now fixed

---

fhir-audit/src/main/java/com/ibm/fhir/audit/logging/impl/WhcAuditCadfLogService.java
fhir-server/src/main/java/com/ibm/fhir/server/resources/Batch.java
fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java

IBM FHIR Server audit does not log bundles correctly. #1803

---

README.md

doc: update to clarify the experimental use of the ibm-fhir-schematool

---

CODE_OF_CONDUCT.md

add communication method

---

fhir-server/liberty-config/configDropins/defaults/openapi.xml
fhir-server/liberty-config/server.xml

Enable OpenLiberty override the fhiropenapi functionality #1760

---

fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java

fix incorrect variable in minor startup log message

---

fhir-audit/src/main/java/com/ibm/fhir/audit/configuration/ConfigurationTranslator.java
fhir-audit/src/main/java/com/ibm/fhir/audit/configuration/type/KafkaType.java

- Per Code Review with Robin Arnold

Convert Strings to Constants for Kafka Key-Value in Properties objects

---

docs/src/pages/guides/FHIRServerUsersGuide.md
fhir-audit/src/main/java/com/ibm/fhir/audit/cadf/CadfEvent.java
fhir-audit/src/main/java/com/ibm/fhir/audit/cadf/CadfResource.java
fhir-audit/src/test/java/com/ibm/fhir/audit/cadf/test/CadfModelTest.java

- CadfEvent doesn't write out target
- Addresses Written Twice in CadfResource

Code Review for FHIR Audit

---

fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java

Removed auditLogService <extension url="http://ibm.com/fhir/extension/auditLogProperties">

---

fhir-server/liberty-config/config/default/fhir-server-config-audit-config.json
fhir-server/liberty-config/config/default/fhir-server-config-audit-environment.json

Package name consistency issue after Code Review of FHIR-Audit Config

---

fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
fhir-search/src/test/java/com/ibm/fhir/search/parameters/MultiTenantSearchParameterTest.java
fhir-search/src/test/resources/config/default/fhir-server-config.json

issue #1831 - fix search parameter filtering issue

---

fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchLastUpdatedIdTest.java

more specifically, I get the current year (in UTC), and use that.  in places where we already had a list of years, i just prepend the current year to the existing list.

fix for hardcoded year from SearchLastUpdatedIdTest

---

docs/src/pages/guides/FHIRServerUsersGuide.md

add info on accessing the bulk operation job logs
