- fhir-persistence/src/main/java/com/ibm/fhir/persistence/interceptor/FHIRPersistenceEvent.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java
> Issue #1849 - AuthZ interceptor validate/convert search requests

- docs/src/pages/Conformance.md
- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/InteractionValidationConfigTest.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/MockPersistenceImpl.java
- fhir-server/src/test/resources/config/interactionConfigTest1/fhir-server-config.json
- fhir-server/src/test/resources/config/interactionConfigTest2/fhir-server-config.json
> Issue #1615 - Enforce configured interactions in REST layer

- docs/src/pages/Conformance.md
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/InclusionQuerySegmentAggregator.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchIncludeTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchRevIncludeTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
> Issue #1494 - add Bundle.entry.search to search results

- fhir-install/src/main/docker/ibm-fhir-schematool/run.sh
- fhir-persistence-schema/README.md
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
> fix: target and grant schemas #1858

- fhir-search/src/main/java/com/ibm/fhir/search/date/DateTimeHandler.java
- fhir-search/src/main/java/com/ibm/fhir/search/parameters/QueryParameterValue.java
- fhir-search/src/test/java/com/ibm/fhir/search/date/DateTimeHandlerTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/QueryParameterValueTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchAllTest.java
Fixes dates in link urls of search response to represent the actual date specified in the search request.
> Issue #1670 - Fix date in link urls of search response

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/DataDefinitionUtil.java
> surround schema name with single quote to detect whitespace issues

- docs/src/pages/guides/FHIRServerUsersGuide.md
> fix subsection numbering

- fhir-search/src/main/java/com/ibm/fhir/search/uri/UriBuilder.java
- fhir-search/src/test/java/com/ibm/fhir/search/uri/test/UriTest.java
> issue #1907 - strip the query from the originalRequstUri before parsing

- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ImportOperation.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataImportUtil.java
- operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/util/BulkDataImportUtilTest.java
> Convert ImportOperation Parameter Processing to use FHIR Path #951

- docs/src/pages/Conformance.md
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractIncludeRevincludeTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchIncludeTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchRevIncludeTest.java
> Issue #1557 - remove dups, ignore _elements for include resources

- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/CompartmentParseQueryParmsTest.java
- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java
> Issue #1912 - add compartment search parms to front of list

- docs/src/data/nav-items.yaml
> doc: update the nav

- fhir-install/Dockerfile
- fhir-install/src/main/resources/scripts/install.bat
- fhir-install/src/main/resources/scripts/install.sh
- fhir-parent/pom.xml
Please hold off on merging this until we decide whether to cut a 4.5.5
> upgrade liberty, postgresql, db2, and cxf

- fhir-server/liberty-config/server.xml
> expose the traceSpecification and traceFileName via env var

- fhir-notification/src/main/java/com/ibm/fhir/notification/FHIRNotificationService.java
> FHIRNotificationService should emit event for delete #983

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRPatchTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Added Feature to support bundle-patch requests.
> Added Feature to support bundle-patch requests-Issue 1525

- fhir-notification/src/main/java/com/ibm/fhir/notification/FHIRNotificationEvent.java
- fhir-notification/src/main/java/com/ibm/fhir/notification/FHIRNotificationService.java
- fhir-notification/src/main/java/com/ibm/fhir/notification/util/FHIRNotificationUtil.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/interceptor/impl/FHIRPersistenceInterceptorMgr.java
> FHIRNotificationEvent does not support multi-tenancy #1206

- fhir-server/liberty-config/configDropins/disabled/db2-cloud/bulkdata.xml
- fhir-server/liberty-config/configDropins/disabled/db2/bulkdata.xml
- fhir-server/liberty-config/configDropins/disabled/postgres/bulkdata.xml
> doc: change the environment variables

- conformance/fhir-ig-davinci-pdex-formulary/src/test/java/com/ibm/fhir/ig/davinci/pdex/formulary/tool/ResourceProcessor.java
- conformance/fhir-ig-davinci-pdex-plan-net/src/test/java/com/ibm/fhir/ig/davinci/plannet/tool/ResourceProcessor.java
- conformance/fhir-ig-mcode/src/test/java/com/ibm/fhir/ig/mcode/tool/IndexGenerator.java
- conformance/fhir-ig-mcode/src/test/java/com/ibm/fhir/ig/mcode/tool/ResourceProcessor.java
> Move fhir-ig packaging utils out of src/main/java and into a '.tool' package

- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
Issue #1844 - Only log stack trace for server error or fine log level
> Issue #1844 - Only log stack trace for server error or fine log level

- fhir-server-test/src/test/java/com/ibm/fhir/cli/test/FHIRCliTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
Issue #1962 - Update copyright year
> Issue #1962 - Update copyright year

- fhir-install/Dockerfile
- fhir-install/src/main/resources/scripts/install.bat
- fhir-install/src/main/resources/scripts/install.sh
- fhir-parent/pom.xml
> Bulk Data Client Fails with Fault on ReflectionUtil #1966

- fhir-audit/pom.xml
- fhir-audit/src/test/java/com/ibm/fhir/audit/cadf/test/CadfModelTest.java
- fhir-bucket/pom.xml
- fhir-bulkimportexport-webapp/pom.xml
- fhir-config/pom.xml
- fhir-core/pom.xml
- fhir-model/pom.xml
- fhir-notification/pom.xml
- fhir-parent/pom.xml
- fhir-path/pom.xml
- fhir-persistence-jdbc/pom.xml
- fhir-persistence-proxy/pom.xml
- fhir-persistence-proxy/src/main/java/com/ibm/fhir/persistence/proxy/rm/test/TestEmbeddedXADataSource.java
- fhir-persistence-schema/pom.xml
- fhir-persistence/pom.xml
- fhir-provider/pom.xml
- fhir-search/pom.xml
- fhir-server-test/pom.xml
- fhir-server/pom.xml
- fhir-smart/pom.xml
- notification/fhir-notification-websocket/pom.xml
- operation/fhir-operation-apply/pom.xml
- operation/fhir-operation-bulkdata/pom.xml
- operation/fhir-operation-test/pom.xml
> Upgrade Pom.xml to latest versions of Dependencies #1959

- fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/provider/DefaultTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/spi/FHIRTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/util/ValueSetSupport.java
> Issue #1530 - fhir-term refactoring

- fhir-provider/pom.xml
- fhir-provider/src/main/java/com/ibm/fhir/provider/util/FHIRUrlParser.java
- fhir-server/pom.xml
- operation/fhir-operation-bulkdata/pom.xml
Issue #1179 - Remove/update CXF dependencies
> Issue #1179 - Change CXF dependency to provided

- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/SubsumesOperation.java
> Issue #1756 - update subsumes operation

- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractCompartmentTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractIncludeRevincludeTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractReverseChainTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/ReferenceUtil.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/ChainParameterParseTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/RevChainParameterParseTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchReferenceTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
> Issue #1553 - check multiple resource types on logical ID ref search

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/AbstractQueryBuilder.java
- fhir-search/src/main/java/com/ibm/fhir/search/parameters/QueryParameterValue.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/ReferenceUtil.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
> Issue #1683 - query builder changes for composite search

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchCompositeTest.java
- fhir-persistence/src/test/resources/config/composite/extension-search-parameters.json
> Issue #1683 - wrap log.fine stmts, add testcases

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/ReorgTable.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/CharColumn.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/Table.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FetchResourceChangesDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceTokenValueRec.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/BackfillResourceChangeLogDb2.java
> issue 1955 use resource subset for all operations in schema tool

- docs/gatsby-config.js
> fix the edit docs link

- .gitattributes
> Windows docker build of fhir server fails non-zero code: 127 #2007

- build/derby-bootstrap.sh
for preparing a non-docker local fhir-server-test in dev (e.g. for our local servers in eclipse)
> share derby-bootstrap script for bootstrapping derby dbs

- fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/FHIRPersistenceUtil.java
> issue #1955 - return http 400 error codes for invalid requests

- build/docker/copy-server-config.sh
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ImportOperationTest.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/FilePreflight.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/HttpsPreflight.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/S3Preflight.java
- Preflight Check for the Storage Type had an invalid expression
- Add S3 Test for Import
- Update copy-server-config adds s3 bucket
> Add Import CI

- fhir-model/src/main/java/com/ibm/fhir/model/type/Narrative.java
- fhir-model/src/test/java/com/ibm/fhir/model/test/EmptyResourceTest.java
- fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java
Issue #646 - Define a Narrative.EMPTY constant
> Issue #646 - Define a Narrative.EMPTY constant

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ChunkWriter.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/V2ConfigurationImpl.java
> Fix for Double Negation Problem

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/S3Provider.java
> Fix issue with Multipart

- fhir-server/liberty-config/configDropins/disabled/db2-cloud/bulkdata.xml
- fhir-server/liberty-config/configDropins/disabled/db2/bulkdata.xml
- fhir-server/liberty-config/configDropins/disabled/postgres/bulkdata.xml
Issue #2035 - Remove fhirSharedLib from bulkdata webapp
> Issue #2035 - Remove fhirSharedLib from bulkdata webapp

- README.md
- docs/src/pages/guides/FHIRBulkOperations.md
- docs/src/pages/guides/FHIRServerUsersGuide.md
> Update to the bulkdata documentation

- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ImportOperation.java
> Improve Error Handling with POST to $import

- docs/src/pages/guides/FHIRServerUsersGuide.md
> fix the X-FHIR-BULKDATA-PROVIDER-OUTCOME header name to match the code

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/listener/Reporter.java
> Fix: Reporter didn't aggregate the total

- fhir-audit/src/main/java/com/ibm/fhir/audit/beans/Context.java
- fhir-audit/src/main/java/com/ibm/fhir/audit/beans/FHIRContext.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/audit/BulkAuditLogger.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/export/group/resource/GroupHandler.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/export/patient/resource/PatientResourceHandler.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/fast/ResourcePayloadReader.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/patient/ChunkReader.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/system/ChunkReader.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ChunkWriter.java
associated with the total read in the log entry #2072
> Audit log entry for bulk data export should have a resource type

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ExportOperationTest.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ExportOperation.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java
Fix for Domain Resource and Resource
> Issue 2063:  avoid exporting abstract resource types

- docs/src/pages/Conformance.md
- fhir-server-webapp/pom.xml
> temporarily exclude the fhir-operation-everything jar from the server webapp

- docs/src/pages/Conformance.md
- fhir-core/src/main/java/com/ibm/fhir/core/FHIRConstants.java
- fhir-core/src/main/java/com/ibm/fhir/core/context/FHIRPagingContext.java
- fhir-core/src/main/java/com/ibm/fhir/core/context/impl/FHIRPagingContextImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPagingTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
- fhir-search/src/main/java/com/ibm/fhir/search/TotalValueSet.java
- fhir-search/src/main/java/com/ibm/fhir/search/context/FHIRSearchContext.java
- fhir-search/src/main/java/com/ibm/fhir/search/context/impl/FHIRSearchContextImpl.java
- fhir-search/src/main/java/com/ibm/fhir/search/uri/UriBuilder.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/InclusionParameterParseTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/TotalParameterParseTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/uri/test/UriTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/registry/ServerRegistryResourceProvider.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Issue #1353 - Add support for _total search parameter
> Issue #1353 - Add support for _total search parameter

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/ReindexResourceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/ResourceIndexRecord.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceDAOImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgres/PostgresReindexResourceDAO.java
> issue-2055 do not try to reindex deleted resources

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractPLSearchTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchCompartmentTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchIdAndLastUpdatedTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchURITest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractCompartmentTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
- fhir-persistence/src/test/resources/config/compartment/extension-search-parameters.json
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/CompartmentParseQueryParmsTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
In prep for exploring some ideas around supporting logical 'or' on the
compartment search param.
> Beef up compartment search tests

- docs/src/pages/guides/FHIRTerminologyGuide.md
> ConceptMap, ValueSet, and ConceptMap

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/FileProvider.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ExportOperationTest.java
> Improve the Export Test to verify the resources that are exported and QA issue with resetting the bufferstream

- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchCompartmentTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/CompartmentParseQueryParmsTest.java
- fhir-search/src/test/resources/config/tenant2/fhir-server-config.json
- fhir-server/liberty-config/config/default/fhir-server-config.json
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java
and add it to our default fhir-server-config.json
> issue #2111 - default useStoredCompartmentParam to true

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/ReindexResourceDAO.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/ReindexOperationTest.java
- fhir-server-test/src/test/java/testng.xml
> Reindex fix for db2 mutlitenancy #2108

- fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
- fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java
Issue #1203 - Added openapi/swagger minItems property to arrays
Issue #1277 - Update base64Binary pattern in openapi/swagger 
> Issue #1203 - Updated openapi/swagger generator

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/DerbyResourceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgres/PostgresResourceNoProcDAO.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceTableGroup.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaVersion.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/GetXXXLogicalResourceNeedsMigration.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/InitializeLogicalResourceDenorms.java
- fhir-persistence-schema/src/main/resources/db2/add_any_resource.sql
- fhir-persistence-schema/src/main/resources/postgres/add_any_resource.sql
- fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/derby/DerbyFhirDatabaseTest.java
> issue-2109 schema V0012 add version_id to XXX_LOGICAL_RESOURCES

- docs/src/pages/Conformance.md
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/ParameterExtractionTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchReferenceTest.java
Issue #773 - Add support for ':identifier' modifier
> Issue #773 - Add support for ':identifier' modifier

- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
> Output missing when an bad incoming url is sent

- docs/src/pages/guides/FHIRServerUsersGuide.md
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/StatusOperation.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/AbstractSystemConfigurationImpl.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/transformer/JobIdEncodingTransformer.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java
- operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/model/transformer/JobIdEncodingTransformerTest.java
The job number is not decoded before used. #2128
> Call into $bulkdata-status passing in the encoded job number

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/everything/EverythingOperationTest.java
- operation/fhir-operation-everything/src/main/java/com/ibm/fhir/operation/everything/EverythingOperation.java
> Everything Operation doesn't respond correctly to deleted resources

- fhir-model/src/main/java/com/ibm/fhir/model/ucum/UCUMLexer.java
- fhir-model/src/main/java/com/ibm/fhir/model/ucum/UCUMParser.java
> Issue #2079 - regenerated parser/lexer

- docs/src/pages/guides/FHIRValidationGuide.md
- fhir-path/pom.xml
- fhir-path/src/main/java/com/ibm/fhir/path/tools/Main.java
- fhir-path/src/test/java/com/ibm/fhir/path/tools/MainTest.java
> FHIRPath CLI #1283

- fhir-term/src/main/java/com/ibm/fhir/term/util/ValueSetSupport.java
> Issue #1980 - changed over validateCode to use normalize

- fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
- fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java
Issue #1845 - Add POST _search to generated swagger/openapi
> Issue #1845 - Add POST _search to generated swagger/openapi

- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/registry/SnomedRegistryResourceProvider.java
- fhir-term-graph/src/test/java/com/ibm/fhir/term/graph/test/SnomedRegistryResourceProviderTest.java
> Issue #1980 - fixed subsumed by implicit value set URL syntax

- fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
> Issue #1980 - clean up FHIRTermService subsumes logic

- docs/src/pages/Conformance.md
- fhir-search/src/main/java/com/ibm/fhir/search/parameters/InclusionParameter.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/InclusionParameterParseTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchIncludeTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchRevIncludeTest.java
Issue #2070 - Support _total with _include and _revinclude
> Issue #2070 - Support _total with _include and _revinclude

- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathAbstractSystemValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathAbstractTemporalValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathBooleanValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathDateTimeValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathDateValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathDecimalValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathIntegerValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathNode.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathQuantityValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathStringValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathTimeValue.java
> Issue #2153 - introduce system value base class, update javadoc

- fhir-model/src/main/java/com/ibm/fhir/model/type/Base64Binary.java
- fhir-model/src/test/java/com/ibm/fhir/model/test/Base64BinaryTest.java
- fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java
> Add javadoc and convenience methods for Base64Binary #1186

- docs/src/pages/Conformance.md
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregatorFactory.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/InclusionParameterParseTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchIncludeTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchRevIncludeTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/performance/SearchPerformanceTest.java
Issue #1915 - Support _sort with _include and _revinclude
> Issue #1915 - Support _sort with _include and _revinclude

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/fast/ResourcePayloadReader.java
- fhir-server/liberty-config/config/default/fhir-server-config.json
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/ConfigurationAdapter.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/AbstractSystemConfigurationImpl.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/url/DownloadUrl.java
> configure the maxChunkReadTime for Fast Export and configurable timeout for presigned URL #2150

- fhir-model/src/main/java/com/ibm/fhir/model/type/Base64Binary.java
- fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java
> issue #1186 - minor javadoc update

- fhir-bulkdata-webapp/pom.xml
- fhir-parent/pom.xml
> Avoid the useless warning for jaxb-core,jaxb-api not found

- docs/src/pages/Conformance.md
- fhir-examples/src/main/resources/json/ibm/basic/BasicToken.json
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/CodeSystemDAOImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterDAOImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterNameDAOImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterVisitorBatchDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dto/QuantityParmVal.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dto/TokenParmVal.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/ParameterExtractionTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchTokenTest.java
- fhir-persistence/src/test/resources/config/token/extension-search-parameters.json
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
- fhir-term/src/main/java/com/ibm/fhir/term/util/ValueSetSupport.java
> Issue #1734 - support :in and :not-in modifiers for Token search

- .github/ISSUE_TEMPLATE/bug_report.md
> add environment section to bug template

- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/AbstractTermOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/LookupOperation.java
> Issue #1756 - build exceptions with issues

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Search.java
Issue #2187 - Support compartment search via POST
> Issue #2187 - Support compartment search via POST

- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/loader/impl/CodeSystemTermGraphLoader.java
- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/provider/GraphTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/util/CodeSystemSupport.java
- fhir-term/src/test/java/com/ibm/fhir/term/service/test/CodeSystemSupportTest.java
> Issue #1733 - changed behavior when hierarchy meaning is undefined

- docs/src/pages/Conformance.md
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterVisitorBatchDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/ParameterExtractionTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
- fhir-server-test/src/test/resources/testdata/Observation1.json
- fhir-server/liberty-config-tenants/config/tenant1/fhir-server-config.json
Issue #1732 - Support token modifier ':text'
> Issue #1732 - Support token modifier ':text'

- fhir-server-test/pom.xml
> fhir-server-test should have had all dependencies scoped to test

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/export/writer/SparkParquetWriter.java
- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/provider/GraphTermServiceProvider.java
- fhir-term-graph/src/test/java/com/ibm/fhir/term/graph/test/SnomedRegistryResourceProviderTest.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/provider/RegistryTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/spi/FHIRTermServiceProvider.java
- fhir-term/src/test/java/com/ibm/fhir/term/service/provider/test/FHIRTermServiceProviderTest.java
- fhir-term/src/test/java/com/ibm/fhir/term/service/test/FHIRTermServiceTest.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/ClosureOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/CodeSystemValidateCodeOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/ExpandOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/SubsumesOperation.java
> Issue #2162 - introduce a new closure method signature

- fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
- fhir-term/src/main/java/com/ibm/fhir/term/spi/FHIRTermServiceProvider.java
- fhir-term/src/test/java/com/ibm/fhir/term/service/provider/test/FHIRTermServiceProviderTest.java
> Issue #2162 - introduce hasConcepts method

- docs/src/pages/Conformance.md
- fhir-examples/src/main/resources/json/ibm/basic/BasicToken.json
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchTokenTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
- fhir-server-test/src/test/resources/testdata/Condition.json
> Issue #1733 - implement TOKEN :above and :below modifiers

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgres/PostgresAdapter.java
> Fix for Bad Drop

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/ReindexResourceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/MockPersistenceImpl.java
- fhir-server/src/test/java/com/ibm/fhir/server/util/FHIRRestHelperTest.java
Issue #2140 - Handle reading null from xx_RESOURCES.DATA
> Issue #2140 - Handle reading null from xx_RESOURCES.DATA

- fhir-server/pom.xml
- fhir-term-graph/pom.xml
Abbreviated dep list
- [INFO] ----------------------< com.ibm.fhir:fhir-server >----------------------
- [INFO] Building fhir-server 4.7.0-SNAPSHOT                              [29/49]
- [INFO] --------------------------------[ jar ]---------------------------------
- [INFO] +- com.ibm.fhir:fhir-term-graph:jar:4.7.0-SNAPSHOT:compile
- [INFO] |  +- com.ibm.fhir:fhir-term:jar:4.7.0-SNAPSHOT:compile
- [INFO] |  +- org.janusgraph:janusgraph-core:jar:0.5.3:compile
- [INFO] |  |  +- org.janusgraph:janusgraph-driver:jar:0.5.3:compile
- X EXCLUDE |  |  |  +- org.apache.tinkerpop:gremlin-groovy:jar:3.4.6:compile
- EXCLUDE |  |  |  |  +- org.apache.ivy:ivy:jar:2.3.0:compile
- EXCLUDE |  |  |  |  +- org.codehaus.groovy:groovy-groovysh:jar:indy:2.5.7:compile
- EXCLUDE |  |  |  |  |  +- …
> Review the Dependencies for FHIR Term

- performance/fhir-meter/searchTest.jmx
Detail: Update to 4 tests due to IBM fhir-server changes.  Added 5 new search tests.
Signed-off-by: Dag Roppe <roppe@us.ibm.com>
> Issue #2232 - Update JMeter test file

- fhir-model/src/main/java/com/ibm/fhir/model/util/FHIRUtil.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/ClosureOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/CodeSystemValidateCodeOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/ExpandOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/LookupOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/SubsumesOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/TranslateOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/ValueSetValidateCodeOperation.java
> Issue #2162 - updates to how we handle UnsupportOperationException

- performance/fhir-meter/README.md
> formatting changes

- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/provider/GraphTermServiceProvider.java
- fhir-term-remote/src/main/java/com/ibm/fhir/term/remote/provider/RemoteTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/provider/AbstractTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/provider/RegistryTermServiceProvider.java
1. Created abstract base class for `FHIRTermServiceProvider` implementations
2. Added argument checking to `RegistryTermServiceProvider` and `RemoteTermServiceProvider`
3. Added support for code system version in requests made by JAX-RS client to remote service
4. Added try/finally block to ensure JAX-RS response object is closed
> Issue #2198 - improve argument, version, and error handling

- fhir-search/src/main/java/com/ibm/fhir/search/context/FHIRSearchContext.java
- fhir-search/src/main/java/com/ibm/fhir/search/context/impl/FHIRSearchContextImpl.java
- fhir-search/src/main/java/com/ibm/fhir/search/sort/Sort.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/location/NearLocationHandlerBoundingRadiusTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/sort/test/SortParameterParseTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/sort/test/SortTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/ElementsParameterParseTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/performance/SearchPerformanceTest.java
- fhir-server/liberty-config-tenants/config/tenant1/fhir-server-config.json
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Issue #1952 - OperationOutcome when search parameters are ignored
> Issue #1952 - OperationOutcome when search parameters are ignored

- README.md
- fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
> Issue #2198 - fixed typo, updated README

- docs/src/data/nav-items.yaml
- docs/src/pages/blog/everything.md
> Updates for Everything Blog

- fhir-server/src/main/java/com/ibm/fhir/server/listener/FHIRServletContextListener.java
> null check for missing graphTermServiceProviders config

- docs/src/pages/guides/FHIRTerminologyGuide.md
> Issue #2198 - FHIRTerminologyGuide.md updates

- fhir-persistence-scout/pom.xml
Signed-off-by: Dag Roppe <roppe@us.ibm.com>
> Fix for bad Pom

- .github/workflows/javadocs.yml
> Update Javadocs #2279

- fhir-model/src/main/java/com/ibm/fhir/model/type/Base64Binary.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Boolean.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Canonical.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Code.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Date.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/DateTime.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Decimal.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Id.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Instant.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Integer.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Markdown.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Oid.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/PositiveInt.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/String.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Time.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/UnsignedInt.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Uri.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Url.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Uuid.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Xhtml.java
- fhir-model/src/test/java/com/ibm/fhir/model/test/DateTimeTest.java
- fhir-model/src/test/java/com/ibm/fhir/model/util/test/ValidationSupportTest.java
- fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java
> issue #1814 - add javadoc and requireNonNull in factory methods

- docs/src/pages/Conformance.md
- fhir-examples/src/main/resources/json/ibm/basic/BasicReference.json
- fhir-examples/src/main/resources/json/ibm/basic/BasicToken.json
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchReferenceTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchTokenTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
- fhir-persistence/src/test/resources/config/token/extension-search-parameters.json
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchReferenceTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
- fhir-server-test/src/test/resources/testdata/Condition.json
> Issue #1551 - perform token search based on codeSystem case-sensitivity

- fhir-server/liberty-config/configDropins/defaults/openapi.xml
- fhir-server/liberty-config/configDropins/disabled/jwtRP.xml
- fhir-server/liberty-config/configDropins/disabled/keycloakRP.xml
- fhir-server/liberty-config/server.xml
Note: merging this will mean that everyone will need to upgrade their version of Liberty to one that supports these newer features.
> upgrade liberty features

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRValidateOperationTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/operation/spi/AbstractOperation.java
- fhir-server/src/main/java/com/ibm/fhir/server/operation/spi/FHIROperationContext.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Operation.java
- fhir-swagger-generator/pom.xml
- Add check for the URI Path
- Add Integration Test
> Null pointer on $validate of a Bundle #2307

- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
Issue #1885 - Include search parameter URLs in conflict warning message
> Issue #1885 - Include search parameter URLs in conflict warning message

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/query/node/IntegerBindMarkerNode.java
based on a single unresolved review comment on #2309 
> super minor comment update

- fhir-path/src/main/java/com/ibm/fhir/path/function/FHIRPathAbstractTermFunction.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/FHIRPathUtil.java
- fhir-term-remote/src/main/java/com/ibm/fhir/term/remote/provider/RemoteTermServiceProvider.java
> Issue #2292 - additional updates

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/api/IDatabaseAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/CommonDatabaseAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/PhysicalDataModel.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/DropForeignKey.java
> issue-1631 PostgreSQL drop schema fails with shared memory error

- fhir-term-remote/src/main/java/com/ibm/fhir/term/remote/provider/RemoteTermServiceProvider.java
> Issue #2292 - introduce String constants

- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
> Issue #2344 - update Capabilities to use fhir-cache

- docs/src/pages/guides/FHIRPerformanceGuide.md
> add _total documentation and move the subsetting info to 6.4

- fhir-registry/src/main/java/com/ibm/fhir/registry/resource/FHIRRegistryResource.java
- fhir-registry/src/main/java/com/ibm/fhir/registry/util/FHIRRegistryUtil.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
- fhir-term/src/main/java/com/ibm/fhir/term/util/ValueSetSupport.java
> Issue #2342 - set experimental to true

- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/patch/Main.java
Issue #1899 - Trim whitespace from values in schema tool property files
> Issue #1899 - Trim whitespace from values in schema tool property files

- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
> Update to control the output of exceptions in ListTenants

- fhir-registry/src/main/java/com/ibm/fhir/registry/FHIRRegistry.java
- fhir-registry/src/main/java/com/ibm/fhir/registry/resource/FHIRRegistryResource.java
- fhir-registry/src/main/java/com/ibm/fhir/registry/spi/AbstractRegistryResourceProvider.java
- fhir-registry/src/main/java/com/ibm/fhir/registry/util/PackageRegistryResourceProvider.java
- fhir-registry/src/test/java/com/ibm/fhir/registry/test/FHIRRegistryDefaultVersionTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/registry/ServerRegistryResourceProvider.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/provider/GraphTermServiceProvider.java
- fhir-term-remote/src/main/java/com/ibm/fhir/term/remote/provider/RemoteTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/provider/RegistryTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/spi/AbstractTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/util/ValueSetSupport.java
> Issue #2356 - add support for default version of registry resources

- docs/src/pages/guides/FHIRServerUsersGuide.md
Issue #1546 - Fix OAuth naming and link
> Issue #1546 - Fix OAuth naming and link

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/terminology/LookupOperationTest.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/LookupOperation.java
> Issue #2362 - check for CodeSystem availability

- fhir-model/src/main/java/com/ibm/fhir/model/util/ValidationSupport.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/ConditionalReferenceTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/RemoteTermServiceProviderTest.java
- fhir-server-test/src/test/resources/testdata/conditional-reference-bundle.json
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
> Issue #1329 - conditional reference support for transaction bundles

- fhir-parent/pom.xml
> Update per Sonatype Lift CVE Report

- .github/workflows/javadocs.yml
> GitHub Workflow - Javadocs version wasn't set

- build/docker/copy-server-config.sh
- build/pre-integration-test-docker.sh
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/listener/ExitStatus.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/load/partition/transformer/impl/S3Transformer.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ImportOperationTest.java
- We pruned zero sized files, where we should keep them to align with
the output needed
- Updated the corresponding automation
> Error on bulk data status call where import did not import anything #2322

- docs/src/pages/guides/FHIRServerUsersGuide.md
> Update Docs to deprecate the exportPublic  feature

- fhir-server-test/pom.xml
- fhir-server-test/src/main/java/com/ibm/fhir/server/test/persistence/TaggingInterceptor.java
- fhir-server-test/src/main/resources/META-INF/services/com.ibm.fhir.persistence.interceptor.FHIRPersistenceInterceptor
> add a sample interceptor for manually testing issue 2369

- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/AbstractSystemConfigurationImpl.java
- operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/ConfigurationTest.java
- operation/fhir-operation-bulkdata/src/test/resources/config/provider/fhir-server-config.json
> Add Tests for Configuration

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FetchResourcePayloadsDAO.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
> FetchResourcePayloadsDAO hits an error condition under debug without _since parameter #2391

- fhir-cache/src/main/java/com/ibm/fhir/cache/CacheKey.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/ResolveFunction.java
- fhir-server/src/main/java/com/ibm/fhir/server/registry/ServerRegistryResourceProvider.java
- fhir-server/src/main/java/com/ibm/fhir/server/resolve/ServerResolveFunction.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/ServerResolveFunctionTest.java
- fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
> Issue #2296 - miscellaneous updates

- demo/docker-compose.yml
- demo/fhir/config/default/fhir-server-config.json
- demo/fhir/openapi.json
> add Consent and MedicationStatement to the demo env

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FetchResourcePayloadsDAO.java
> Update Fetch to protect the count query

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyTranslator.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/DerbyResourceDAO.java
> issue 2405 fix version concurrency issue for Derby

- build/release/bin/00_prep/0_install_packages.sh
- build/release/bin/10_build/2_version.sh
- build/release/bin/30_release/0_sonatype.sh
> Update to limit releases of fhir-examples

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/listener/StepChunkListener.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ImportJobListener.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ImportPartitionMapper.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/exception/FHIRLoadException.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/load/partition/transformer/impl/S3Transformer.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ImportOperationTest.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/OperationConstants.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
#2322
- mutate the exit status during Mapping failure
- add test for $import of missing file
> Error on bulk data status call where import did not import anything.

- build/release/bin/00_prep/0_install_packages.sh
- build/release/bin/10_build/2_version.sh
- build/release/bin/30_release/0_sonatype.sh
- fhir-parent/pom.xml
> lock in to fhir-examples 4.8.2

- README.md
- docs/src/pages/guides/FHIRServerUsersGuide.md
> Update the Users Guide to correct issue with auth and update README.md with the Erase operation

- fhir-term-remote/src/main/java/com/ibm/fhir/term/remote/provider/RemoteTermServiceProvider.java
> Issue #2431 - RemoteTermServiceProvider.Configuration.from fixup

- docs/src/pages/guides/FHIRPerformanceGuide.md
> Doc update #2364

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-audit/src/main/java/com/ibm/fhir/audit/beans/Batch.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java
> Set more specific batch bundle action in audit event when possible #1817

- fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
- fhir-path/src/test/java/com/ibm/fhir/path/test/FHIRPathAsTest.java
> Issue #2455 - update "as" operation to match "as" function

- fhir-install/Dockerfile
- fhir-install/src/main/resources/scripts/install.bat
- fhir-install/src/main/resources/scripts/install.sh
- fhir-parent/pom.xml
> issue #2461 - upgrade to liberty 21.0.0.5

- fhir-persistence-schema/src/main/resources/postgres/add_any_resource.sql
- fhir-persistence-schema/src/main/resources/postgres/add_code_system.sql
- fhir-persistence-schema/src/main/resources/postgres/add_parameter_name.sql
- fhir-persistence-schema/src/main/resources/postgres/add_resource_type.sql
- fhir-persistence-schema/src/main/resources/postgres/erase_resource.sql
> Move the Trace to SQL Body

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BasicServerTest.java
For both the CapabilityStatement and the TerminologyStatement.
> issue #2436 - validate the metadata responses in e2e tests

- docs/src/pages/guides/FHIRServerUsersGuide.md
> issue #2143 - documentation for the registry and how its used

- build/release/bin/00_prep/0_install_packages.sh
> sudo build and release

- build/release/bin/00_prep/0_install_packages.sh
> use proper ubuntu package for the xpath util

- build/release/bin/30_release/1_dockerhub.sh
using the same approach that we use in our integration tests
> attempt to free disk space before our docker build

- docs/src/pages/guides/BringYourOwnPersistence.md
- docs/src/pages/guides/DB2OnCloudSetup.md
- docs/src/pages/guides/FHIRServerUsersGuide.md
> BYOP and DB2OnCloudSetup has out of date instructions for datasource configuration #2303

- fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
> Issue #2491 - replace Java Streams based logic with conventional loop

- CONTRIBUTING.md
1. indicate that we use github reviews, not just LGTM comments
2. remove the reference to a CHANGELOG...we don't actually maintain one (not we just put that info in the release notes)
> minor updates to CONTRIBUTING.md

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/fast/ResourcePayloadReader.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/AzureProvider.java
FYI - I found these will scripting a demo.
Fast Export with AzureProvider misses resources since it doesn't
complete #2520
> Fast Export using AzureProvider doesn't split by newline #2517

- docs/src/pages/guides/FHIRPerformanceGuide.md
> minor link fix

- conformance/fhir-ig-spl/src/test/java/com/ibm/fhir/ig/us/spl/EstablishmentOrganizationTest.java
- conformance/fhir-ig-spl/src/test/java/com/ibm/fhir/ig/us/spl/SliceSpecificConstraintTest.java
- conformance/fhir-ig-spl/src/test/resources/json/StructureDefinition-IdentifiedOrganization.json
- conformance/fhir-ig-spl/src/test/resources/xml/Organization-ExampleEstablishment.xml
- conformance/fhir-ig-spl/src/test/resources/xml/StructureDefinition-EstablishmentOrganization.xml
- conformance/fhir-ig-spl/src/test/resources/xml/StructureDefinition-SPLContactPoint.xml
- fhir-path/src/test/java/com/ibm/fhir/path/test/MatchesFunctionTest.java
- fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
- fhir-profile/src/main/java/com/ibm/fhir/profile/ProfileSupport.java
> Issue #2501, #2530 - add support for slice specific constraints

- fhir-install/pom.xml
> Remove reference to the removed fhir-cli module

- fhir-term-remote/src/main/java/com/ibm/fhir/term/remote/provider/RemoteTermServiceProvider.java
> Issue #2532 - avoid NPE when expansion is empty

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/ReindexOperationTest.java
- operation/fhir-operation-reindex/src/main/java/com/ibm/fhir/operation/reindex/ReindexOperation.java
Issue #2503 - Check resource type on $reindex operation
> Issue #2503 - Check resource type on $reindex operation

- fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
> Issue #2541 - update generateProfileConstraint

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/CommonDatabaseAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/BaseObject.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/FunctionDef.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgres/PostgresAdapter.java
> fhir-persistance-schema-cli update-schema not updating functions. #2564

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchQueryRenderer.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/NewQueryBuilder.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/NewDateParmBehaviorUtil.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractPLSearchTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
> Issue #1624 and #1653 - date range search improvements

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchQueryRenderer.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractSortTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SortingTest.java
> Issue #2560 - fix sort by _id

- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/GetLogicalResourceNeedsV0014Migration.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/MigrateV0014LogicalResourceIsDeletedLastUpdated.java
> Do V0014 migration in smaller batches

- demo/fhir/config/default/fhir-server-config.json
> fixup search parameter filtering for demo env

- fhir-install/src/main/docker/ibm-fhir-schematool/Dockerfile
`set +x` doesn't do what the comment says and I think its not needed
> minor cleanup

- demo/fhir/config/default/fhir-server-config.json
> more search param filtering updates

- fhir-bucket/README.md
- fhir-bucket/src/main/java/com/ibm/fhir/bucket/app/Main.java
- fhir-bucket/src/main/java/com/ibm/fhir/bucket/reindex/ClientDrivenReindexOperation.java
Issue #2574 - Add reindex-start-with-index-id parameter
> Issue #2574 - Add reindex-start-with-index-id parameter

- conformance/fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/C4BBPatientConstraintGeneratorTest.java
- conformance/fhir-ig-spl/src/test/java/com/ibm/fhir/ig/us/spl/ExamplesValidationTest.java
- fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/DiagnosticsEvaluationListener.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/EvaluationResultTree.java
- fhir-path/src/test/java/com/ibm/fhir/path/test/EvaluationResultTreeTest.java
- fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
- fhir-profile/src/main/java/com/ibm/fhir/profile/ProfileBuilder.java
- fhir-profile/src/test/java/com/ibm/fhir/profile/test/ConstraintGeneratorTest.java
- fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/BloodPressureObservationTest.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/ConditionProfileTest.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/ExtensionTest.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/FamilyMemberHistoryTest.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/MaxValueSetTest.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/ReferenceExtensionTest.java
> Issue #2541 - ConstraintGenerator updates

- fhir-notification/src/main/java/com/ibm/fhir/notification/util/FHIRNotificationUtil.java
- fhir-notification/src/test/java/com/ibm/fhir/notification/util/FHIRNotificationUtilTest.java
> Update ordering in the subset notification

- fhir-model/src/main/java/com/ibm/fhir/model/annotation/Constraint.java
> Issue #2583 - update copyright header

- fhir-bucket/src/main/java/com/ibm/fhir/bucket/reindex/ClientDrivenReindexOperation.java
- fhir-bucket/src/main/java/com/ibm/fhir/bucket/reindex/ServerDrivenReindexOperation.java
> Issue #2574 - updates per PR comments

- fhir-bucket/src/main/java/com/ibm/fhir/bucket/client/FHIRBucketClient.java
- fhir-bucket/src/main/java/com/ibm/fhir/bucket/reindex/ClientDrivenReindexOperation.java
- fhir-bucket/src/main/java/com/ibm/fhir/bucket/reindex/ServerDrivenReindexOperation.java
Issue #2574 - Improve ability to resume from failed reindex
> Issue #2574 - Improve ability to resume from failed reindex

- fhir-model/src/main/java/com/ibm/fhir/model/util/ModelSupport.java
- fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
> Issue #2582, #2583 - additional updates

- fhir-install/Dockerfile
- fhir-install/src/main/resources/scripts/install.bat
- fhir-install/src/main/resources/scripts/install.sh
- fhir-parent/pom.xml
> Upgrade to liberty 21.0.0.6

- fhir-smart/pom.xml
> defer to fhir-parent for the version of the fhir-examples dependency

- docs/src/pages/guides/FHIRPerformanceGuide.md
> Update term to postgresql

- fhir-model/src/main/java/com/ibm/fhir/model/annotation/Constraint.java
- fhir-model/src/main/java/com/ibm/fhir/model/util/ModelSupport.java
- fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
- fhir-profile/src/main/java/com/ibm/fhir/profile/ProfileSupport.java
- fhir-registry/src/test/java/com/ibm/fhir/registry/core/test/VitalSignsProfileTest.java
- fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
> Issue #2583, Issue #2600 - clean up Constraint factory code

- fhir-model/src/main/java/com/ibm/fhir/model/annotation/Constraint.java
- fhir-model/src/main/java/com/ibm/fhir/model/constraint/factory/ConstraintFactory.java
- fhir-model/src/main/java/com/ibm/fhir/model/util/ModelSupport.java
- fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
- fhir-profile/src/main/java/com/ibm/fhir/profile/ProfileSupport.java
- fhir-registry/src/test/java/com/ibm/fhir/registry/core/test/VitalSignsProfileTest.java
- fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
> Issue #2583, #2600 - move Factory class out of Constraint annotation

- fhir-model/src/main/java/com/ibm/fhir/model/constraint/factory/ConstraintFactory.java
> Issue #2583 - update constraint factory toString method

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/cache/IdNameCache.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/cache/NameIdCache.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/IIdNameCache.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/INameIdCache.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/JDBCIdentityCache.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/JDBCIdentityCacheImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/ChainedSearchParam.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/IdSearchParam.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/LastUpdatedSearchParam.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchQueryRenderer.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchQueryVisitor.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/NewQueryBuilder.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/erase/EraseTestMain.java
> Issue #2629 - fix performance issue with whole-system _id search

- fhir-model/src/main/java/com/ibm/fhir/model/constraint/spi/ConstraintProvider.java
- fhir-model/src/main/java/com/ibm/fhir/model/constraint/spi/ConstraintValidator.java
> Issue #2583 - comments / whitespace only

- fhir-model/src/test/java/com/ibm/fhir/model/spec/test/R4ExamplesDriver.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/connection/FHIRDbTenantDatasourceConnectionStrategy.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/db2/Db2ResourceReferenceDAO.java
- fhir-server-test/pom.xml
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BasicServerTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/PlanDefinitionApplyOperationTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/ReadTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchLastUpdatedIdTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchNearTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchRevIncludeTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SortingTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/VReadTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ExportOperationTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ImportOperationAzureTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ImportOperationTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/db2/LargeResourceTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/examples/R4ExampleServerTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/EraseOperationTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/ProfilesTestBase.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreAllergyIntoleranceTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreCarePlanTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreCareTeamTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreConditionTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreDiagnosticReportLabTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreDiagnosticReportNoteTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreDocumentReferenceTest.java
- Cuts down on needless logging
- Improves the performance of multi resource loads and deletes.
> Update CI tests to improve overall performance

- fhir-cache/src/main/java/com/ibm/fhir/cache/CacheKey.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/DiagnosticsEvaluationListener.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/EvaluationResultTree.java
- fhir-registry/src/main/java/com/ibm/fhir/registry/FHIRRegistry.java
> Miscellaneous updates

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgres/PostgresVacuumSettingDAO.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceTableGroup.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaGenerator.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaVersion.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchRevIncludeTest.java
> Update for Postgres vacuum settings

- fhir-cache/src/main/java/com/ibm/fhir/cache/CacheKey.java
> Javadoc-only update

- fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
> Doc only change

- fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
> Fix minor issue in evaluate method

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgres/GatherTablesDataModelVisitor.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgres/PostgresVacuumSettingDAO.java
- fhir-persistence-schema/README.md
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceTableGroup.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaGenerator.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaVersion.java
Update Postgres per IBM Cloud Recommendations and slight optimizations to change the transaction boundaries such that it fails more gracefully
> Update Postgres per IBM Cloud Recommendations and slight optimizations to change the transaction boundaries such that it fails more gracefully

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgres/PostgresVacuumSettingDAO.java
> Conditional OR was improperly set

- fhir-install/Dockerfile
- fhir-install/src/main/docker/ibm-fhir-schematool/Dockerfile
I tested the schematool with the restricted profile.  
I tried the  server and the testing didn't set the right restricted profile.  
> Dockerfile should ensure directories are writable by root group (gid=0) #2632

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/CommonDatabaseAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgres/PostgresAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgres/PostgresVacuumSettingDAO.java
> Add Null Check and Make schema drop idempotent #2401

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgres/PostgresVacuumSettingDAO.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceTableGroup.java
> Update the TableName for Vacuum during update-schema

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/common/BulkDataUtils.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ExportOperationTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRUrlParser.java
> Fail to process _typeFilter #2645

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-install/src/main/docker/ibm-fhir-schematool/run.sh
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
- fhir-server/liberty-config-tenants/config/tenant1/fhir-server-config.json
- fhir-server/liberty-config-tenants/config/tenant2/fhir-server-config.json
- fhir-server/src/main/java/com/ibm/fhir/server/FHIRApplication.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/filters/OriginalRequestFilter.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/OriginalRequestFilterTest.java
- fhir-server/src/test/resources/config/overrideuri/fhir-server-config.json
> Add Override for Alternative External Base URL and schematool update per review

- fhir-model/src/main/java/com/ibm/fhir/model/generator/FHIRAbstractGenerator.java
- fhir-model/src/main/java/com/ibm/fhir/model/generator/FHIRJsonGenerator.java
- fhir-model/src/main/java/com/ibm/fhir/model/generator/FHIRXMLGenerator.java
> Moved pretty printing field/method into base class

- fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
- fhir-registry/src/main/java/com/ibm/fhir/registry/spi/AbstractRegistryResourceProvider.java
> Issue #2651 - ConstraintGenerator updates

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
> Reindex of latest code produced a deadlock in some tables #2654

- fhir-bulkdata-webapp/pom.xml
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/context/BatchContextAdapter.java
- fhir-bulkdata-webapp/src/main/sh/.gitignore
- fhir-bulkdata-webapp/src/main/sh/cache-parquet-deps.sh
- Adds script to cache necessary parquet files
- Add format to the Context used in the push of resources
- Move SLF4J to provided as it causes a loop on parquet usage.
> Issue 2658

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/pool/PoolConnectionProvider.java
> change logging from warning to fine for 'not a problem' condition

- fhir-server/src/main/java/com/ibm/fhir/server/resources/filters/OriginalRequestFilter.java
> Original Request URI doubles up on whole system search

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/common/BulkDataUtils.java
- fhir-bulkdata-webapp/src/test/java/com/ibm/fhir/bulkdata/common/test/BulkDataUtilsTest.java
> Needed to account for encoded values in a decoded URI

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterVisitorBatchDAO.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/constraint/test/PatientConstraintValidator.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/ConformsToLoopTest.java
> Update logging level to avoid unnecessary log messages

- build/release/bin/10_build/2_version.sh
- fhir-parent/pom.xml
> compare fhir-examples.version against pom version before it changes

- fhir-parent/pom.xml
> Upgrade Dependencies in 4.9.0 #2698

- fhir-path/src/main/java/com/ibm/fhir/path/tool/Main.java
> issue #2702 - use Element.toString to print element nodes

- docs/src/pages/Conformance.md
- fhir-examples/src/main/resources/json/ibm/basic/BasicReference.json
- fhir-examples/src/main/resources/json/ibm/basic/BasicURI.json
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/ChainedSearchParam.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchQueryRenderer.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/CanonicalSupport.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/CanonicalValue.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/NewQueryBuilder.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/JDBCanonicalTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/ParameterExtractionTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchReferenceTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchURITest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractCanonicalTest.java
- fhir-persistence/src/test/resources/config/reference/extension-search-parameters.json
- fhir-persistence/src/test/resources/config/uri/extension-search-parameters.json
- fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
- fhir-search/src/main/java/com/ibm/fhir/search/parameters/InclusionParameter.java
- fhir-search/src/main/java/com/ibm/fhir/search/parameters/QueryParameter.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/InclusionParameterParseTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchChainTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchIncludeTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchReferenceTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchRevIncludeTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchReverseChainTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
> Issue #772 - implement canonical search

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/ChainedSearchParam.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchQueryRenderer.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchTokenTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractWholeSystemSearchTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractReverseChainTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchAllTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchChainTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchReverseChainTest.java
> Issue #2553 - fix chained search and system-only global parm search

- fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
> Issue #2716 - prevent potential NPE

- fhir-model/src/test/java/com/ibm/fhir/model/util/test/ReferenceMappingVisitorTest.java
- fhir-path/src/test/java/com/ibm/fhir/path/patch/test/FHIRPathPatchBuilderTest.java
> minor test changes

- fhir-bulkdata-webapp/src/main/sh/cache-parquet-deps.sh
> fix spark-hive dependency url and mark script executable

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/fast/ExportPartitionAnalyzer.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/system/ExportPartitionAnalyzer.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/listener/StepChunkListener.java
> Update for the fhir-bulkdata-webapp

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/ConvertOperationTest.java
- fhir-server-webapp/src/main/webapp/WEB-INF/web.xml
- fhir-server/liberty-config/configDropins/disabled/postgres/bulkdata.xml
- fhir-server/liberty-config/server.xml
None of these are particularly important, but I've been sitting on these minor local edits for a bit and thought I'd offer them back to the project.
> miscelaneous tweaks/fixes

- fhir-server/liberty-config/configDropins/defaults/bulkdata.xml
> WHFFHIR-213: Add Variable for FHIR_JBATCH

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/query/BindVisitor.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/version/SchemaConstants.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/ReindexResourceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FHIRDbDAOImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FetchPayloadsForIdsDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FetchResourceChangesDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FetchResourcePayloadsDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterVisitorBatchDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceDAOImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/RetrieveIndexDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/DerbyResourceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgres/PostgresReindexResourceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgres/PostgresResourceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgres/PostgresResourceNoProcDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/CalendarHelper.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/InitializeLogicalResourceDenorms.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/MigrateV0014LogicalResourceIsDeletedLastUpdated.java
> issue-2747 - thread safety for JDBC get/set timestamp UTC

- .github/workflows/javadocs.yml
> Update Javadoc Support #2750

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/ConditionalReferenceTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Also a minor log level tweak for a line I'm seeing a lot in our logs for bundle requests with FINE level trace.
> issue #2556 - add the conditional reference that failed to the error details

- .github/dependabot.yml
> Initial Dependabot Configuration

- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
> issue #2556 - add the entry index to the error message

- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/JavaBatchSchemaGenerator.java
> Update per QA - isolate the group name

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/version/CreateVersionHistory.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
> Update to support VHS Drop

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/version/CreateVersionHistory.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
> Update after missing pdm in fhiradmin condition

- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/action/batch/BatchCancelRequestAction.java
> Update for multiple job executions #2742

- fhir-audit/pom.xml
- fhir-bulkdata-webapp/pom.xml
- fhir-config/pom.xml
- fhir-model/pom.xml
- fhir-model/src/main/java/com/ibm/fhir/model/parser/FHIRJsonParser.java
- fhir-notification/pom.xml
- fhir-parent/pom.xml
- fhir-path/pom.xml
- fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java
Move up to Parsson groupId as the project moves from glassfish. 
> Update for #1155 and move to parsson

- build/docker/minio/Dockerfile
> cicd: Update Dockerfile with note and revert to latest

- conformance/fhir-ig-carin-bb/pom.xml
- conformance/fhir-ig-davinci-hrex/pom.xml
- conformance/fhir-ig-davinci-pdex-formulary/pom.xml
- conformance/fhir-ig-davinci-pdex-plan-net/pom.xml
- conformance/fhir-ig-davinci-pdex/pom.xml
- conformance/fhir-ig-us-core/pom.xml
- fhir-persistence-scout/pom.xml
- fhir-swagger-generator/pom.xml
> inherit version of fhir-examples from the parent

- .github/workflows/migration.yml
- build/migration/bin/8_teardown.sh
> Issue #2803 - always gather the migration test logs

- fhir-bucket/src/main/java/com/ibm/fhir/bucket/persistence/AddResourceBundleErrors.java
- fhir-bucket/src/main/java/com/ibm/fhir/bucket/persistence/GetResourceRefsForBundleLine.java
- fhir-bucket/src/main/java/com/ibm/fhir/bucket/persistence/MergeResourceTypes.java
- fhir-bucket/src/main/java/com/ibm/fhir/bucket/persistence/MergeResources.java
- fhir-bucket/src/main/java/com/ibm/fhir/bucket/persistence/ResourceTypesReader.java
- fhir-bucket/src/main/java/com/ibm/fhir/bucket/reindex/ServerDrivenReindexOperation.java
> Update Loggers to use the proper classes

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgres/PostgresFillfactorSettingDAO.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceTableGroup.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaConstants.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaGenerator.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaVersion.java
> issue-1834 set PostgreSQL fillfactor for updatable tables

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgres/PostgresAdapter.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaGenerator.java
- fhir-persistence-schema/src/main/resources/db2/add_any_resource.sql
- fhir-persistence-schema/src/main/resources/db2/delete_resource_parameters.sql
- fhir-persistence-schema/src/main/resources/db2/erase_resource.sql
- fhir-persistence-schema/src/main/resources/postgres/add_any_resource.sql
- fhir-persistence-schema/src/main/resources/postgres/delete_resource_parameters.sql
- fhir-persistence-schema/src/main/resources/postgres/erase_resource.sql
> issue-2348 consolidate parameter deletes to single procedure

- docs/src/pages/guides/FHIRServerUsersGuide.md
- docs/src/pages/guides/FHIRValidationGuide.md
- fhir-server-spi/src/main/java/com/ibm/fhir/server/spi/operation/FHIRResourceHelpers.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/ProfileValidationConfigTest.java
- operation/fhir-operation-erase/src/test/java/com/ibm/fhir/operation/erase/mock/MockFHIRResourceHelpers.java
- operation/fhir-operation-member-match/src/test/java/com/ibm/fhir/operation/davinci/hrex/test/MemberMatchTest.java
- operation/fhir-operation-validate/pom.xml
- operation/fhir-operation-validate/src/main/java/com/ibm/fhir/operation/validate/ValidateOperation.java
- operation/fhir-operation-validate/src/test/java/com/ibm/fhir/operation/validate/ValidateOperationTest.java
- operation/fhir-operation-validate/src/test/resources/config/default/fhir-server-config.json
> Issue #2905 - support profile properties from $validate when mode set

- fhir-profile/src/test/java/com/ibm/fhir/profile/ExtensionBuilder.java
this utility isn't currently used, but I think its useful and so I wanted to push this fix
> minor fix to currently-unused test util for creating extension definitions

- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
> issue 2751 - handle race condition for create control table

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/ConditionalReferenceTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/rest/FHIRRestInteractionCreate.java
- fhir-server/src/main/java/com/ibm/fhir/server/rest/FHIRRestInteractionVisitorMeta.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
> issue #2946 - add conditional reference value and entry index (again)

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/uscore/v311/USCoreMedicationRequestTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/uscore/v311/USCorePractitionerAndPractitionerRoleTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/uscore/v400/USCoreMedicationRequestTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/uscore/v400/USCorePractitionerAndPractitionerRoleTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/BundleValidationTest.java
> Issue #2513 - check bundle-level constraints on creates/updates

- fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java
Ran with Test cases
Method: Post 
Url: https://localhost:9443/fhir-server/api/v4/Patient/17d0b9c3153-e6df49f1-fc82-433d-a203-066f8ebdd94f
```
{
"request_unique_id": "c9f8d282-ecf1-47ca-98b9-4438f18b0d51",
"action": "C",
"start_time": "2021-11-10 20:48:42.406",
"end_time": "2021-11-10 20:48:45.757",
"api_parameters": {
"request": "/fhir-server/api/v4/Patient",
"request_status": 201
},
"data": {
"resource_type": "Patient",
"id": "17d0b9c3153-e6df49f1-fc82-433d-a203-066f8ebdd94f",
"version_id": "1"
},
"event_type": "fhir-create",
"description": "FHIR Create request",
"location": "0:0:0:0:0:0:0:1/localhost"
}
```
Method: PUT 
Url: https://localhost:9443/fhir-server/api/v4/Patient/17d0b9c3153-e6df49f1-fc82-433d-a203-066f8ebdd94f
Prior version
```
{
"request_unique_id": …
```
> Update RestAuditLogger to use status to switch RAL type

- docs/src/pages/Conformance.md
- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/exception/FHIRPersistenceIfNoneMatchException.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BundleTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/UpdateIfNoneMatchTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Update.java
- fhir-server/src/main/java/com/ibm/fhir/server/rest/FHIRRestInteractionVisitorBase.java
- fhir-server/src/main/java/com/ibm/fhir/server/rest/FHIRRestInteractionVisitorMeta.java
- fhir-server/src/main/java/com/ibm/fhir/server/rest/FHIRRestInteractionVisitorPersist.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
> issue 2050 ifNoneMatch returns 412 unless ifNoneMatchReturnsNotModified

- build/security/asoc.sh
- docs/readme.md
> AppScan Automation: The .irx is too large to analyze #2989

- docs/.babelrc
- docs/package.json
- docs/yarn.lock
> Update BabelRC Order and Yarn

- build/release/bin/10_build/3_build.sh
> Remove build threading for release

- fhir-install/src/main/docker/ibm-fhir-bucket-tool/Dockerfile
> Tag Release did not publish ibm-fhir-bucket-tool #3005

- fhir-install/Dockerfile
- fhir-install/src/main/resources/scripts/install.bat
- fhir-install/src/main/resources/scripts/install.sh
- fhir-parent/pom.xml
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchAllTest.java
- fhir-server-webapp/src/main/webapp/WEB-INF/web.xml
specifically for https://github.com/OpenLiberty/open-liberty/issues/18663 but also for the other fixes / enhancements
> upgrade to liberty 21.0.0.11

- README.md
> Update README.md to remove projects that are not in main

- fhir-parent/pom.xml
> Revert pom.xml change jakarta.xml.ws-api to 2.3.3

- demo/fhir/config/default/fhir-server-config.json
- fhir-profile/src/test/java/com/ibm/fhir/profile/test/ConstraintGeneratorTest.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/constraint/test/PatientConstraintValidatorTest.java
For both the constraint generator and the PatientConstraintValidatorTest
> Added extension validation examples

- fhir-server-spi/src/main/java/com/ibm/fhir/server/spi/operation/FHIRResourceHelpers.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/ReindexOperationPhase2Test.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/InteractionValidationConfigTest.java
> issue 3058 touchstone conformance fix for response bundle entry id

- fhir-install/Dockerfile
- fhir-install/src/main/resources/scripts/install.bat
- fhir-install/src/main/resources/scripts/install.sh
- fhir-parent/pom.xml
> upgrade to liberty 21.0.0.12

- docs/src/pages/guides/FHIRServerUsersGuide.md
> Fix for Bad text

- fhir-server-webapp/src/main/liberty/config/configDropins/defaults/monitoring.xml
> add monitoring feature to the default config

- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ExportOperation.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ImportOperation.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/OperationConstants.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/StatusOperation.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/AzurePreflight.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/FilePreflight.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/HttpsPreflight.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/NopPreflight.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/S3Preflight.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataImportUtil.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/CommonUtil.java
- Optimize the message to provider useful hints
> Error Message for Bad StorageProvider Configuration is unintentionally opaque #3118

- fhir-parent/pom.xml
> CVE-2021-42550: ch.qos.logback:logback-core #3132

- .github/ISSUE_TEMPLATE/feature_request.md
> Adds label to feature request

- fhir-bucket/src/main/java/com/ibm/fhir/bucket/app/Main.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/schema/LeaseManager.java
- fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/derby/DerbyLeaseTest.java
> issue #3135 stop lease maintenance thread before cancel lease

- docs/src/pages/Conformance.md
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRRequestContext.java
- fhir-config/src/main/java/com/ibm/fhir/config/SystemConfigHelper.java
- fhir-config/src/test/java/com/ibm/fhir/config/test/SystemConfigHelperTest.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FetchResourceChangesDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/FHIRPersistence.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/HistorySortOrder.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/context/FHIRSystemHistoryContext.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/context/impl/FHIRSystemHistoryContextImpl.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/FHIRPersistenceUtil.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/MockPersistenceImpl.java
- fhir-server-spi/src/main/java/com/ibm/fhir/server/spi/operation/FHIRResourceHelpers.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SystemHistoryTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/History.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/MockPersistenceImpl.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/ServerResolveFunctionTest.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/MockPersistenceImpl.java
- operation/fhir-operation-erase/src/test/java/com/ibm/fhir/operation/erase/mock/MockFHIRResourceHelpers.java
- operation/fhir-operation-member-match/src/test/java/com/ibm/fhir/operation/davinci/hrex/test/MemberMatchTest.java
Breaking change. The whole-system-history search endpoints have been changed to address spec-compliance. Pagination has changed. See Conformance.md for a detailed description.
> Issue #2972 type filter on system history plus new resource history interaction

- conformance/fhir-ig-spl/src/test/java/com/ibm/fhir/ig/us/spl/ExamplesValidationTest.java
> issue #3147 fix build for 2022 due to year validation rule

- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
> Update Capabilities Statement to use new copyright year

- docs/src/pages/Conformance.md
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
> issue #2026 #3174 #3175 history updates for QA

- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- Update message to include system/ and actual scopes
> Scope warning message for $export is confusing #3182

- .github/workflows/rebuild.yml
- build/release/bin/global/2_verify_build_settings.sh
my first attempt to fix the rebuild workflow
> set GITHUB_REF to the ref/tag we're rebuilding

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/ProfilesTestBase.java
- Small Enhancements to improve the Performance of Profile Test Execution 
- CI Enhancement
> Update to pull ITestContext CapabilityStatement

- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
> add --help option for fhir-persistence-schema cli jar #3209

- fhir-parent/pom.xml
- Found this while preparing for Testing... 
> Update Db2 JCC to Latest

- fhir-parent/pom.xml
- Found while preparing for testing
> Update cxf-rt-transports-http-hc to agree with cxf deps

- docs/package.json
- docs/yarn.lock
> Update per dependabot alert on node-fetch

- fhir-search/src/main/java/com/ibm/fhir/search/uri/UriBuilder.java
- fhir-search/src/test/java/com/ibm/fhir/search/uri/test/UriTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchAllTest.java
> Encode the datetime values in the bundle.Link.URL in the resource #3245

- fhir-config/src/main/java/com/ibm/fhir/config/FHIRRequestContext.java
- fhir-search/src/test/java/com/ibm/fhir/search/reference/ExtractReferenceValueTest.java
> issue #3281 - dont let FHIRRequetContext be null

- fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
- fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java
Signed-off-by: mpayne2 <mpayne2@us.ibm.com>
> Added Whole System History API to swagger and openapi

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchQueryRenderer.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/NewQueryBuilder.java
> issue #3275 fix PostgreSQL syntax for search with Prefer: return=minimal

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/kafka/KafkaNotificationTest.java
> Remove Deprecated API

- operation/fhir-operation-member-match/src/main/java/com/ibm/fhir/operation/davinci/hrex/provider/strategy/DefaultMemberMatchStrategy.java
- operation/fhir-operation-member-match/src/test/java/com/ibm/fhir/operation/davinci/hrex/test/MemberMatchIssuesTest.java
- operation/fhir-operation-member-match/src/test/resources/JSON/coverage.json
> Contained Resources shouldn't be processed in Member Match #3312

- fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
- fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java
Signed-off-by: mpayne2 <mpayne2@us.ibm.com>
> Generators not following Swagger and APIC spec

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-server-webapp/src/main/liberty/config/configDropins/disabled/jvm-dev.options
- Alternative docs for constrained environments during development.
> update docs for constrained environments

- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- Changing message per conversation in Issue 
> Scope warning message for  is confusing #3182

- docs/src/pages/Conformance.md
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BasicServerTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchExtensionsTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/UpdateTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRHttpServletRequestWrapper.java
- fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java
- fhir-server/src/test/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilterTest.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/FHIRHttpServletRequestWrapperTest.java
Issue #3318 - Improve support for Prefer HTTP header
> Issue #3318 - Improve support for Prefer HTTP header

- fhir-parent/pom.xml
- fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java
- Add batch alerts as individual messages
- Add update to Postgres driver to address `#26` which is a dependabot security alert
> Issue 1816

- fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java
Issue #3318 - Case insensitive check of HTTP header name
> Issue #3318 - Case insensitive check of HTTP header name

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/listener/ExitStatus.java
- Add an intermediate step to organize counts and then sort and then convert to ExitStatus
> Bulk Data S3Provider with Prefix Matrix's import status does not have  correct count when the job is completed #3038

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/VersionsOperationTest.java
- operation/fhir-operation-versions/README.md
- operation/fhir-operation-versions/pom.xml
- operation/fhir-operation-versions/src/main/java/com/ibm/fhir/operation/versions/VersionsOperation.java
Issue #3295 - Add R4B to $versions operation
> Issue #3295 - Add R4B to $versions operation

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-server-webapp/src/main/liberty/config/configDropins/defaults/bulkdata.xml
- fhir-server-webapp/src/main/liberty/config/configDropins/disabled/db2-cloud/bulkdata.xml
- fhir-server-webapp/src/main/liberty/config/configDropins/disabled/postgres/bulkdata.xml
- Added a missing variable defaultHostName (we used internally however did not move to opensource)
- added batch db hostname variable for consistency 
> Bulk Data import job with pod restarts unable to delete #3033

- README.md
I also expand the top-content to focus on getting started materials
> introduce links to the helm chart

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ChunkReader.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ImportPartitionAnalyzer.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/listener/Reporter.java
- FIxed the division in the RATE in the Infly reporting
- Added labels to end of job report
> Issue 3000: Update per QA

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceReferenceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgres/PostgresResourceReferenceDAO.java
> Issue 3106 - Update per QA

- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ExportOperation.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java
- operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtilTest.java
> Update to _type

- docs/src/pages/Conformance.md
> issue #2993 - document reference replacement non-conformance

- fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java
by fixing the ternary statement
> issue #3391 -  properly set auditIp

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ChunkWriter.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/listener/Reporter.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/AzureProvider.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/FileProvider.java
> Update for QA #2390

- fhir-audit/src/main/java/com/ibm/fhir/audit/beans/Batch.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java
> Update for QA #1816

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java
Issue #3423 - Update afterHistory and afterSearch
> Issue #3423 - Update afterHistory and afterSearch

- demo/fhir/configDropins/overrides/datasources.xml
- docs/src/pages/guides/DB2OnCloudSetup.md
- docs/src/pages/guides/FHIRPerformanceGuide.md
- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-server-webapp/src/main/liberty/config/configDropins/disabled/datasource-db2.xml
- fhir-server-webapp/src/main/liberty/config/configDropins/disabled/datasource-postgresql.xml
> issue #3043 updated connectionManager tuning guidance and samples

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRPatchTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Patch.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Issue #3450 - Handle deleted resource on PATCH
> Issue #3450 - Handle deleted resource on PATCH

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRPatchTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Patch.java
Issue #3450 - Return 404 on PATCH if resource does not exist
> Issue #3450 - Return 404 on PATCH if resource does not exist

- fhir-install/Dockerfile
- fhir-install/src/main/resources/scripts/install.bat
- fhir-install/src/main/resources/scripts/install.sh
- fhir-parent/pom.xml
> bump liberty from 21.0.0.12 to 22.0.0.3

- conformance/fhir-ig-us-core/CHANGELOG
- conformance/fhir-ig-us-core/src/main/resources/hl7/fhir/us/core/400/package/StructureDefinition-us-core-condition.json
- conformance/fhir-ig-us-core/src/main/resources/hl7/fhir/us/core/400/package/StructureDefinition-us-core-provenance.json
- conformance/fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/v400/ConformanceTest.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/FHIRPathUtil.java
Add tests under com.ibm.fhir.ig.us.core.test.v400.ConformanceTest to
show the issues.
For Provenance: fix provenance-1 to handle multiple agents
For Condition: fix us-core-1 to handle multiple categories
> issue #3490 - patch us core 4.0 fhirpath expressions

- fhir-persistence-blob/src/main/java/com/ibm/fhir/persistence/blob/BlobReadPayload.java
- fhir-persistence-blob/src/main/java/com/ibm/fhir/persistence/blob/BlobStorePayload.java
> issue #3414 support larger payload offload using Azure Blob

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/api/IDatabaseAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/CommonDatabaseAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgres/PostgresAdapter.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
> issue #3417 add grant usage to schema

- fhir-persistence-blob-app/README.md
> issue #3414 updated docs with new blob offload size limit

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchReferenceTest.java
and some minor formatting to reduce line lengths
> issue #3525 - replace hardcoded path and port with getRestBaseURL

- fhir-bucket/README.md
> remove redundant bootstrap-schema entries in fhir-bucket README

- fhir-bucket/src/main/java/com/ibm/fhir/bucket/app/Main.java
- fhir-bucket/src/main/java/com/ibm/fhir/bucket/client/PostResource.java
- fhir-bucket/src/main/java/com/ibm/fhir/bucket/scanner/CosScanner.java
and log the full exception if there's an issue during COS scanning
> issue #3509 - initialize cosClient before its first use

- docs/src/pages/guides/FHIRPerformanceGuide.md
> issue #3508 updated numConnectionsPerThreadLocal guidance in performance guide

- demo/fhir/configDropins/overrides/datasources.xml
- docs/src/pages/guides/DB2OnCloudSetup.md
- docs/src/pages/guides/FHIRPerformanceGuide.md
- fhir-server-webapp/src/main/liberty/config/configDropins/disabled/datasource-db2.xml
- fhir-server-webapp/src/main/liberty/config/configDropins/disabled/datasource-postgresql.xml
> back out numConnectionsPerThreadLocal=1 due to #3508

- fhir-persistence-cassandra/src/test/resources/fhir-server-config.json
- fhir-persistence-cos/src/test/resources/fhir-server-config.json
> remove stale properties from test configs

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/DavinciHealthRecordExchangeTest.java
We missed this one when we updated from the 0.2.0 snapshot to version
1.0.0
> issue #3526 - update DavinciHealthRecordExchangeTest for hrex 1.0.0

- fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
- fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java
and group export-related operations together
- in the all-in-one they now have tag "Bulk Data"
- in the file-per-resource they are all in export-swagger.json /
export-openapi.json
> issue #3409 - add bulkdata-status to all-in-one openapi

- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestBundleHelper.java
> skip bundle entry sorting for batch bundles

- fhir-install/src/main/docker/ibm-fhir-bucket-tool/run.sh
- fhir-install/src/main/docker/ibm-fhir-server/bootstrap.sh
- fhir-install/src/main/docker/ibm-fhir-term-graph-loader/run.sh
this way you can exit the containers via control+c when they are launch
on the foreground with a command like `docker run`
> issue #3565 - use exec in docker container launch scripts

- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
prior to calling doCreate on the interceptors
> issue #3576 - remove Resource.id passed via POST

- .github/workflows/rebuild.yml
And reduce the schedule from daily to weekly (on tuesdays)
> add 4.11.1 to rebuild list

- fhir-model/src/main/java/com/ibm/fhir/model/visitor/ResourceFingerprintVisitor.java
- fhir-model/src/test/java/com/ibm/fhir/model/util/test/ResourceFingerprintVisitorTest.java
> issue #3616 - flip the bytebuffer before we use it to update the digest

- docs/src/data/nav-items.yaml
- docs/src/pages/blog/everything.md
- docs/src/pages/blog/parquet.md
- docs/src/pages/blog/raspberrypi4howto.mdx
I also added a byline to the existing blog posts so that readers will know who wrote it and when.
> issue #3372 - document transforming ndjson export to parquet

- docs/src/pages/guides/FHIRServerUsersGuide.md
> issue #3629 - fix interceptor package name in user guide

- .github/workflows/migration.yml
> migration workflow should work when manually invoked

- fhir-parent/pom.xml
> bump jakarta.json from 1.0.0 to 1.1.0

- docs/src/pages/guides/FHIRValidationGuide.md
> fix table in docs

- fhir-profile/src/test/java/com/ibm/fhir/profile/test/BPConstraintGeneratorTest.java
> convert BPConstraintGeneratorTest main into a test

- fhir-persistence-schema/docs/SchemaToolUsageGuide.md
- fhir-remote-index/README.md
> #3698 schema tool usage updates for Citus

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/ReindexResourceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgres/PostgresReindexResourceDAO.java
> issue #3737 reindex must lock logical_resource_ident

- fhir-search/pom.xml
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRPatchTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Also added a single test case to ensure we have coverage for this case going forward.
> issue #3773 - add guard to avoid NPE for conditional patch

- fhir-server/src/main/java/com/ibm/fhir/server/operation/FHIROperationRegistry.java
Very minor change to (very slightly) reduce noise in the startup log
> Log one long message at level info instead of many smaller ones

- fhir-core/src/main/java/com/ibm/fhir/core/trace/Trace.java
- fhir-core/src/main/java/com/ibm/fhir/core/util/ResourceTypeHelper.java
- fhir-core/src/test/java/com/ibm/fhir/core/util/test/ResourceTypeHelperTest.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-schema/docs/SchemaToolUsageGuide.md
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/util/SchemaSupport.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/size/CitusSizeCollector.java
- fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/app/util/test/SchemaSupportTest.java
> issue #3741 db size report fixes for R4B and experimental Citus collection

- README.md
- docs/_config.yml
- docs/src/gatsby-theme-carbon/components/Footer.js
- docs/src/gatsby-theme-carbon/components/Header.js
to match the docker image description
> updated project description

- demo/docker-compose.yml
I missed this one in https://github.com/LinuxForHealth/FHIR/pull/3789
> fix demo env

- docs/src/pages/guides/FHIRModelGuide.md
- docs/src/pages/guides/FHIRModelGuide.mdx
pretty basic info but i've had this question a few times and so thought it might be worth mentioning in the docs
also made a few more model guide tweaks/additions while I was in there (partially due to review comment)
> document parsing from and generating to java.lang.String

- docs/src/pages/guides/FHIRServerUsersGuide.md
Signed-off-by: Prasanna Hegde <prasanna.hegde1@ibm.com>
> issue #3806 - fix audit event format documentation

- docs/src/pages/guides/FHIROperationFramework.md
Including renaming IBM FHIR Server -> LinuxForHealth FHIR Server
> Operation framework doc updates

- fhir-swagger-generator/pom.xml
> issue #3821 - add fhir-registry and fhir-core-r4b to the swagger cli jar

- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathType.java
I double-checked and the new data type (CodeableReference) and
resources are already listed.
> remove TODO in FHIRPathType

- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
Signed-off-by: Prasanna Hegde <prasanna.hegde1@ibm.com>
> issue #3681 - moved checkIfDataExistsForV0030 method call

- .github/workflows/build.yml
- .github/workflows/windows.yml
> update server path in build scripts

- fhir-path/src/test/java/org/linuxforhealth/fhir/path/test/FHIRPathVariablesTest.java
I created this test as a quick double-check for a user-reported issue
and I felt like it was worth checking it in.
> add a single fhirpath test

- fhir-database-utils/src/main/java/org/linuxforhealth/fhir/database/utils/version/CreateWholeSchemaVersion.java
- fhir-database-utils/src/main/java/org/linuxforhealth/fhir/database/utils/version/SchemaConstants.java
- fhir-persistence-schema/src/main/java/org/linuxforhealth/fhir/schema/app/Main.java
by using the passed user in grantPrivilegesForFhirData
> issue #3706 - fix regression of --grant-read-to

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-persistence-blob-app/README.md
- fhir-persistence-blob-app/src/main/java/org/linuxforhealth/fhir/persistence/blob/app/ReadBlobValue.java
- fhir-persistence-blob/src/main/java/org/linuxforhealth/fhir/persistence/blob/BlobContainerManager.java
- fhir-persistence-blob/src/main/java/org/linuxforhealth/fhir/persistence/blob/BlobDeletePayload.java
- fhir-persistence-blob/src/main/java/org/linuxforhealth/fhir/persistence/blob/BlobName.java
- fhir-persistence-blob/src/main/java/org/linuxforhealth/fhir/persistence/blob/BlobPropertyGroupAdapter.java
- fhir-persistence-blob/src/main/java/org/linuxforhealth/fhir/persistence/blob/BlobReadPayload.java
- fhir-persistence-blob/src/test/java/org/linuxforhealth/fhir/persistence/blob/BlobNameTest.java
- fhir-persistence-jdbc/src/main/java/org/linuxforhealth/fhir/persistence/jdbc/dto/ErasedResourceRec.java
- fhir-persistence-jdbc/src/main/java/org/linuxforhealth/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
> issue #3866 parse offload using elements to subset

- conformance/fhir-ig-us-core/README.md
> issue #3870 added 5.0.1 to README.md

- MAINTAINERS.md
- cql/pom.xml
- fhir-examples/pom.xml
- fhir-parent/pom.xml
- fhir-tools/pom.xml
- fhir-tools/src/main/java/org/linuxforhealth/fhir/model/plugin/generator/ModelGenerator.java
- operation/fhir-operation-bulkdata/src/main/resources/status.json
- term/pom.xml
> various correctness updates to poms and contacts

- fhir-server-test/src/test/java/org/linuxforhealth/fhir/server/test/examples/ExampleRequestProcessor.java
> issue #3304 - catch the Assertion error I missed previously

- fhir-persistence-jdbc/src/main/java/org/linuxforhealth/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence/src/main/java/org/linuxforhealth/fhir/persistence/FHIRPersistenceSupport.java
- fhir-persistence/src/main/java/org/linuxforhealth/fhir/persistence/ResourceResult.java
- fhir-persistence/src/main/java/org/linuxforhealth/fhir/persistence/SingleResourceResult.java
> issue #3690 fix wall clock time check

- build/release/bin/global/2_verify_build_settings.sh
> remove the check for DockerHub username and token

- fhir-examples/pom.xml
> update ossrh endpoint in one more spot

- build/release/bin/30_release/0_sonatype.sh
> another release fix

- fhir-server-test/src/test/java/org/linuxforhealth/fhir/server/test/examples/ExampleRequestProcessor.java
I added a simple retry loop with a hard-coded MAX_TRIES to 2
and no backoff between attempts.
I did not add any logic to fail the test if we see too many of these.
> issue #3910 - add a simple retry loop

- docs/src/pages/guides/FHIRSearchConfiguration.md
> minor doc fix

- fhir-smart/src/main/java/org/linuxforhealth/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- operation/fhir-operation-everything/src/main/java/org/linuxforhealth/fhir/operation/everything/EverythingOperation.java
> issue #3503 - special case FORBIDDEN errors when reading the patient resource

- fhir-config/src/main/java/org/linuxforhealth/fhir/config/FHIRConfiguration.java
- fhir-config/src/main/java/org/linuxforhealth/fhir/config/FHIRRequestContext.java
- fhir-model/src/main/java/org/linuxforhealth/fhir/model/util/XMLSupport.java
- fhir-server/src/main/java/org/linuxforhealth/fhir/server/filter/rest/FHIRRestServletFilter.java
1. add more input validation for header values
2. set additional attributes on the XMLTransformerFactory
> security hardening

- fhir-persistence/src/main/java/org/linuxforhealth/fhir/persistence/util/InputOutputByteStream.java
> issue #3957 avoid narrowing conversion flagged by CodeQL

- fhir-benchmark/pom.xml
Signed-off-by: Berkant Karduman <karduman.berkant@gmail.com>
> LinuxForHealth renaming

- fhir-server/src/main/java/org/linuxforhealth/fhir/server/filter/rest/FHIRRestServletFilter.java
- fhir-server/src/main/java/org/linuxforhealth/fhir/server/listener/FHIRServletContextListener.java
> issue-3968 - validating the tenant Id passed in header in configured tenants list

- .github/workflows/rebuild.yml
> rebuild 5.0.0 and remove dockerhub rebuild

- fhir-core/src/main/java/org/linuxforhealth/fhir/core/context/FHIRPagingContext.java
- fhir-core/src/main/java/org/linuxforhealth/fhir/core/context/impl/FHIRPagingContextImpl.java
- fhir-persistence-jdbc/src/main/java/org/linuxforhealth/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/org/linuxforhealth/fhir/persistence/jdbc/util/NewQueryBuilder.java
- fhir-persistence/src/main/java/org/linuxforhealth/fhir/persistence/MultiResourceResult.java
- fhir-persistence/src/test/java/org/linuxforhealth/fhir/persistence/search/test/AbstractPLSearchTest.java
- fhir-persistence/src/test/java/org/linuxforhealth/fhir/persistence/search/test/AbstractSearchCompartmentTest.java
- fhir-persistence/src/test/java/org/linuxforhealth/fhir/persistence/search/test/AbstractSearchStringTest.java
- fhir-persistence/src/test/java/org/linuxforhealth/fhir/persistence/test/FHIRPersistenceContextTest.java
- fhir-persistence/src/test/java/org/linuxforhealth/fhir/persistence/test/common/AbstractPagingTest.java
- fhir-search/src/main/java/org/linuxforhealth/fhir/search/SearchConstants.java
- fhir-search/src/main/java/org/linuxforhealth/fhir/search/context/FHIRSearchContextFactory.java
- fhir-search/src/main/java/org/linuxforhealth/fhir/search/util/SearchHelper.java
- fhir-search/src/test/java/org/linuxforhealth/fhir/search/sort/test/SortUriTest.java
- fhir-search/src/test/java/org/linuxforhealth/fhir/search/uri/test/UriTest.java
- fhir-server-test/src/test/java/org/linuxforhealth/fhir/server/test/SearchTest.java
- fhir-server-test/src/test/java/org/linuxforhealth/fhir/server/test/SortingTest.java
- fhir-server-test/src/test/resources/testdata/patient-example-d.json
- fhir-server/src/main/java/org/linuxforhealth/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/org/linuxforhealth/fhir/server/util/FHIRRestHelperTest.java
> issue-3590 - Add warning to search response when pages have shifted

- fhir-persistence-schema/src/main/resources/parameter_names.properties
> issue-3563 - adding search parameters to parameter_names.properties

- fhir-install/Dockerfile
- fhir-install/src/main/resources/scripts/install.bat
- fhir-install/src/main/resources/scripts/install.sh
- fhir-parent/pom.xml
> issue-4017 - Upgrade to liberty 22.0.0.10

- fhir-model/src/main/java/org/linuxforhealth/fhir/model/string/util/StringSizeControlStrategyFactory.java
- fhir-model/src/main/java/org/linuxforhealth/fhir/model/string/util/strategy/MaxBytesStringSizeControlStrategy.java
- fhir-model/src/main/java/org/linuxforhealth/fhir/model/string/util/strategy/StringSizeControlStrategy.java
- fhir-model/src/main/resources/META-INF/services/org.linuxforhealth.fhir.model.string.util.strategy.StringSizeControlStrategy
- fhir-model/src/test/java/org/linuxforhealth/fhir/model/string/util/test/StringSizeControlStrategyTest.java
- fhir-persistence-jdbc/src/main/java/org/linuxforhealth/fhir/persistence/jdbc/dao/impl/ParameterTransportVisitor.java
- fhir-persistence/src/main/java/org/linuxforhealth/fhir/persistence/index/ParameterValueVisitorAdapter.java
- fhir-persistence/src/main/java/org/linuxforhealth/fhir/persistence/index/SearchParametersTransportAdapter.java
- fhir-persistence/src/test/java/org/linuxforhealth/fhir/persistence/helper/MessageSerializationTest.java
- fhir-remote-index/src/test/java/org/linuxforhealth/fhir/remote/index/RemoteIndexTest.java
> issue-4021 - Truncate String parameter value before persisting

- .github/workflows/audit.yml
- .github/workflows/build.yml
- .github/workflows/integration.yml
- .github/workflows/migration.yml
- .github/workflows/notification.yml
- .github/workflows/persistence.yml
- .github/workflows/reindex.yml
- .github/workflows/windows.yml
> ignore markdown updates when considering which workflows to run

- fhir-parent/pom.xml
> bump commons-text from 1.9 to 1.10.0 in fhir-parent

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-config/src/main/java/org/linuxforhealth/fhir/config/FHIRConfiguration.java
- fhir-server-webapp/src/main/liberty/config/config/default/fhir-server-config.json
- fhir-smart/src/main/java/org/linuxforhealth/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- fhir-smart/src/test/java/org/linuxforhealth/fhir/smart/test/AuthzPolicyEnforcementTest.java
> issue-3716 - validate securityContext for a Binary resource

- fhir-server/src/main/java/org/linuxforhealth/fhir/server/resources/Capabilities.java
Also removed the "publisher" field which is optional.
Also updated copyright from IBM to "Merative and others".
Also fixed a minor compiler warning.
> issue #4061 - "IBM" to "LinuxForHealth" in the CapabilityStatement

- docs/src/pages/index.mdx
> update conformance link

- .github/workflows/audit.yml
- build/audit/bin/gather-logs.sh
- build/audit/bin/pre-integration-test.sh
- build/audit/kafka/docker-compose.yml
- build/audit/kafka/integration-test.sh
- build/audit/kafka/pre-integration-test.sh
- build/notifications/bin/gather-logs.sh
- build/persistence/bin/gather-logs.sh
- fhir-server-webapp/src/test/liberty/config/config/default/fhir-server-config-audit-cicd.json
> correcting audit integration test script file

- fhir-smart/src/main/java/org/linuxforhealth/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- fhir-smart/src/test/java/org/linuxforhealth/fhir/smart/test/AuthzPolicyEnforcementTest.java
> issue #4083 - handle missing patient_id claim

- fhir-server-test/src/test/java/org/linuxforhealth/fhir/server/test/BundleTest.java
- fhir-server/src/main/java/org/linuxforhealth/fhir/server/util/RestAuditLogger.java
> issue-3493 - Removing the "batch" section from audit event messages for batch bundle entries

- fhir-install/Dockerfile
- fhir-install/src/main/resources/scripts/install.bat
- fhir-install/src/main/resources/scripts/install.sh
- fhir-parent/pom.xml
> issue-4116 - Upgrade openliberty-runtime from 22.0.0.10 to 22.0.0.12

- .github/workflows/rebuild.yml
> update rebuild workflow for 5.1.1

- README.md
- docs/src/pages/guides/FHIRServerUsersGuide.md
> link to linuxforhealth docker image and lfh-helm instead of alvearie
