LinuxForHealth/FHIR

- fhir-server-test/src/test/java/com/ibm/watson/health/fhir/server/test/BasicServerTest.java
- fhir-server/liberty-config/server.xml
- fhir-server/src/main/java/com/ibm/watson/health/fhir/server/filter/rest/FHIRHttpServletRequestWrapper.java
- removed extraneous webcontainer
- updated test to reflect _format decoded
- update code to reflect _format in rare circumstance with Accept
conflicting
> _format parameter overrides the HTTP Header Accept #542

- fhir-bulkimportexport-webapp/WebContent/META-INF/MANIFEST.MF
- fhir-bulkimportexport-webapp/WebContent/WEB-INF/ibm-web-ext.xml
- fhir-bulkimportexport-webapp/WebContent/WEB-INF/ibm-ws-bnd.xml
- fhir-bulkimportexport-webapp/WebContent/WEB-INF/web.xml
- fhir-bulkimportexport-webapp/liberty-config/server.xml
- fhir-bulkimportexport-webapp/pom.xml
- fhir-bulkimportexport-webapp/src/main/liberty/config/server.xml
- fhir-bulkimportexport/pom.xml
- fhir-bulkimportexport/src/main/java/META-INF/MANIFEST.MF
- fhir-bulkimportexport/src/main/java/META-INF/batch-jobs/FhirBulkExportBatchJob.xml
- fhir-bulkimportexport/src/main/java/META-INF/batch-jobs/FhirBulkExportChunkJob.xml
- fhir-bulkimportexport/src/main/java/META-INF/batch-jobs/FhirBulkImportBatchJob.xml
- fhir-bulkimportexport/src/main/java/META-INF/batch-jobs/FhirBulkImportChunkJob.xml
- fhir-bulkimportexport/src/main/java/META-INF/batch.xml
- fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkexport/BulkExportBatchLet.java
- fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkexport/ChunkProcessor.java
- fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkexport/ChunkReader.java
- fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkexport/ChunkWriter.java
- fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkimport/BulkImportBatchLet.java
- fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkimport/ChunkReader.java
- fhir-bulkimportexport/src/main/java/com/ibm/watson/health/fhir/bulkimport/ChunkWriter.java
This is the initial code drop, further enhancement will focus on the support of:
(1) Use one COS object(file) for one exported resourceType with configurable object name.
(2) Able to import from one or more COS object(s) with name beginning with configurable string.
etc.
Signed-off-by: xuwang@us.ibm.com
> issue #30 Initial version of Javabatch for bulk import&export

- fhir-openapi/pom.xml
- fhir-openapi/src/main/webapp/WEB-INF/ibm-web-ext.xml
- fhir-swagger-generator/src/main/java/com/ibm/watson/health/fhir/openapi/generator/FHIROpenApiGenerator.java
- fhir-swagger-generator/src/main/java/com/ibm/watson/health/fhir/swagger/generator/FHIRSwaggerGenerator.java
In DSTU2 we prefixed classes with the name of the containing type.
However, in R4, we moved to a nested class structure and so the simple names are no longer unique.
Furthermore, there are now some BackboneElements that share a local name
within the same resource (e.g. ImplementationGuide.Definition.resource
and ImplementationGuide.Manifest.resource) and so we need to use the
full path of contained resource simple names to ensure uniqueness.
Signed-off-by: lmsurpre <lmsurpre@us.ibm.com>
> issue #26 - include containing classes in element definition ids to avoid conflicts

- fhir-openapi/pom.xml
this is consistent with how we name the fhir-server-webapp war file
> Update fhir-openapi war name to fix the build

- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/BulkImportBatchLet.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ChunkReader.java
IBM COS can support both null and "" as initial continuetoken, but s3 can only support null, so change to use null to be compatible with s3.
> issue #101 use null instead of empty continuetoken for s3

- fhir-server-test/src/test/java/com/ibm/fhir/cli/test/FHIRCliTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/ServerSpecTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/UpdateTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
According to the spec, 
(1) Conditional update a resource without match and without id in the input resource, server should create the resource with server assigned resource id and with 201 response code instead of return 400 error.
(2) Conditional update a resource with 1 match but with a id in the input resource which is different from the id of the search result, server should return 400 error.
> issue #117 Create resource if conditionalUpdate not found

- fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRHttpServletRequestWrapper.java
Pull request #163 introduces a bad error where certain requests (with no Accept header I guess) result in 500 error with NullPointerException.
> NPE fix for issue #161

- fhir-provider/src/main/java/com/ibm/fhir/provider/util/FHIRProviderUtil.java
When exception happens during parsing the request body, the charset in accept header of the request is incorrectly dropped from the content-type header of the response.
Codes are changed to use the charset gotten from the accept header(if any) of the request for the content-type response header.
> issue #170 miss charset in content-type of 400 response

- fhir-server-test/pom.xml
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRNotificationServiceClientEndpoint.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/WebSocketNotificationsTest.java
- configure the base test
- set tests as single threaded
- update the base tests
> CI: Tests report failure when messages are sent back. #184

- fhir-search/src/main/java/com/ibm/fhir/search/valuetypes/impl/ValueTypesR4Impl.java
- fhir-server/liberty-config/server.xml
I added this subpackage in #202.
For each type that was moved to the new package, it causes warning like this from ValueTypesR4Impl:
> unable to convert to class while setting value types for AccountStatus
> add additional check for Code subtypes in the new types.code subpackage #202

- fhir-install/pom.xml
> fhir-bulkimportexport-webapp is not in the fhir-install dependency tree

- fhir-core/pom.xml
- fhir-core/src/main/java/com/ibm/fhir/core/FHIRUtilities.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/LogFormatter.java
- fhir-parent/pom.xml
- fhir-server-webapp/pom.xml
- cleans up commons io usage
- removes unused gzipdecompress/gzipcompress/isgzip
- cleans up unused code in database utils
> Remove Commons-IO and corresponding Gzip usage #232

- .github/workflows/build.yml
- fhir-model/src/test/java/com/ibm/fhir/model/spec/test/R4ExamplesDriver.java
- fhir-parent/pom.xml
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/WebSocketNotificationsTest.java
Enable Spec Driver to use string values for TestTypes and Support switches in maven #242
`mvn clean install -Pall-tests -f fhir-parent/pom.xml  -Dcom.ibm.fhir.model.spec.test.R4ExamplesDriver.testType=ALL`
> Enable Spec Driver to use string values for TestTypes and Support switches in maven #242

- fhir-model/pom.xml
- fhir-model/src/main/java/com/ibm/fhir/model/generator/FHIRAbstractGenerator.java
- fhir-model/src/main/java/com/ibm/fhir/model/generator/FHIRGenerator.java
- fhir-model/src/main/java/com/ibm/fhir/model/generator/FHIRJsonGenerator.java
- fhir-model/src/main/java/com/ibm/fhir/model/generator/FHIRXMLGenerator.java
- fhir-model/src/main/java/com/ibm/fhir/model/parser/FHIRJsonParser.java
- fhir-model/src/main/java/com/ibm/fhir/model/parser/FHIRParser.java
- fhir-model/src/main/java/com/ibm/fhir/model/parser/FHIRXMLParser.java
- fhir-model/src/main/java/com/ibm/fhir/model/visitor/CopyingVisitor.java
- fhir-model/src/main/java/com/ibm/fhir/model/visitor/PathAwareAbstractVisitor.java
- fhir-parent/pom.xml
- fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java
Added JavaDoc and removed the `reset()` method from all FHIRGenerator classes (it wasn't doing anything) and also from the public FHIRParser interface as its only used internally (no use case for invoking it as a user).
Also introduced a dependency on
http://jcip.net/annotations/doc/net/jcip/annotations/package-summary.html
to highlight that the FHIRJsonParser and FHIRXMLParser are *not*
threadsafe.
Also added this annotation to the CopyingVisitor and
PathAwareAbstractVisitor which should definitely not be shared across
threads either.
Signed-off-by: lmsurpre <lmsurpre@us.ibm.com>
> Add JavaDoc for FHIRParser and FHIRGenerator

- docs/Conformance.md
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QueryBuilderUtil.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
Now all date param values will be handled as an implicit range unless
there are microseconds given. For example:
* `01:01:01` -> `[01:01:01, 01:01:02)`
* `01:01:01.1` -> `01:01:01.100000`
* `01:01:01.111111` -> `01:01:01.111111`
Once we support passing times without seconds, this should also adjust the implicit range by adding a whole minute:
* `01:01` -> `[01:01, 01:02)`
I considered guessing at the passed precision by looking for the last
non-zero digit, but our DateTime actually doesn't store this type of precision detail.
> issue #305 - handle more date param values as ranges

- fhir-parent/pom.xml
```
Known  critical severity security vulnerability detected in com.fasterxml.jackson.core:jackson-databind < 2.9.10 defined in pom.xml. | Known  critical severity security vulnerability detected in com.fasterxml.jackson.core:jackson-databind < 2.9.10 defined in pom.xml.
Known  critical severity security vulnerability detected in com.fasterxml.jackson.core:jackson-databind < 2.9.10 defined in pom.xml.
```
> update the parent dependencies for jackson libraries #322

- fhir-core/src/main/java/com/ibm/fhir/core/context/FHIRPagingContext.java
- fhir-core/src/main/java/com/ibm/fhir/core/context/impl/FHIRPagingContextImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceDAOImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/FHIRPersistenceUtil.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPagingTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
- fhir-persistence/src/test/resources/logging.unitTest.properties
- fhir-search/src/main/java/com/ibm/fhir/search/context/FHIRSearchContext.java
- fhir-search/src/main/java/com/ibm/fhir/search/context/impl/FHIRSearchContextImpl.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
> Issue #329 - Invalid SQL generated in ResourceDAOImpl

- .github/workflows/build.yml
- fhir-parent/pom.xml
this commit introduces a dependency on https://github.com/marketplace/actions/setup-java-environment-based-on-adoptopenjdk
> issue #335 - use openjdk in favor of zulu

- fhir-model/src/main/java/com/ibm/fhir/model/util/FHIRUtil.java
- fhir-provider/src/main/java/com/ibm/fhir/provider/FHIRJsonPatchProvider.java
- fhir-provider/src/main/java/com/ibm/fhir/provider/FHIRJsonProvider.java
- fhir-provider/src/main/java/com/ibm/fhir/provider/FHIRProvider.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java
Also updated FHIRJsonProvider and FHIRJsonPatchProvider to be consistent
across all 3 providers.
> issue #193 - mirror "isServer" logic on the writeTo methods

- fhir-examples/src/main/resources/json/ibm/basic/BasicString.json
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QueryBuilderUtil.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchStringTest.java
1. add tests in AbstractSearchStringTest
2. modify JDBCParameterBuildingVisitor to pass the tests
previously we were indexing "use" for HumanName and "type" for Addres;
now we index just the string fields
> issue #344 - properly index Address and HumanName

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/ParameterExtractionTest.java
string, uri, and canonical types can be extracted as multiple different
search parameter types
to address issue #348, we need to store the value in the valueCode when
a string data type is extracted for a search parameter of type token
while there, I flushed out ParameterExtractionTest to cover all valid
combinations of data type + search parameter type (but just one test per
combo)
> issue #348 - add extraction support for multi-type search params

- fhir-examples/pom.xml
- fhir-model/src/main/java/com/ibm/fhir/model/path/function/ResolveFunction.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-tools/pom.xml
1. remove jdk11 profile from extra projects (already previously removed from fhir-parent)
2. fixup log message in FHIRPersistenceJDBCImpl (log the value not the JSON-like toString)
3. minor javadoc change and whitespace stuff
> miscelaneous edits

- fhir-model/src/main/java/com/ibm/fhir/model/path/evaluator/FHIRPathEvaluator.java
This interpretation was preferred because it allows us to write
constraints like `Observation.subject.resolve().is(Patient)` and always
get a true/false result.
This differs from the implied language in the FHIRPath spec, but matches
both our previous implementation as well as Graham's implementation.
I opened https://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=25189 to track this discrepency.
> issue #370 - have `is` return false on empty input collection

- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceGroup.java
In add_any_resource storedprocedure, the codes insert record to the resource table with "TENANT_ID" column, but in the resource table creation codes, the "TENANT_ID" column is missed, this fix is to add the missed "TENANT_ID" column to the table creation codes.
I choose to add it instead of dropping it from the storedprocedure for the purpose of being compatible with existing deployments.
> issue #383 fix db2 fhir resource creation issue

- .github/workflows/build.yml
- fhir-model/pom.xml
- fhir-parent/pom.xml
- fhir-persistence-jdbc/pom.xml
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/ParameterExtractionTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/ExtractorValidator.java
issue #395 - add guards for missing values
privitive elements with no values (only extensions) are not common, but
they are allowed and we shouldn't fail on them
also note: i updated the `Coding` (and `CodeableConcept`) extraction so
that a Coding won't get indexed unless it has a code value.
also updated parent-pom jdbc-all-tests profile to enable setting of
JDBC testType independent of the model testType
I found that the existing profiles (`model-all-tests` and
`jdbc-all-tests`) didn't actual set any system properties at runtime. I
fixed this by
1. introducing `fhir-model.testType` and
`fhir-persistence-jdbc.testType` parameters with a default value of
MINIMAL
2. updating the profile definitions to set these properties when
activated
3. updating surefire-plugin config in …
> Patch for 395

- fhir-model/src/main/java/com/ibm/fhir/model/path/evaluator/FHIRPathEvaluator.java
In pull request https://github.com/IBM/FHIR/pull/376 I missed that `!isSingleton(nodes)` would be true for empty collections and so I didn't get the intended behavior.
Now `is` will evaluate to SINGLETON_FALSE for in both the operation and function contexts.
> issue-370 - fixup 1c6498f1b41b9f790ef8673dc45e2048dd447cce

- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- When the DomainResource is returned, without an expression, the
logging fails.
> fix logging for SearchUtil extractParametersValues #255

- fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathDateTimeValue.java
- fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathNumberValue.java
- fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathTimeValue.java
- fhir-model/src/main/java/com/ibm/fhir/model/path/evaluator/FHIRPathEvaluator.java
* Updated visitNumberLiteral to use presence of a decimal point instead of exceptions to control logic flow
* Updated FHIRPathNumberValue.isComparableTo/compareTo to accommodate newly introduced FHIRPathQuantityNode
* Updated FHIRPathDateTimeValue and FHIRPathTimeValue classes with new patterns per the updated FHIRPath grammar
> Issue #389 - fixed issues related to failing FHIRPathSpec tests

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyMaster.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
The fixes:
(1) To speed up sequence fetch, add a derby config to pre-create 1000 sequence numbers instead of the default 100.
(2) Made changes to make sure committing the transaction after the processing of each example, then old codes commit only once after all the test examples are processed.
> issue #426 fix for pipeline derby jdbc test error

- fhir-model/src/main/java/com/ibm/fhir/model/type/Element.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Extension.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Id.java
- fhir-model/src/main/java/com/ibm/fhir/model/util/ValidationSupport.java
- fhir-model/src/test/resources/FHIRPath/tests-fhir-r4-old.xml
- fhir-swagger-generator/src/main/resources/.gitignore
- fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java
These elements are "special" in that, in the XML serialization, they are
attributes and not elements.
To facilitate this "specialness", we keep them as raw java strings in
our model, but according to the spec they should still be valid data
types (String and Id respectively).
Also added javadoc for ValidationSupport.java
> Add validation for Element.id and Extension.url

- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/CheckPointAlgorithm.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/CheckPointUserData.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/ChunkReader.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/ChunkWriter.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/TransientUserData.java
- fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
- fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/BulkExportJobExecutionResponse.java
- fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/PollingLocationResponse.java
- fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/processor/impl/CosExportImpl.java
- fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/model/PollingLocationResponseTest.java
(1) Enhanced bulkexport job to support multiple resource types, and return the exported resource types and counts info in the exit status of the batch job, e.g, Patient[1000,1000,200]:Observation[1000,1000,200]
(2) Enhanced bulkdate export operation to parse the exit status of the batch job and generate the download Urls and resources counts for all the exported files of all the resource types like following:
...
[{ "type" : "Patient", "url": "https://s3.us-south.cloud-object-storage.appdomain.cloud/fhir-r4-connectathon/job2/Patient_1.ndjson", "count": 400},{ "type" : "Patient", "url": "https://s3.us-south.cloud-object-storage.appdomain.cloud/fhir-r4-connectathon/job2/Patient_2.ndjson", "count": 400},{ "type" : "Patient", "url": …
> issue #103 #105 bulkdataExport multi-resType support with Res counts

- docs/src/pages/Conformance.md
- fhir-provider/src/main/java/com/ibm/fhir/provider/FHIRProvider.java
- fhir-provider/src/test/java/com/ibm/fhir/provider/FHIRProviderTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/PrettyServerFormatTest.java
- Update conformance.md statements on _pretty
- Update Provider to support Pretty from CDI injected URIInfo
- Introduce new test for Pretty
- Update SearchConstants to avoid processing _pretty as a Search
Parameter
> Support _pretty query parameter #269

- fhir-model/src/main/java/com/ibm/fhir/model/util/ModelSupport.java
- fhir-swagger-generator/.gitignore
- fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
- fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/APIConnectAdapter.java
- fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java
1. Updated FHIROpenApiGenerator to match the recent changes to
FHIRSwaggerGenerator (e.g. one file per resource type)
2. utilize the Liberty mpOpenAPI-1.0 feature to validate the updated
OpenAPI definition; this helped to find and a number of issues that were
applicable to both the OpenAPI and the Swagger 2.0 definitions, includ
ing:
* Problem:  Complex datatypes and wildcard choice elements are
referencing non-existent primitive elements.
* Solution:  add isApplicableForClass guard to the loops for adding
the choice type properties and the data type and definitions...this
simplifies the schema by skipping both special types like Dosage and
ElementDefinition and metadata types like ContactDetail, Contributor,
DataRequirement, and ParameterDefinition (unless they are explicitly
referenced …
> more swagger tweaks and update OpenApiGenerator to match

- fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
- fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java
1. I found that the swagger definitions are missing the 'resourceType'
propery; after this change it should be there for all resource types.
Unfortunately, I think we need to change our whole approach if we want
to indicate the value is 'fixed'. Because there are some places where
any Resource is allowed, I added this property to the base Resource type (as an enum).
However, Swagger/OpenAPI--or at least the
Liberty support for it--doesn't like it when a property is defined in
both halves of the *allOf* constraint...even if those two are compatible.
To address it, I think we should avoid the *allOf* construct and
just copy the duplicated Resource properties into each different
Resource subtype. For now, its just a TODO in the code.
2. Added an extra check to prevent the creation of a …
> more swagger updates

- fhir-model/src/main/java/com/ibm/fhir/model/util/FHIRUtil.java
- fhir-model/src/main/java/com/ibm/fhir/model/util/ModelSupport.java
- fhir-model/src/main/java/com/ibm/fhir/model/visitor/PathAwareVisitor.java
- fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/FHIRPathUtil.java
- fhir-path/src/test/java/com/ibm/fhir/path/test/FHIRPathCacheSizeEstimator.java
- fhir-profile/src/main/java/com/ibm/fhir/profile/ProfileSupport.java
- Clean up `implies` logic
- Clean up external constant handling
- Add logic to unescape additional characters
- Re-introduce keyword checking into PathAwareVisitor
> Issue #453 - post refactor clean-up

- fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
- fhir-path/src/test/resources/FHIRPath/tests-fhir-r4.xml
Changed error handling logic in `FHIRPathEvaluator.EvaluatingVisitor.visitAdditiveExpression`
Re-enabled a couple of FHIRPath spec tests
> Issue #389 - re-enable FHIRPath spec tests

- docs/src/pages/guides/FHIRServerUsersGuide.md
we used to package IBM Java with our server, but now Java is just a prereq.  we had this info in our "setting up for development" wiki, but we also need it to install and run.
> document java prereq

- fhir-examples/src/main/resources/json/ibm/basic/BasicNumber.json
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/NumberParmBehaviorUtil.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/NumberParmBehaviorUtilTest.java
- fhir-persistence-jdbc/src/test/java/testng.xml
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchNumberTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchQuantityTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchReferenceTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchStringTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchTokenTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchURITest.java
- fhir-persistence/src/test/resources/config/number/extension-search-parameters.json
- fhir-persistence/src/test/resources/logging.unitTest.properties
- fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParameterValue.java
- Add precision value to BasicNumber.json
- Extend the extension-search-parameters.json to add precision
SearchParameter
- Enhance AbstractSearchNumberTest.java to include precision
- Update testng.xml to include new tests that were not specifically
included
- Cleanup formatting in FHIRPersistenceJDBCImpl
- Implement variable precision in the search
- Add guard to the Null Prefix.
- Added a conformance related commentary to the Abstract Tests
Reference: https://hl7.org/fhir/search.html#number
> Number searches with implicit ranges #257

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/ParameterDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterDAOImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/CodeSystemsCache.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/NumberParmBehaviorUtil.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/QuantityParmBehaviorUtil.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/NumberParmBehaviorUtilTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/QuantityParmBehaviorUtilTest.java
- fhir-persistence-jdbc/src/test/java/testng.xml
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchQuantityTest.java
- Remove reference to PARAMETERS_GTT which is not used and also removed
insert method from the interface and impl
- Refactor JDBCQueryBuilder to move QuantityParameter processing into a
Specific Utility related to the processing
- Add QuantityParmBehaviorUtil
- Add tests for QuantityParmBehaviorUtil and the various methods and
prefixes
- Add QuantityParmBehaviorUtilTest to testng.xml
- Reset NumberParmBehaviorUtilTest to FINE (avoids needless logs at
INFO)
> Quantity searches update to consider implicit ranges #257

- fhir-install/README-DB2.md
previously, it just said to use the "db schema tool" in the fhir-persistence-schema project; now it links to a page that will show the README of how that works
> add link to fhir-persistence-schema project

- docs/src/pages/Conformance.md
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
1. Added more search modifiers to map of allowed modifiers in
fhir-search  SearchConstants
2. Introduced a new "supportedModifiersMap" in the fhir-persistence-jdbc
layer, added a method called `checkModifiers` which checks all
QueryParameters passed to the search method
3. Updated the Conformance.md doc to state that we don't support
`:below` or `:not` modifiers for token search
> Search modifier refactoring and doc update

- fhir-search/src/main/java/com/ibm/fhir/search/parameters/QueryParameterValue.java
- fhir-search/src/main/java/com/ibm/fhir/search/uri/UriBuilder.java
I didn't realize that we were using QueryParameterValue.toString to
write the self URI for the response messages, so I added a generic
toString capability for composite values.
Now, I've updated this to return the data in a format that is consistent
with the query string value we parsed to get it.
Note: there is no known syntax for a single component within a composite
value to itself have multiple values; we'll throw an
IllegalStateException if we ever see it.
> issue #519 - QueryParameterValue.toString should use query string format

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/ColumnDefBuilder.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/Table.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/TimestampColumn.java
I added the original if logic because it was throwing a NullPointer and
I didn't understand why...now I realize it was just from "auto-boxing"
of the Integer to an int. Now I switched the parameter to type Integer
so we can remove the extra branching logic.
> Remove unnecessary complexity in db utils Table/ColumnDefBuilder

- docs/src/pages/Conformance.md
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/DateParmBehaviorUtil.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/date/DateTimeHandler.java
This PR builds on #529 and can be taken in whole or in part.
The spec says "Where both search parameters and resource element date
times do not have time zones, the servers local time zone should be
assumed" and so I wanted to see what that would look like.
Its not very clear what is "correct" if only one of those two excludes
time zones. It doesn't matter much on the parameter extraction side
because all datetimes with times in them are required to have a
timezone, but I think I like the idea of handling searches w/o timezone
info via local time, because usually if someone puts a date or datetime
without a timezone they are expecting local time and not UTC time.
In the process, I also found a discrepency between our EQ and NE
behavior. To rectify this, I removed the "exactly equals …
> issue #528 - use server timezone to interpret dates

- docs/src/pages/Conformance.md
- fhir-examples/src/main/resources/json/ibm/basic/BasicDate.json
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractPLSearchTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/date/DateTimeHandler.java
- fhir-search/src/test/java/com/ibm/fhir/search/date/DateTimeHandlerTest.java
1. added a bunch more date and datetime tests to AbstractSearchDateTest
(and reorganized some ones that were there)
2. found and fixed one problematic case:
We were capturing the precision wrong for Datetime values which include
0 seconds.  Our algorithm relied on TemporalAccessor.toString but this
method actually excludes the seconds when they are 0. This was causing
us to store values like `2019-12-31T20:00:00Z` as the range
`[2019-12-31T20:00:00Z, 2019-12-31T20:00:59.999999Z)` instead of
`[2019-12-31T20:00:00Z, 2019-12-31T20:00:00.999999Z)`. I addressed it by
using the DateTime or Date PARSER_FORMATTER (depending on its type).
3. updated BasicDate.json to test with a more "interesting"
dateTime...one that strattles the edge of a year, month, and day.
Signed-off-by: Lee Surprenant …
> issue #528 - update Conformance.md and tweak datetime precision

- docs/src/pages/Conformance.md
- fhir-core/src/main/java/com/ibm/fhir/core/FHIRUtilities.java
- fhir-examples/src/main/resources/json/ibm/basic/BasicDate.json
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FHIRDbDAOImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterVisitorBatchDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceDAOImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/DerbyResourceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dto/DateParmVal.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/DateParmBehaviorUtil.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/DateParmBehaviorUtilTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/LocationParmBehaviorUtilTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/date/DateTimeHandler.java
- fhir-search/src/test/java/com/ibm/fhir/search/date/DateTimeHandlerTest.java
also added `shutdownDatabase` placeholder in AbstractPersistenceTest
> Set timezone to UTC for all storedprocedure timestamps

- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/ParameterExtractionTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/date/DateTimeHandlerTest.java
Now the DateTimeHandler are dependent on the current timezone of the
java runtime.  On our CI environment, it must be UTC.  Now we'll set UTC
as the default timezone at the beginning of these tests so they can pass
like they used to.
> issue #528 - use UTC in DateTimeHandlerTest and ParameterExtractionTest

- fhir-model/src/main/java/com/ibm/fhir/model/resource/Resource.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Element.java
- fhir-swagger-generator/README.md
- fhir-swagger-generator/pom.xml
- fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
- fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java
- fhir-tools/src/main/java/com/ibm/fhir/tools/CodeBuilder.java
- fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java
By default, we'll now use the first `complete-mock` example for each
applicable resourceType.
In addition, I flipped this to "minimal" and used that to generate a new
version of the "all-in-one" in our `fhir-openapi` project.
> issue #536 - introduce examples to the Swagger/OpenAPI

- fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersMap.java
- fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersUtil.java
- fhir-search/src/main/java/com/ibm/fhir/search/parameters/cache/TenantSpecificSearchParameterCache.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/MultiTenantSearchParameterTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/ParametersSearchUtilTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/ParametersUtilTest.java
Previously, the parameter maps built by ParametersUtil had each
SearchParameter listed twice...once by "code" and once by "url".
This pull request introduces a new ParametersMap object that
encapsulates two separate maps and presents it as a single object.
Also removed the notion of "UNSUPPORTED_EXPRESSION" since 
4.0.1 artifacts now have valid FHIRPath and our FHIRPath engine
now supports `resolve()`.
> issue #535 - Deduplicate the SearchParameter map

- .github/workflows/build.yml
- .github/workflows/javadocs.yml
- fhir-parent/pom.xml
``` sh
JAVADOC_GOAL=""
if [ "${{ matrix.java }}" != "openjdk8" ]
then 
export JAVA_HOME=/opt/hostedtoolcache/AdoptOpenJDK/1.0.0-releases-${{ matrix.java }}-hotspot-normal-latest/x64/
JAVADOC_GOAL=" -Pvalidate-javadoc javadoc:javadoc "
fi
mvn -B ${JAVADOC_GOAL} install --file fhir-parent/pom.xml -DskipTests --no-transfer-progress -X
```
> Add Lint for the Javadocs #545

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/LocationParmBehaviorUtil.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchNearTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/LocationParmBehaviorUtilTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
- fhir-search/src/main/java/com/ibm/fhir/search/location/NearLocationHandler.java
- fhir-search/src/main/java/com/ibm/fhir/search/location/bounding/Bounding.java
- fhir-search/src/main/java/com/ibm/fhir/search/location/bounding/BoundingBox.java
- fhir-search/src/main/java/com/ibm/fhir/search/location/bounding/BoundingMissing.java
- fhir-search/src/main/java/com/ibm/fhir/search/location/bounding/BoundingRadius.java
- fhir-search/src/main/java/com/ibm/fhir/search/location/bounding/BoundingType.java
- fhir-search/src/test/java/com/ibm/fhir/search/location/BoundingTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchNearTest.java
- Add support for multiple instance of the _near parameter
- Improve AND coverage tests
- Add Bounding type for missing and corresponding support for it
- Enable Search's support of :missing
- Improve Test coverage for fhir-search-tests
> Add Positional Search (near) with :missing modifier #510

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/InclusionQuerySegmentAggregator.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/SortedQuerySegmentAggregator.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchDateTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchIdLastUpdatedTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/JDBCIncludeRevincludeTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchIdAndLastUpdatedTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractWholeSystemSearchTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractIncludeRevincludeTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/parameters/QueryParameterValue.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchAllTest.java
- Add Bind Variables to Inclusion and Sorted Query Segment Aggregators
- Verify with tests
- Whole System Search with SORT and without SORT
- Resource Specific Search with SORT and without SORT
> _id and _lastUpdated search bindvariables are not added #577

- .github/workflows/build.yml
- build/post-integration-test.ps1
- build/pre-integration-test.ps1
- build/tests.ps1
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
- fhir-persistence-schema/README.md
- fhir-server-webapp/src/main/webapp/WEB-INF/web.xml
- Remove invalid character and replace with valid encoded character
- Change to use File.separator instead of hard coded "/"
- Add pre/post integration scripts
- Add job to build.yml
> Add e2e tests for Windows #562

- docs/src/pages/Conformance.md
- fhir-tools/pom.xml
I set up a new Eclipse 2019.12 workspace and it was complaining about
our maven-plugin-plugin config in fhir-tools.  After adding the
pluginExecutionFilter that error is gone.
I also noticed some outdated info in our Conformance.md doc, so I updated that too.
> Doc fix and m2e config

- fhir-operation-validate/src/main/java/com/ibm/fhir/operation/validate/ValidateOperation.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRValidateOperationTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
Added tests to FHIRValidateOperationTest for:
* a valid vital sign observation
* a valid respiration rate observation
* an invalid heartRate observation
Also fixed the ordering of expected vs actual for existing tests.
> issue #615 - added support for the profile parameter in $validate

- fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
based on a user question about what is the behavior for
resource-asserted profiles that are unknown to the server
> add detail to FHIRValidator javadoc

- .github/workflows/release.yml
- build/release/README.md
- build/release/code-coverage.sh
- fhir-config/src/test/java/com/ibm/fhir/config/test/ConfigurationServiceTest.java
- fhir-config/src/test/java/com/ibm/fhir/config/test/FHIRConfigHelperTest.java
- fhir-config/src/test/java/com/ibm/fhir/config/test/PropertyGroupTest.java
- fhir-config/src/test/resources/fhirConfig.json
- fhir-examples/src/main/resources/ibm-json.txt
- fhir-examples/src/main/resources/ibm-xml.txt
- fhir-examples/src/main/resources/json/ibm/coverage/basic-type.json
- fhir-examples/src/main/resources/json/ibm/coverage/parameters-contactdetail.json
- fhir-examples/src/main/resources/xml/ibm/coverage/basic-type.xml
- fhir-examples/src/main/resources/xml/ibm/coverage/parameters-contactdetail.xml
- fhir-model/src/main/java/com/ibm/fhir/model/util/FHIRUtil.java
- fhir-model/src/test/java/com/ibm/fhir/model/test/ResourceCoverageTest.java
- fhir-parent/pom.xml
- Add Examples to increase Test Coverage
- parameters-contactdetail.[json/xml]
- basic-type.[json/xml]
- Add coverage for get method tests
- Update fhir-parent to use the latest jacoco plugin
- Increase code coverage of fhir-config
- Update fhir-model to remove unused FHIRUtil method
- Add a switch to turn on/off codecov.io
> Incorporate and Improve test coverage in the build/site #248

- docs/src/pages/guides/FHIRServerUsersGuide.md
$endpoint should be $healthcheck; use single quotes around the URL
> Fix healthcheck example

- fhir-path/src/main/java/com/ibm/fhir/path/function/ConformsToFunction.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/ConformsToTest.java
- fhir-validation/src/test/resources/JSON/us-core-patient.json
> Issue #662 - add logic to handle empty context for 'conformsTo' function

- .github/workflows/build.yml
- fhir-model/src/main/java/com/ibm/fhir/model/util/CollectingVisitor.java
- fhir-model/src/main/java/com/ibm/fhir/model/util/FHIRUtil.java
- fhir-model/src/main/java/com/ibm/fhir/model/util/ModelSupport.java
- fhir-model/src/main/java/com/ibm/fhir/model/util/ReferenceMappingVisitor.java
- fhir-model/src/test/java/com/ibm/fhir/model/util/test/ReferenceMappingVistorTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/Base64BinaryTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BundleTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
1. Moved ReferenceMappingVisitor from fhir-server to fhir-model and
refactored it to allow any mapping (not just UUID -> logical id)
2. Introduced FHIRUtil.createStandaloneBundle for adding resources to a
bundle and replacing internal references with bundle-local UUID values
3. Removed deprecated FHIRUtil methods and added deprecated flag to
FHIRUtil.getResourceTypeName(Resource resource)
> Refactoring and addition of FHIRUtil.createStandaloneBundle

- fhir-model/src/main/java/com/ibm/fhir/model/visitor/CopyingVisitor.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathNode.java
- fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
- fhir-path/src/main/java/com/ibm/fhir/path/patch/FHIRPathPatch.java
- fhir-path/src/main/java/com/ibm/fhir/path/patch/FHIRPathPatchAdd.java
- fhir-path/src/main/java/com/ibm/fhir/path/patch/FHIRPathPatchDelete.java
- fhir-path/src/main/java/com/ibm/fhir/path/patch/FHIRPathPatchInsert.java
- fhir-path/src/main/java/com/ibm/fhir/path/patch/FHIRPathPatchMove.java
- fhir-path/src/main/java/com/ibm/fhir/path/patch/FHIRPathPatchOperation.java
- fhir-path/src/main/java/com/ibm/fhir/path/patch/FHIRPathPatchReplace.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/AddingVisitor.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/DeletingVisitor.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/FHIRPathUtil.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/InsertingVisitor.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/MovingVisitor.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/ReplacingVisitor.java
- fhir-path/src/test/java/com/ibm/fhir/path/patch/test/FHIRPathPatchBuilderTest.java
- fhir-path/src/test/java/com/ibm/fhir/path/patch/test/FHIRPathPatchSpecTest.java
- fhir-path/src/test/java/com/ibm/fhir/path/test/FHIRPathUtilTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
Also:
1. added `toParameters()` to set up use from the client
2. removed hacky logic for retrieving the element name from a path
It turns out that our FHIRPathNode object already exposes the element
name from a selected node.
This works for all cases other than inserting an element at position 0
of an empty list, and its not clear from the spec whether that should be
supported or not. Now we throw UnsupportedOperationException in that
case.
3. reduced the visibility of all the patch visitors, added null
checks, and improved documentation of both the visitors and select
methods in the FHIRPath model.
4. fixed major issue caused by use of parent identity in the fhirpathpatch visitors
> Refactored FHIRPathPatch into builder pattern

- fhir-benchmark/src/main/java/com/ibm/fhir/benchmark/FHIRParserBenchmark.java
- fhir-benchmark/src/main/java/com/ibm/fhir/benchmark/FHIRPatchBenchmark.java
- fhir-benchmark/src/main/java/com/ibm/fhir/benchmark/FHIRPathEvaluatorBenchmark.java
- fhir-benchmark/src/main/java/com/ibm/fhir/benchmark/ObjectSizeEstimator.java
- fhir-benchmark/src/main/java/com/ibm/fhir/benchmark/util/BenchmarkUtil.java
Not a totally fair benchmark because we start with an in-memory resource, so the JSON patch has to generate, then patch, then parse.
```
Benchmark
(exampleName)   Mode  Cnt      Score   Error  Units
FHIRPatchBenchmark.benchmarkFHIRPathPatch
encounter-example-emerg  thrpt    2  11557.376          ops/s
FHIRPatchBenchmark.benchmarkJSONPatch
encounter-example-emerg  thrpt    2   1051.019          ops/s
```
> Add FHIRPatch benchmark and fix BenchmarkUtil

- fhir-server/liberty-config/config/default/fhir-server-config.json
to match the username and schema name used at fhir-persistence-schema
> update _db2_default config

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyMaster.java
- fhir-persistence-jdbc/pom.xml
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/FHIRDbDAOTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/DerbyInitializer.java
- fhir-persistence-jdbc/src/test/resources/test.jdbc.properties
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/derby/DerbyFhirDatabase.java
- fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/derby/DerbyFhirDatabaseTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractPLSearchTest.java
I found that eclipse kept "validating" the derby files in their present location, so I moved them under the target dir.
> Put test derby db under target dir

- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchTokenTest.java
R4 clarifies that booleans should not be searched with their implicit
system
> issue #353 - clean up comments in AbstractSearchTokenTest

- .github/workflows/build.yml
- README.md
- docs/src/pages/guides/FHIRServerUsersGuide.md
- docs/src/pages/index.mdx
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRPatchTest.java
* remove reference to the rc-1 zip installer from the user guide
* remove statement about how you "must" set up for development to use the server (from the site's index page)
* add a link to "setting up for development" from the README
> site and readme documentation tweaks

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
- fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
- fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/processor/impl/CosExportImpl.java
- fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/processor/impl/DummyImportExportImpl.java
- fhir-operation-document/src/main/java/com/ibm/fhir/operation/document/DocumentOperation.java
- fhir-search/src/main/java/com/ibm/fhir/search/uri/UriBuilder.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
Added config prop `fhirServer/core/originalRequestUriHeaderName` with a
default value of null.
Updated FHIRResource.getRequestUri and FHIRResource.getRequestBaseUri to
use the configured originalRequestUriHeaderName to get the original
request uri (in case proxies have rewritten the host and/or path).
Updated CosExportImpl to use
FHIROperationContext.PROPNAME_REQUEST_BASE_URI instead of
PROPNAME_URI_INFO to get the base URI.
> issue #66 - introduce originalRequestUriHeaderName prop and update uris

- fhir-audit/src/main/java/com/ibm/fhir/audit/kafka/Environment.java
- fhir-install/Dockerfile
- fhir-install/src/main/resources/scripts/install.bat
- fhir-install/src/main/resources/scripts/install.sh
- fhir-parent/pom.xml
Updated the packaged openliberty version from 19.0.0.8 to 19.0.0.12.
Also, I found that the websphere-liberty:microProfile2 tag isn't being
kept up-to-date, only websphere-liberty:kernel and
websphere-liberty:full, so I switched our Dockerfile to use
`websphere-liberty:kernel`
Finally, I reduced the log level of fhir-audit kafka/eventstreams
binding info...this message is logging our event streams credentials and
so I don't want it being logged by default.
> Update liberty version

- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
I didn't think we'd ever hit this case, but I found that we do for requests within a batch/transaction bundle.
Since those are always POSTed to the base uri, the simplest fix is to just use the requestUri as the baseUri in that case.
> fixup issue #66 for bundle requests

- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkcommon/BulkDataUtils.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkcommon/Constants.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ChunkReader.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ChunkWriter.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportJobListener.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionCollector.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionMapper.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportTransientUserData.java
- fhir-model/src/test/java/com/ibm/fhir/model/test/ResourceCoverageTest.java
currently, we enable the reuse by default, and we can turn it off if need in the future.
**Test results(using the same 34M ndjson test file):**
**From local file**
**(1) without reuse**
---- Fhir resources imported in 365.517seconds ----
ResourceType 	 Imported 	 Failed
AllergyIntolerance	54238	0
---- Total: 54238 ImportRate: 148.38707912354283 ----
**(2) with reuse**
---- Fhir resources imported in 358.754seconds ----
ResourceType 	 Imported 	 Failed
AllergyIntolerance	54238	0
---- Total: 54238 ImportRate: 151.1843770383048 ----
**From COS:**
**(1) without reuse**
---- Fhir resources imported in 517.111seconds ----
ResourceType 	 Imported 	 Failed
AllergyIntolerance	54238	0
---- Total: 54238 ImportRate: 104.8865717418504 ----
**(2) with …
> issue #726 reuse input stream of data source between chunks

- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
I must've overwritten this error message with the "unable to audit" one by mistake...
but after looking at it a bit, I don't even think we want this log message, it already gets logged in the catch near the bottom of this method.
> remove erroneous log message for conditional update/patch

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/group/ChunkReader.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/patient/ChunkReader.java
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRRequestContext.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/CompartmentParseQueryParmsTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java
- fhir-server/src/main/java/com/ibm/fhir/server/listener/FHIRServletContextListener.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
1. added originalRequestUri to FHIRRequestContext
2. set it from FHIRRestServletFilter
3. use it from FHIRResource
4. remove unused `queryString` parm from SearchUtil.parseQueryParameters
> REST layer refactoring/cleanup

- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkcommon/BulkDataUtils.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkcommon/Constants.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ChunkReader.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ChunkWriter.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportCheckPointData.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportJobListener.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionCollector.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionMapper.java
Changes:
(1) Added error handling for fhir parse exception.
(2) Added error handling and retry for https and S3 client timeout/reset exception.
(3) Increase S3 client socket timeout(without activity) to 120 seconds.
(4) Use the sum of job execution times as the job instance time when calculating rate.
(5) Skip the already processed lines after the job is restarted.
> Issue #765 #768 Bulkdata import metrics and error handling enhancements

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/api/IDatabaseAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/CommonDatabaseAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/ForeignKeyConstraint.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/Table.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceTableGroup.java
We found that the query plan was doing a full index scan of the
Observation_COMPOSITES table on each delete to each of the
Observation_X_VALUES tables. This is totally unneccessary because we
always delete the composite rows first before we delete the
corresponding X_VALUES rows. Telling Db2 not to enforce this particular
constraint should speed things up nicely.
I also found and fixed an issue where we were only generating the FK 
constraint for component 3 (comp3) of the composites tables. We added 
the FK for each component (all 3), but since we never changed the name 
it was overwriting it instead of adding it for each set of columns (i.e. components).
Also fixed javadoc in FhirResourceTableGroup by:
1. fixing copy-paste issue in addComposites javadoc
2. remove "ON DELETE CASCADE" …
> issue #781 - skip constraint checking for composite foreign keys

- build/pre-integration-test-docker.sh
- fhir-install/docker/Dockerfile-ol
Starting with the docker images for liberty 20.0.0.3, open-liberty is expecting both `/config/configDropins/defaults` and `/config/configDrops/overrides` to exist.
Since we delete the `defaultServer` and replace it with our own `fhir-server` server, we also overwrite `/config` to point at this new server.
However, the entrypoint script is expecting these directories to exist like they do for the defaultServer config.
We were already creating `/config/configDropins/defaults`; so now we just create `/config/configDrops/overrides` at the same time.
> issue #828 - create configDropins/overrides for the fhir-server

- docs/src/pages/guides/FHIRServerUsersGuide.md
Moved the "create and deploy schema" step before "configure fhir-server-config" since you need to use the generated tenantKey to complete the configuration step.
> Add information about setting the tenantKey

- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaConstants.java
> Reduce the Default Pool Size for the Schema Generator #841

- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
according to http://hl7.org/fhir/uv/bulkdata/operations/index.html, added bulkdata(export) to CapabilityStatement.
> issue #670 add bulkdata to server CapabilityStatement

- .github/workflows/build.yml
- build/db2-migration-test-docker.sh
- build/pre-integration-test-docker.sh
- build/pre-migration-test-docker.sh
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/api/IDatabaseAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/DateMath.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/DropForeignKeyConstraint.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/db2/Db2Adapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/db2/Db2GetPartitionInfo.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/db2/Db2Reorg.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/Table.java
- fhir-install/docker/copy-dependencies-db2-migration.sh
- fhir-install/docker/deploySchemaAndTenant.sh
- fhir-install/docker/updateSchema.sh
- fhir-notification-kafka/src/main/java/com/ibm/fhir/notifications/kafka/impl/FHIRNotificationKafkaPublisher.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchCompositeTest.java
- fhir-persistence-schema/deployPriorVersions.sh
- fhir-persistence-schema/docs/DB2SchemaMigration.md
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceTableGroup.java
Introduced variant of e2e-db2 test for testing migration which:
1. creates a db2 instance and deploys the previous version of the schema
2. runs migration
3. executes the e2e tests
This uncovered a couple different issues with our existing migrations:
1. `DB2 SQL Error: SQLCODE=-2310, SQLSTATE=     , SQLERRMC=-668`
while executing runstats after dropping a column
2. `DB2 SQL Error: SQLCODE=-108, SQLSTATE=42601,
SQLERRMC=FK_OBSERVATION_COMPOSITES_DATE`
while executing DropForeignKeyConstraint
3. `DB2 SQL Error: SQLCODE=-204, SQLSTATE=42704,
SQLERRMC=FK_OBSERVATION_COMPOSITES_DATE`
while executing DropForeignKeyConstraint
For number 1, the fix was to avoid executing RUNSTATS until after the
table with the dropped column has been REORGed.
For number 2, the fix was to stop qualifying the …
> issue #833 - add db2 migration test and fix issues

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/system/ChunkWriter.java
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
- fhir-core/src/main/java/com/ibm/fhir/core/FHIRConstants.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BundleTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/DeleteTest.java
- fhir-server/liberty-config/config/default/fhir-server-config-db2.json
- fhir-server/liberty-config/config/default/fhir-server-config.json
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
(1)This PR enabled fhir server to support conditional delete with multiple matches.
passed all tests including the 2 touchstone fhir-api-r4-patient-delete-03-conditional-multiple test cases which failed before.
https://touchstone.aegis.net/touchstone/scriptexecution?exec=202003301558230438592632&qn=/FHIR4-0-1-Advanced/Patient/05-delete/fhir-api-r4-patient-delete-03-conditional-multiple#WAITING_OPER
(2) This PR also added server configure "fhirserver.bulkdata.isExportPublic" to allow user to disable public access to the exported files in COS/S3.
> issue #664 #884 conditional delete multiple match support and config for disabling bulk export public access

- docs/src/pages/guides/BringYourOwnPersistence.md
1. use `com.ibm.fhir` instead of a variable in the groupIds
2. added test-jar dependency so that the fhir-persistence tests can be used
> Update maven snippet in BYOP section

- fhir-model/src/main/java/com/ibm/fhir/model/util/FHIRUtil.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-provider/src/main/java/com/ibm/fhir/provider/FHIRProvider.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BasicServerTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Delete.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
subsumes #915
1. Verified the support for return preference in create and update and
added corresponding tests under the BasicServerTest class
2. Collect and return supplemental warnings from the persistence layer
(e.g. search parameters that will be skipped)
3. Update doCreate/doUpdate to check the persistence-layer-generated supplemental
warnings and add them to the validation warnings
4. Added comments to various places in FHIRUtil where we may want to do
something similar in the future; basically wherever we throw in strict
mode but continue on in lenient mode
> issue #910 - test create warnings and add PL-generated warnings

- fhir-bulkimportexport-webapp/src/main/java/META-INF/batch-jobs/FhirBulkImportChunkJob.xml
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkcommon/BulkDataUtils.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkcommon/Constants.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ChunkWriter.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportCheckPointData.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportJobListener.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionMapper.java
Added import counts (succeeded and failures) to import javabatch job exit status.
> issue #944 add import counts to job exit status

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/FHIRPersistence.java
- fhir-server-test/src/test/java/com/ibm/fhir/cli/test/FHIRCliTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BundleTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/DeleteTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchNearTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/UpdateTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Delete.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java
While investigating the issue, I found that `delete` and `conditionalDelete` were handled subtely different.
Now the response status is set in FHIRRestHelper.doDelete() and these two variants share a common buildResponse helper.
Additionally, we were inconsistent in the response status being returned.
Previously we were returning 204 (No Content) for some deletes and 200 (OK) status for others.
Now we will always return a 200 (OK) for a successful delete and the response will always contain an OperationOutcome:
* For conditional deletes with no matches, we return a warning
* For the deletion of a previously deleted resource, we return a warning
* For the deletion of a non-existent resource, we return a warning
* For any other successful deletion (conditional or not), we return an …
> issue #930 - ensure status is never null from delete AND return 200 OK on success

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-bulkimportexport-webapp/src/main/java/META-INF/batch-jobs/FhirBulkImportChunkJob.xml
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkcommon/BulkDataUtils.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionCollector.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionMapper.java
- fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
- fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/JobExecutionResponse.java
- fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/JobInstanceRequest.java
- fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/type/JobParameter.java
- Updated the ChunkJob.xml to include missing parameters (the passed
values didn't agree)
- Add guard for null condition
- Added support for operational outcome bucket
```
{
"transactionTime": "2020-04-25T20:35:50.699-04:00",
"request": "$import",
"requiresAccessToken": false,
"output": [
{
"type": "OperationOutcome",
"url": "test-import.ndjson_oo_success.ndjson",
"count": 3
}
],
"error": [
{
"type": "OperationOutcome",
"url": "test-import.ndjson_oo_errors.ndjson",
"count": 0
}
]
}```
> BulkData $import API improvement - Exit Status #949

- fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
- fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/processor/impl/CosExportImpl.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/ImportOperationTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Operation.java
- Update REST Operation with method DELETE (takes no content)
- Improved the ImportOperationTest
- Update CosExportImpl
- Improve error conditions of DELETE support for the Java Batch
Framework
I executed the QA using injected code into the Import operation to test the behaviors and error conditions, as this could introduce risk in the resulting code I removed before I checked in.
> BulkData $bulkdata-status DELETE API must stop first #952

- fhir-server-webapp/src/main/webapp/WEB-INF/web.xml
- fhir-server/liberty-config/configDropins/disabled/jwtRP.xml
- fhir-server/liberty-config/configDropins/disabled/oauthResourceServer.xml
- fhir-server/liberty-config/configDropins/disabled/oidcProvider.xml
- fhir-server/liberty-config/server.xml
- fhir-server/pom.xml
- fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRHttpServletRequestWrapper.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Batch.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Create.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Delete.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/History.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Operation.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Patch.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Read.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Search.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Update.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/VRead.java
1. Move webapp security info into `RolesAllowed` annotations on a per-JAXRS-resource basis and make the `metadata` and `.well-known/smart-configuration` endpoints open by default
2. Introduce jwtRP.xml as a new configDropin alternative to oauthResourceServer which
can be used to introspect jwt tokens that are passed to the server for
introspecting scopes and making authorization decisions
3. Re-introduce `singleSignonEnabled="false"` on the
default server.xml and override this setting within the
`oidcProvider.xml` dropin
> Move to @RolesAllowed security, update server config, and introduce jwtRP.xml

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceDAOImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/DerbyResourceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgresql/PostgreSqlParameterNamesDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgresql/PostgreSqlResourceDAO.java
The small enhancement is to query ResourceTypesCache first, if no found, then query the local MAP, this will help to avoid at least (batch size -1) query to the database.
> issue #1007 minor enhancement to resourceTypesCache

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-install/pom.xml
- fhir-install/src/main/assembly/distribution.xml
- fhir-install/src/main/resources/scripts/install-fhir.sh
- fhir-install/src/main/resources/scripts/install.bat
- fhir-install/src/main/resources/scripts/install.sh
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceDAOImpl.java
- fhir-server-webapp/pom.xml
Instead of packaging them in the fhir-server-webapp war, now we place
them in a userlib dir and the server will discover them from there.
I also performed some path simplification on the install scripts.
We used to create the install files at `/fhir/server/usr/*` but, since
we no longer package the fhir-client or the cli utilities in the
distribution, there's really no need to have these 3 levels.
Finally, I moved the docs (which have a single README which now points
at our website) into the fhir-server directory.
> issue #1005 - move ig jars to userlib dir

- fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
Proposed change to remove the word "failed" from the warnings for preferred and extensible bindings.
> Minor change to valueset membership warning

- fhir-registry/src/main/java/com/ibm/fhir/registry/util/PackageRegistryResourceProvider.java
- fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java
ConfigHelper pulls the tenantId and dsId from the threadlocal, so we
can't use that to lookup tenant-specific config until after its set.
> issue #1032 - set FHIRRequestContext threadlocal before using ConfigHelper

- fhir-install/src/main/assembly/distribution.xml
- fhir-install/src/main/resources/scripts/install-fhir.sh
- fhir-install/src/main/resources/scripts/install.bat
- fhir-install/src/main/resources/scripts/install.sh
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/MockPersistenceFactory.java
- fhir-server/liberty-config/configDropins/disabled/cloud.xml
to avoid the need for writing logic to prevent the installer from
recusively copying its files to itself in perpetuum
> issue #1039 - move fhir-server artifacts under subdirectory in distribution zip

- fhir-core/src/main/java/com/ibm/fhir/core/FHIRConstants.java
- fhir-core/src/main/java/com/ibm/fhir/core/context/FHIRPagingContext.java
- fhir-core/src/main/java/com/ibm/fhir/core/context/impl/FHIRPagingContextImpl.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-server-test/src/test/java/testng.xml
- fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRHttpServletRequestWrapper.java
1. added PrettyServerFormatTest to testng.xml
2. moved "general parameter" parameter names to FHIRConstants in `fhir-core`
and update SearchUtil; this fixes #1052 
3. added javadoc to the FHIRPagingContext interface
> issue #1052 - ignore non-return parameter "general parameters" in search

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyMaster.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyServerPropertiesMgr.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/DerbyBootstrapper.java
- fhir-server/src/main/java/com/ibm/fhir/server/listener/FHIRServletContextListener.java
Addresses lock contention with verification of the number of sequence numbers preallocated for each database instance using a callable system stored procedure for derby only.
> Sequence Lock Contention on Apache Derby #1038

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgresql/PostgreSqlAdapter.java
- fhir-persistence-schema/src/main/resources/add_any_resource_postgresql.sql
To achieve better update performance:
-Updated add_any_resource function for postgresql to use "no key update";
-Updated postgresqladapter to disable the constrains for composites.
Per tests, the first change improved the updates of observations from only about 3/second to more than 33/second; and the second change further improved the performance to about 60/second, almost the same as importing new resources.
> issue #1061 fixes for improving postgresql update performance

- fhir-registry/src/main/java/com/ibm/fhir/registry/util/FHIRRegistryUtil.java
- fhir-registry/src/main/java/com/ibm/fhir/registry/util/Index.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/ValidationProcessor.java
Also, this PR updates the NullPointerExceptions to include the name of
the field that is missing.  I think we should consider doing that for
all uses of Objects.nonNull across the model.
> Skip index entries that are missing required fields instead of throwing

- fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Removes an extra space from one and adds a missing one to the other.
Also small cleanup in FHIRRestServletFilter since request and response
are now always of the Http variant.
> Minor message fixes

- fhir-ig-davinci-pdex-plan-net/pom.xml
- fhir-model/src/main/java/com/ibm/fhir/model/type/Element.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
- fhir-registry/src/main/java/com/ibm/fhir/registry/util/PackageRegistryResourceProvider.java
- fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java
While testing with the DaVinci PDEX Plan-Net we noticed that some of the
search parameters weren't getting indexed.
Upon further inspection, it was because the expression led to an
Extension element and not the value of that extension.
I'm still not sure what is "best practice" but I found that the
`mothersMaidenName` search parameter from the base spec has the same
issue and so I think its good for us to handle this.
> When searchparameter expression resolves to extension element, use value

- docs/src/pages/guides/FHIRServerUsersGuide.md
Fhir User Guide has incorrect jar location mentioned to keep custom interceptors jar for Persistence interceptors.
Steps to reproduce the behavior:
Go to 'https://ibm.github.io/FHIR/guides/FHIRServerUsersGuide/#432-implementing-a-persistence-interceptor'
Under 4.3.2 Implementing a persistence interceptor step 3, Copy your jar to the <WLP_HOME>/usr/servers/fhir-server/config. This path should be <WLP_HOME>/usr/servers/fhir-server/userlib
> Replace /config to /userlib

- fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
- fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java
Bruno reported that he's still seeing a "MAX DEPTH" issue in the examples generated by IBM API Connect...this was supposed to have been fixed by https://github.com/IBM/FHIR/pull/863 but I think I know why it didn't work...
Bruno to confirm ASAP so we can possibly try squeezing this in for 4.2.2.
Additionally, I moved the list of required fields for each object down one level in the hierarchy as requested by a potential user of the tool.
> Minor swagger definition changes

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/DeleteTest.java
Previously, this test was over-zealously deleting Observations it didn't
create.
Now it should be much more self-contained and more consistent: it always
tests both multi-delete scenarios (result <= max & result > max).
> Update DeleteTest to be more self-contained

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/common/CheckPointAlgorithm.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/system/ChunkWriter.java
Changed these following bulkdata configurations to tenant specific:
- fhirServer/bulkdata/isExportPublic
- fhirServer/bulkdata/cosFileMaxResources
- fhirServer/bulkdata/cosFileMaxSize
> issue #943 change isExportPublic etc to tenant specific

- fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/USCoreEthnicityExtensionTest.java
- fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/USCoreRaceExtensionTest.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/code/DataAbsentReason.java
- fhir-model/src/main/java/com/ibm/fhir/model/util/FHIRUtil.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
- fhir-path/src/test/java/com/ibm/fhir/path/test/MemberOfFunctionTest.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/provider/DefaultTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/util/FHIRTermServiceUtil.java
- fhir-term/src/main/java/com/ibm/fhir/term/spi/ExpansionParameters.java
- fhir-term/src/main/java/com/ibm/fhir/term/spi/FHIRTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/spi/LookupOutcome.java
- fhir-term/src/main/java/com/ibm/fhir/term/spi/LookupParameters.java
- fhir-term/src/main/java/com/ibm/fhir/term/spi/TranslationOutcome.java
- fhir-term/src/main/java/com/ibm/fhir/term/spi/TranslationParameters.java
- fhir-term/src/main/java/com/ibm/fhir/term/spi/ValidationOutcome.java
- fhir-term/src/main/java/com/ibm/fhir/term/spi/ValidationParameters.java
- fhir-term/src/test/java/com/ibm/fhir/term/service/test/FHIRTermServiceTest.java
- fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/BodyWeightProfileTest.java
This PR contains changes to the `FHIRTermServiceProvider` interface including the introduction of various `Parameters` and `Outcome` classes that can be converted to/from a Parameters resource for compatibility with the operations framework.
> Issue #1168 - default term service provider enhancements / refinements

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-bulkimportexport-webapp/src/main/java/META-INF/batch-jobs/FhirBulkExportGroupChunkJob.xml
- fhir-bulkimportexport-webapp/src/main/java/META-INF/batch-jobs/FhirBulkExportPatientChunkJob.xml
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkcommon/Constants.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/common/CheckPointUserData.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/common/TransientUserData.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/group/ChunkReader.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/patient/ChunkReader.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/system/ChunkReader.java
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/system/ChunkWriter.java
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
Changes for patient/group export:
(1) Added config fhirServer/bulkdata/patientExportPageSize to control search page size.
(2) Changed the checkpoint algorithm from custom to 1 item (one search page).
(3) Added lastWritePageNum to checkpointdata to allow the job to restart from the last written page if the job is stopped and restarted.  
> issue #1187 fix for DB connection timeout issue of patient export

- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/patient/ChunkReader.java
Performance enhancement:
changed to get resources for the whole page of patients in one query for each compartment search criteria instead of do compartment search for the resource type patient by patient.
According to the test results, this has improved the export performance by more than 10 times.
> issue #1198 performance enhancement for patient/group export

- fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersMap.java
- fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersUtil.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/MultiTenantSearchParameterTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/ParametersSearchUtilTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/ParametersUtilTest.java
I found that we were adding the Resource-level SearchParameters in two
different places and this was causing some inconsistent behavior.
In this option, I stop adding the Resource search parameters in
ParametersUtil and instead update the methods in SearchUtil to ensure
that these parameters are handled properly.
Also: removes redundant `getApplicableSearchParametersMap(resourceType)`
in favor of `getSearchParameter()` calls which eventually reach
`getSearchParameterByCodeIfPresent()`.
> issue #1237 - stop double-adding inhereted searchparameters

- fhir-examples/src/main/resources/performance-json.txt
- fhir-examples/src/main/resources/spec-json.txt
This example is valid to the core spec but invalid to the US Core IG and
we're not equipped to handle examples like this just yet.
> removed problematic example from indices

- fhir-audit/src/main/java/com/ibm/fhir/audit/logging/impl/WhcAuditCadfLogService.java
Fixed:
- Enabled CADF logging not only for operations, but also for all other CRUD etc requests. 
> issue #1247 Enable CADFlog for all requests in addition to operations

- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/ParametersSearchUtilTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
In https://github.com/IBM/FHIR/pull/1238 I introduced a conflict check
for the ParametersMap, but this is only constructed on a
per-resource-type basis.
With this change, we will now detect conflicts where the same code is
defined for both a specific resource type and the more generic
"Resource" type as well.
> issue #1257 - handle codes which conflict across resource types

- fhir-model/src/main/java/com/ibm/fhir/model/util/ValidationSupport.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
1. Use the code value instead of the code object in the warning message;
this should be safe because code is a required element on
SearchParameter
2. Stop adding Resource parameters to the Resource datatype, which was
leading to invalid warnings like this:
```
Detected conflict for code ... code is defined for both Resource and
Resource; using Resource
```
Also included a random cleanup item in ValidationSupport that I had lying around.
> Improve handling of cross-resource-type searchparam code conflicts

- fhir-config/src/main/java/com/ibm/fhir/config/DefaultFHIRConfigProvider.java
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfigProvider.java
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRRequestContext.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/connection/SetTenantAction.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/Main.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesProcessor.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/TestFHIRConfigProvider.java
This change permits the R4 examples JDBC Main to run against DB2 databases without requiring a fhir-server-config.json file to be defined with the tenantKey (which in this case is provided as a command-line argument). This change follows on from a previous change which moved the tenantKey out of the FHIRRequestContext.
This change also now removes the tenantKey property from the FHIRRequestContext, which had previously been marked as deprecated.
> Issue 1122 remove tenantKey from request context and support tenantKey without requiring fhir-server-config files

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/api/IDatabaseAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/CommonDatabaseAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/AlterTableIdentityCache.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/DataModelVisitor.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/DataModelVisitorBase.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgresql/PostgreSqlAdapter.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceDAOImpl.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceTableGroup.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaConstants.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaVersion.java
- fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/derby/DerbyMigrationTest.java
Addresses Db2 performance concerns with high concurrency causing contention on sequences used to support parameter table row_id identity columns.
Closing #1341.
> issue #1341 use larger cache for identity sequences in Db2

- .github/workflows/build.yml
- build/docker/updateSchema.sh
- fhir-persistence-schema/README.md
Db2 automation is timing out frequently.  I found that the alter statements were taking a long time with a small default poolsize.  Increasing to 5 limited the time spent, and moving to 10 and then 20 really sped it up. (30 min to 15 min and then 15 seconds)
> Increase Poolsize to speed up automation

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/LogicalIdentityProvider.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/TimestampPrefixedUUID.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/TimestampPrefixedUUIDTest.java
> issue 1362 Use timestamp prefix for identity strings to reduce random reads during ingestion

- fhir-server/liberty-config/configDropins/defaults/bulkdata.xml
- fhir-server/liberty-config/server.xml
By giving this element an id, we make it much simpler to override the default.
Without this, I was seeing intermittent behavior where sometimes it would use the group defined in server.xml and sometimes it would use the group defined in my override (seemingly at random).
> Add id to webApplication/application-bnd/security-role/group

- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/processor/BulkDataFactory.java
this should avoid the unnexpected NPE
also removed references to bulkdata.json since that config has been moved to fhir-server-config
> use String.equals instead of String.compareTo == 0

- fhir-model/src/main/java/com/ibm/fhir/model/util/FHIRUtil.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
> Fix javadoc and parameter name and add warning to FHIRUtil.getRandomKey

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/LocationParmBehaviorUtilTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/PopulateStaticTablesDerbyTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchIdAndLastUpdatedTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchChainTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchLastUpdatedIdTest.java
- FHIRPersistenceJDBCImpl filters the codes in the
extractParameterValues step and keeps the parameter values from hitting
the corresponding tables
URL
`https://localhost:9443/fhir-server/api/v4/Procedure?_count=10&subject:Patient._id=173a1657ba3-b9399454-1c17-4b96-9665-6cb930bc9c36&_page=1`
GENERATES SQL
`SELECT R.RESOURCE_ID, R.LOGICAL_RESOURCE_ID, R.VERSION_ID, R.LAST_UPDATED, R.IS_DELETED, R.DATA, LR.LOGICAL_ID  FROM PROCEDURE_RESOURCES R JOIN (SELECT DISTINCT LR.LOGICAL_RESOURCE_ID, LR.LOGICAL_ID, LR.CURRENT_RESOURCE_ID FROM Procedure_LOGICAL_RESOURCES LR  JOIN Procedure_RESOURCES R ON R.LOGICAL_RESOURCE_ID = LR.LOGICAL_RESOURCE_ID   AND R.RESOURCE_ID = LR.CURRENT_RESOURCE_ID   AND R.IS_DELETED <> 'Y'  JOIN Procedure_STR_VALUES  AS param0 ON (param0.PARAMETER_NAME_ID=1396 AND …
> Resolves Search Issues #1383 #1384 #1388

- docs/src/pages/Conformance.md
- fhir-model/src/main/java/com/ibm/fhir/model/resource/Resource.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Element.java
- fhir-model/src/main/java/com/ibm/fhir/model/util/FHIRUtil.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchDateTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchNumberTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchQuantityTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchReferenceTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchStringTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchTokenTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchURITest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCWholeSystemSearchTest.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/exception/FHIRPersistenceNotSupportedException.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchNumberTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchQuantityTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchReferenceTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchStringTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchTokenTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchURITest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractWholeSystemSearchTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/parameters/QueryParameter.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/IssueTypeToHttpStatusMapper.java
- fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java
1. uncomment the chained_missing search tests from the fhir-persistence module
2. update FHIRPersistenceJDBCImpl.checkModifiers to throw a FHIRPersistenceNotSupportedException for chained params with a modifier
3. override these search tests in the fhir-persistence-jdbc concrete subtypes and add an exception expectation
separately, i found and opened issue #1415, documented the current limitation, and made a similar "fix":
4. add a search test to AbstractWholeSystemSearchTest
5. update FHIRPersistenceJDBCImpl.checkModifiers to throw a FHIRPersistenceNotSupportedException for whole-system search params with the missing modifier
6. override that search test in JDBCWholeSystemSearchTest to expect that exception
finally,
7. added javadoc for Element.is (and Resource.is)
8. added issue of type …
> Issue 1413 - improve error response for unsupported modifiers

- conformance/fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/USCoreEthnicityExtensionTest.java
- conformance/fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/USCoreRaceExtensionTest.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/ConformsToFunction.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/MaxValueSetTest.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/ProfileConstraintTest.java
An alternative to #1465
Previously, we added supplemental issues with a Severity of ERROR when
the conformance check failed.
However, we also return false in these cases and so it should be the
caller's responsibility to determine if that will result in an error or
not.
Instead, the detail in these supplemental issues is really just extra
information about the failed conformance check and thus these now have a
severity of "information".
> issue #1452 - reduce severity of supplemental issues in conformsTo

- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathElementNode.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathQuantityNode.java
- fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/FHIRPathUtil.java
- fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
1. add "left.isEmpty() check to `in` operator
2. rename isComparableTo to validateEqualityOperands and move to private
method
3. added else clauses in constraintgenerator to workaround carin BB
issues
4. some formatting changes
> Miscelaneous edits to fhirpath and conformance classes

- fhir-model/src/main/java/com/ibm/fhir/model/type/DateTime.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Instant.java
- fhir-model/src/main/java/com/ibm/fhir/model/type/Time.java
- fhir-model/src/main/java/com/ibm/fhir/model/util/ModelSupport.java
- fhir-model/src/test/java/com/ibm/fhir/model/test/DateTimeTest.java
- fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java
> Issue #1446 - enable parsing dateTime fractional seconds up to 9 digits

- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/date/DateTimeHandler.java
- fhir-search/src/test/java/com/ibm/fhir/search/date/DateTimeHandlerTest.java
> Issue #1505 - enable parsing date fractional seconds up to 9 digits

- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathDateTimeValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathTimeValue.java
- fhir-path/src/test/java/com/ibm/fhir/path/test/DateTimeComparisonTest.java
> Issue #1506 - enable parsing dateTime fractional seconds up to 9 digits

- conformance/fhir-ig-davinci-pdex-plan-net/src/main/java/com/ibm/fhir/ig/davinci/pdex/plan/net/util/IndexGenerator.java
- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
- fhir-config/src/main/java/com/ibm/fhir/config/PropertyGroup.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
- fhir-server/liberty-config/config/default/fhir-server-config.json
- fhir-server/liberty-config/server.xml
- fhir-server/src/main/java/com/ibm/fhir/server/FHIRApplication.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/WellKnown.java
1. combine our existing "oauth" and "authFilter" fhir-server-config property groups into a single new group called "security".
2. introduce new properties like:
* fhirServer/security/basic (enabled by default)
* fhirServer/security/cert (enabled by default)
* fhirServer/security/smart (disabled by default, with customizable endpoints and scopes)
* fhirServer/security/cors (default=true)
3. use these values to populate `CapabilityStatement.rest.security`
* only serve up the Oauth extensions in the CapabilityStatement when fhirServer/security/service is set to `OAuth` or `SMART-on-FHIR`
4. only serve up the `.well-known/smart-capabilities` endpoint when fhirServer/security/service is set to `SMART-on-FHIR`
> issue #1480 - introduce new fhir-server-config security group and use

- fhir-config/pom.xml
- fhir-config/src/main/java/com/ibm/fhir/config/ConfigurationService.java
- fhir-config/src/test/java/com/ibm/fhir/config/test/ConfigurationServiceTest.java
- fhir-config/src/test/resources/fhirConfig.json
Use Apache Commons Text’s StringSubstitutor in ConfigurationService’s loadConfiguration method to replace variables in JSON configuration files with the values of the respective envirnoment variables.
> issue-1517 - Support for variables in JSON configuration files like 'fhir-server-config.json'

- docs/src/pages/guides/FHIRServerUsersGuide.md
Updated FHIR Server Users Guide to add documentation for what is logged in CADF audit event log.
> issue #1531 - Improve CADF audit event log documentation

- performance/fhir-meter/README.md
- performance/fhir-meter/searchTest.jmx
Detail: This is the initial delivery of the fhir-meter project
containing a readme and a JMeter test plan.  The test plan is for
searching a FHIR server with preloaded resources where you can get a
list of resource ID's into a CSV file before you run the test.  This is
meant to add load to the server through JMeter load testing.
Signed-off-by: Dag O. Roppe <roppe@us.ibm.com>
> issue #1508 - Initial delivery of fhir-meter project

- fhir-server/liberty-config/config/default/fhir-server-config.json
this is how we advertise support for SMART’s OpenID Connect profile
> add single smart capability to the default list

- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/SearchParameterRestrictionTest.java
- fhir-search/src/test/resources/config/default/fhir-server-config.json
- fhir-search/src/test/resources/config/tenant1/fhir-server-config.json
- fhir-search/src/test/resources/config/tenant2/fhir-server-config.json
- fhir-search/src/test/resources/config/tenant4/fhir-server-config.json
- fhir-search/src/test/resources/config/tenant5/fhir-server-config.json
- fhir-search/src/test/resources/config/tenant6/fhir-server-config.json
- fhir-search/src/test/resources/config/tenant7/extension-search-parameters.json
- fhir-search/src/test/resources/config/tenant7/fhir-server-config.json
- fhir-server/liberty-config-tenants/config/tenant1/fhir-server-config.json
This update enables checking of SearchParameter search restrictions and updates the FHIR server config file with a resources group that will provide configuration for additional search restrictions. Checking of required search parameters, includes, and revincludes will be in an upcoming commit.
> issue #1351 - Check SearchParameter search restrictions

- performance/fhir-meter/searchTest.jmx
Detail:  The original location of copyright caused the copyright to
disappear from the file as soon as it was saved once.  Now the copyright
is in a statement comment, so part of the first 2 statements in the
JMeter Test Plan.
Added additional simple searches on patient for different resource
types.
Signed-off-by: Dag O. Roppe <roppe@us.ibm.com>
> issue #1598 - Change location of copyright and additional simple search

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/resources/config/tenant1/fhir-server-config.json
- fhir-search/src/test/resources/config/tenant4/fhir-server-config.json
- fhir-search/src/test/resources/config/tenant5/fhir-server-config.json
- fhir-search/src/test/resources/config/tenant7/fhir-server-config.json
- fhir-server/liberty-config-tenants/config/tenant1/fhir-server-config.json
- fhir-server/src/test/resources/config/smart-enabled/fhir-server-config.json
Initially we made each searchParameter its own object so that we could
add additional properties for issue #1351.
However, now we don't think that any additional fields are needed and so
we can simplify the config to be a simple map of SearchParameter  code
-> SearchParameter.url
This format will give us the flexibility of overriding a SearchParameter
code for a given resource type for a given deploy. However, currently
the code from the config is not used...it will only use the url and it
will auto-resolve any conflicting codes.
> issue #1272 - simplify searchParameter configuration

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/CommonDatabaseAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgresql/PostgreSqlAdapter.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgresql/PostgreSqlTranslator.java
- fhir-persistence-schema/README.md
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/util/CommonUtil.java
Previously, if `--drop-schema` was used without `--drop-schema-fhir`, `--drop-schema-oauth`, or `--drop-schema-jbatch` then it completed with success without actually doing anything.
I think what happened is that we were debating two different options for these args:
A. passing some kind of argument to `--drop-schema`, so it might be like `--drop-schema fhir` or `--drop-schema oauth jbatch`; or
B. using explicit flags for dropping the fhir, schema, or oauth tables, so usage would be like `--drop-schema-fhir --drop-schema-oauth`
But somehow we ended up with a combination of the two which I hope we can all agree is not very good.
This pull request modifies the current behavior and turns it into option B, removing support for the `--drop-schema` action.
Note: this PR does *not* actually …
> DropSchema related changes for issue #1595

- docs/package.json
fix: site unable to compile due to invalid export variable in a recent gatsby-remark-plugin update
The invalid update was about 4 hours ago, I locked in the version in package.json
> fix: site unable to compile due to invalid export variable in a recent gatsby-remark-plugin update

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
- fhir-search/src/main/java/com/ibm/fhir/search/exception/SearchExceptionUtil.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/SearchParameterRestrictionTest.java
- fhir-search/src/test/resources/config/tenant7/fhir-server-config.json
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/CapabilitiesTest.java
- fhir-server/src/test/resources/config/empty/fhir-server-config.json
- fhir-server/src/test/resources/config/smart-enabled/fhir-server-config.json
Update the supported _include values, _revinclude values, and search parameter combinations to be configurable.
> issue #1351 - Check _include and _revinclude values are supported

- fhir-bucket/.gitignore
- fhir-bucket/README.md
- fhir-bucket/derby.properties
- fhir-bucket/src/main/java/com/ibm/fhir/bucket/client/ClientPropertyAdapter.java
- fhir-bucket/src/main/java/com/ibm/fhir/bucket/client/FHIRBucketClient.java
- fhir-persistence-schema/.gitignore
Omitting the truststore will result in the client using the default java
cacerts truststore which works will any of our cloud deploys.
I also allowed my editor to apply the "remove trailing whitespace"
action
> Add postgres.properties template to README and allow users to omit fhir truststore

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
Note: I'm opening this PR against Mike's branch for #1218 instead of master because I was already under that branch when I made the change.  If needed, I can cherry-pick it into a new branch off master, but my assumption is that we'll merge Mike's PR soon anyway and so it doesn't matter much.
Previously, we used a default sort of RESOURCE_ID ASC (the row identifier of the resource version being returned).
While investigating #1673, I noticed that removing this sort took this query from 10 seconds down to 3-4 seconds.
However, having *some* sort order is important, so that we get consistent page results.
Upon further inspection, I found that changing the default sort to LOGICAL_RESOURCE_ID (the row identifier of the logical resource row being returned)
yielded a similar performance boost …
> issue #1673 - change default ordering for resource searches

- fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersMap.java
This allows it to be re-used in other places, which is especially useful
for the logic within ParametersMap.insert for detecting search code and
parameter definition url conflicts.
> Expand visibility for ParametersMap

- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
To avoid advertising support for us-core-client without requiring us
from removing that CapabilityStatement from our packaging of us-core
> Add filtering logic in Capabilities.buildInstantiates

- fhir-install/Dockerfile
> fix: labels are incorrect due to base image being from open-=libery and need to be overridden

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
The `R.LOGICAL_RESOURCE_ID = LR.LOGICAL_RESOURCE_ID` part of this join
is unnecessary because R.RESOURCE_ID is the unique identifier on the
Resources (R) table...so if LR.CURRENT_RESOURCE_ID = R.RESOURCE_ID then
this RESOURCES row will always have a LOGICAL_RESOURCE_ID which matches
the LOGICAL_RESOURCES row.
Making this change changed the processing results of the following query
from over 5 minutes down to under 1 second on my postgresql db with
~30,000 patients and ~300,000 conditions:
`GET [base]/Patient?_has:Condition:patient:code=http://snomed.info/sct|44054006`
> issue #1705 - simplified top-level join avoids bad postgresql plan for simple _has queries

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceDAOImpl.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaConstants.java
- fhir-persistence-schema/src/main/resources/db2/add_any_resource.sql
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/db2/LargeResourceTest.java
This error is only on the Db2 and isolated to the Db2 stored procedure - add_any_resource.
Scenario
- Load a Bundle with multiple if not hundreds of resources in a simultaneous way within a single Connection
- Note, the Bundle can be set as Transaction or Batch.
- Db2 with 8GB of memory without INSTANCE_MEMORY=Automatic
- The simultaneous load with ~10 to 20 threads.
- The result is *SQL0930N There is not enough storage available to process the statement*.
I monitored the db2 memory under load using db2tmrk, db2pd and generated some tests which indicate the following is accurate (other memory expands to about 600GB). 
In the underlying Memory Allocation, the 2GB size cause a block of memory to be reserved, where it accumulates. So if a new large request comes up requiring substantial …
> Private Memory on Db2 results in -930 errors at load #1527

- performance/fhir-meter/searchTest.jmx
Detail: The tests numbered from 201 - 239 are tests to cover issue 676
these tests will run in the same framework.
Test focuses on:
whole-system search
chaining/reverse chaining(_has)
include/reverse include
compartment search
Signed-off-by: Dag O. Roppe <roppe@us.ibm.com>
> issue #676 - delivery of tests related to issue 676

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-bulkimportexport-webapp/src/main/java/META-INF/batch-jobs/FhirBulkExportChunkJob.xml
- fhir-bulkimportexport-webapp/src/main/java/META-INF/batch-jobs/FhirBulkExportGroupChunkJob.xml
- fhir-bulkimportexport-webapp/src/main/java/META-INF/batch-jobs/FhirBulkExportPatientChunkJob.xml
- fhir-bulkimportexport-webapp/src/main/java/META-INF/batch-jobs/FhirBulkImportChunkJob.xml
- fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/jbatch/bulkdata/common/Constants.java
- fhir-server/liberty-config/config/default/fhir-server-config-db2.json
- fhir-server/liberty-config/config/default/fhir-server-config-postgresql.json
- fhir-server/liberty-config/config/default/fhir-server-config.json
- fhir-tools/src/main/resources/.gitignore
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/BulkDataConfigUtil.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/JobExecutionResponse.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/JobInstanceRequest.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/type/JobParameter.java
- operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/model/BulkExportJobRestTest.java
- operation/fhir-operation-bulkdata/src/test/resources/testdata/config/default/fhir-server-config.json
When running on VPC, the cos URL used by the application should be the
"direct" one.  However, we still need to use the "public" one for the
donwload urls in the final response.
> Split COS endpointurl into internal and external

- fhir-persistence-schema/docs/DropTenant.md
Updated from --remove-tenant-meta to --delete-tenant-meta to reflect the actual flag in the CLI interface.
> Corrected the command flag for tenant name reuse step

- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
- issue updating the stored procedure and function
- Verify the signature of the postgres procedure/function
```
SELECT md5(prosrc),proname FROM pg_proc WHERE proname =
'add_any_resource';
```
> fix: postgres/db2 refresh of the stored procedure

- fhir-provider/src/main/java/com/ibm/fhir/provider/FHIRProvider.java
- encode the error messages from FHIRProvider with Encode.forHtml #1785
> fix: encode the error messages from FHIRProvider with Encode.forHtml

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/db2/Db2ResourceReferenceDAO.java
- fhir-persistence-schema/README.md
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
Also includes fixes for:
#1787 - incorrect classname in logger
#1790 - FHIR_ADMIN.TENANTS should enforce uniqueness for tenant schema name
> issue #1789 refresh-tenants does not handle Db2 multi-tenant/multi-schema scenarios

- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java
This prevents us from leaking information about what patient resources
exist / don't exist on the system, which was deemed useful in case an
implementer uses sensitive data for the Resource.id of the Patient
resources (which still isn't advised).
> Prevent unauthorized access to Patient resource before it happens

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/CarinBlueButtonTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/DavinciDrugFormularyTest.java
> fix: it tests were not running for drug formulary and c4bb

- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/SearchParameterRestrictionTest.java
- fhir-search/src/test/resources/config/tenant7/fhir-server-config.json
The validity checking of the _include and _revinclude parameters has been updated so if the configuration value does not specify a target resource type, then the parameter value only needs to match on its first two components (regardless of target resource type specified).
> issue #1739 - Update _include and _revinclude parameter checking

- conformance/fhir-ig-davinci-hrex/CHANGELOG.md
- conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/package/.index.json
Warning about invalid entry when discovering HREX profile. 
An example snuck into the .index.json. 
Fixes this warning on startup
fhir-server_1  | [WARNING ] Skipping index entry 2 due to one or more missing required fields, beginning with: url
> HREX - Update .index.json

- fhir-path/src/test/java/com/ibm/fhir/path/test/BetweenFunctionTest.java
> fix: test that doesn't account for year shifts

- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/type/JobParameter.java
- Removed the duplicate serialization of the fhir.dataSourcesInfo
closes #1855 
> Duplicate Job Parameters fhir.dataSourcesInfo are created #1855

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/FHIRPersistenceJDBCFactory.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/cache/FHIRPersistenceJDBCTenantCache.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/helper/FHIRPersistenceHelper.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/PersistenceLayerServerTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java
- Disambiguates the Error Messages that are bubbled up through the
Persistence Layer
- Add Integration Test
Closes #1792 
> Confusing error when request is targetted for an invalid tenant id #1792

- fhir-server/liberty-config-tenants/config/tenant1/fhir-server-config.json
USCore-specific functionality should be tested as part of our profile tests
> Remove inadvertent dependency on us-core from our base SearchTest

- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
If `useStoredCompartmentParam` is set to true, then we shouldn't need the compartment inclusion parameters to be externally visible.
> Make the 'compartment param not found' warning conditional

- fhir-model/src/test/java/com/ibm/fhir/model/test/TestUtil.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/ReferenceUtil.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/ReferenceValue.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/MockPersistenceImpl.java
- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/MockPersistenceImpl.java
For search, skip compartment checking; direct Provenance search is already scoped to the patient compartment
and for revincluded Provenance we will let the access to the targeted resources carry the day.
For direct access (read/vread/history) we will read the targets of the Provenance and allow the access if the user
has access to one or more of them.
Additionally, I beefed up the javadoc for
ReferenceUtil.createReferenceValueFrom and ReferenceValue from
fhir-search since I had to study them to use them.
Finally, I added a variant of TestUtil.getMinimalResource which doesn't
force the Format argument (which is almost never relevant).
> issue #1881 - add logic to allow reading of provenance resources

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/DateParmBehaviorUtil.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/DateParmBehaviorUtilTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
- fhir-server-test/src/test/resources/testdata/CarePlan.json
Fixed the search approximate prefix, ap, to find partial range overlaps instead of complete range overlaps.
> Issue #1877 - Fix search ap prefix to find partial range overlaps

- fhir-search/src/main/java/com/ibm/fhir/search/uri/UriBuilder.java
- fhir-search/src/test/java/com/ibm/fhir/search/uri/test/UriTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
Fixes extraneous '&' characters in compartment search response links.
> Issue #1870 - Fix extraneous '&' in compartment search response links

- fhir-bucket/README.md
1. use consistent styling on the `--` params at the end.
2. clarify the behavior of passing a date with no time for tstamp
> minor fhir-bucket readme updates

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/ReadTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Updated read to support the _elements search parameter, and return an error when invalid search parameters are used.
> Issue #1661 - Read returns error when invalid search parameters used

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/VReadTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/operation/spi/FHIRResourceHelpers.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/VRead.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/processor/DummyImportExportImplTest.java
Updated vread to support the _elements and _summary search parameters, and return an error when invalid search parameters are used.
Signed-off-by: Troy Biesterfeld tbieste@us.ibm.com
> Issue #1905 - VRead returns error when invalid search parameters used

- docs/src/pages/Conformance.md
- fhir-model/src/main/java/com/ibm/fhir/model/util/ModelSupport.java
- fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
- fhir-search/src/main/java/com/ibm/fhir/search/sort/Sort.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/sort/test/SortParameterParseTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/sort/test/SortTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/ElementsParameterParseTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/PageCountParameterParseTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/SummaryParameterParseTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/TypeParameterParseTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SortingTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/performance/SearchPerformanceTest.java
Updated to return an error when the _type search parameter is used in a non-system search with strict parsing. Updated to have consistent behavior of the _type, _elements, _sort, _count, _page, and _summary search parameters with regards to when any of those parameters is specified multiple times; with strict parsing, an error is returned; with lenient parsing, the value of the first occurrence of the parameter is used.
> Issue #1718 - Update handling of _type and other singleton search params

- docs/src/pages/Conformance.md
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchTokenTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
Added support for the search parameter ':not' modifier.
> Issue #1731 - Add support for ':not' modifier

- docs/src/pages/Conformance.md
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchDateTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchNumberTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchQuantityTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchReferenceTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchStringTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchTokenTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchURITest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCWholeSystemSearchTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchReferenceTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchTokenTest.java
- fhir-persistence/src/test/resources/config/token/extension-search-parameters.json
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchAllTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchChainTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchReverseChainTest.java
Issue #473 - Adds support for the ':missing' modifier to be used in chained search and whole-system search.
> Issue #473 - Add support for ':missing' modifier within chained search and whole-system search

- docs/src/pages/Conformance.md
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/AbstractQueryBuilder.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchTokenTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractWholeSystemSearchTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchAllTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchChainTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchReverseChainTest.java
Issue #1926 - Adds support for the ':not' modifier to be used in chained search and whole-system search.
Signed-off-by: Troy Biesterfeld tbieste@us.ibm.com
> Issue #1926 - Add support for ':not' modifier within chained search and whole-system search

- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
Instead of throwing IllegalArgumentException errors, the various helpers in this class
now throw FHIRPersistenceInterceptorException with OperationOutcomeIssues of type FORBIDDEN.
These issues then get mapped into the desired HTTP status codes on their way out of the server.
> issue #1951 - add OperationOutcomeIssue to exceptions thrown from interceptor

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/OriginalRequestRewriteServerTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchAllTest.java
- fhir-server/liberty-config/config/default/fhir-server-config-db2.json
- fhir-server/liberty-config/config/default/fhir-server-config-postgresql.json
- fhir-server/liberty-config/config/default/fhir-server-config.json
- fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
1. Previously I updated our UriBuilder for this case (and introduced tests
to ensure it is properly functioning). However, I missed the fact that
FHIRRestServletFilter parses the originalRequestUri header value into a
URI and, when this fails, it simply reverts to the actual URL of the
request. Therefor, when the request contained a character like `|`, this
header value was never being used in downstream processing like
UriBuilder.buildSelfUri.toSearchSelfUri().
2. Set originalRequestUriHeaderName to "X-FHIR-FORWARDED-URL" in our
default fhir-server-config (so that this can get tested by our default
CI without flags)
3. Added OriginalRequestRewriteServerTest to ensure this feature is
working as expected
4. Expanded SearchAllTest to include a check for the fullUrl entries in the
response …
> issues #1907 and #1964 - strip the query from originalRequestUri before parsing and fix baseUrl for whole-system queries

- fhir-persistence-schema/pom.xml
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/PopulateParameterNames.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/PopulateResourceTypes.java
- fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/control/PopulateParameterNamesTest.java
- fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/control/PopulateResourceTypesTest.java
Moved PopulateParameterNames.verify() to PopulateParameterNamesTest and
set the FHIRRegistry dependency to `test` scope.
Moved PopulateResourceTypes.verify() to PopulateResourceTypesTest just
for consistency.
> issue #1983 - move verification methods into unit test

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/version/GetLatestVersionDAO.java
This should workaround the root cause of issue #1971 and prevent
`--update-schema` from trying to apply updates that have already been
applied.
The root cause will need to be addressed in a separate PR.
> issue #1971 - handle duplicate entries in version_history with grace

- fhir-install/Dockerfile
Previously we tried to get clever and copy the whole /opt directory,
but that really bloated our image. This change restores us to a more
reasonable size.
> Use two COPY commands to be more selective

- fhir-persistence-schema/README.md
Also, use upper case for the postgresql schema names since the tool now upper-cases them anyway (minimize confusion)
> Clarify that --update-schema is used for both initial deploy and migration

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/Migration.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceTableGroup.java
We missed this as part of #1996, so anyone that has applied these updates to a DB since that change now has the wrong
version of that object.  Since that change was never released, I think we're OK just to fix it now (and help anyone
riding the bleeding edge to manually fix their VERSION_HISTORY table).
I also made an unrelated tweak to the Migration interface:  priorVersion should never be null and this makes that more clear
> set x_RESOURCE_TOKEN_REFS to V0009

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/context/BatchContextAdapter.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/S3Preflight.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java
By overloading BulkDataExportUtil.buildOperationException with a variant
that accepts the cause.
> Add causedBy to caught exceptions.

- .github/ISSUE_TEMPLATE/feature_request.md
I always bugs me that `AND` and `WHEN` are on the same line, and we needed at least one more indent so that the text actually belongs to the numbered list item.
> reformat the acceptance criteria a tad

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/export/group/resource/GroupHandler.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/checkpoint/ExportCheckpointAlgorithm.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/data/ExportCheckpointUserData.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/data/ExportTransientUserData.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/group/ChunkReader.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/patient/ChunkReader.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/system/ChunkReader.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/S3Provider.java
- fhir-bulkdata-webapp/src/main/resources/META-INF/batch-jobs/FhirBulkExportGroupChunkJob.xml
- fhir-bulkdata-webapp/src/main/resources/META-INF/batch-jobs/FhirBulkExportPatientChunkJob.xml
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ExportOperationTest.java
1. Previously we were looping through all of the ReadResultDTOs
(presumably 1 per page of search results), and entering our logic for
each page.  However, the chunkData buffer stream constains the content
from all the results, so this doesn't make much sense to me.
2. Renamed lastWritePageNum to lastWrittenPageNum to make its purpose
more clear (more distinct from lastPageNum)
3. Update ExportOperationTest to properly look for an 'output' key in
the response json, not just anywhere in the response body
4. Add logging to ExportCheckpointAlgorithm
5. ExportTransientUserData.Builder methods now return
ExportTransientUserData instead of the super type (same change was made
to ImportTransientUserData previously)
6. Page number now matches the actual page number read; previously it
was always 1 …
> issue #2040 - cleanup in S3Provider.writeResources

- docs/src/pages/guides/FHIRPerformanceGuide.md
- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-server/liberty-config/configDropins/defaults/datasource.xml
- fhir-server/liberty-config/configDropins/disabled/datasource-db2.xml
- fhir-server/liberty-config/configDropins/disabled/datasource-derby.xml
- fhir-server/liberty-config/configDropins/disabled/datasource-postgresql.xml
We used to have this attribute in our fhirProxyDatasource configuration, but we didn't carry it forward.
After adding it to my deploy, I followed the steps to reproduce the issue described in #2077 and was no longer able to produce it.
From the Liberty docs, here is what this setting does:
> Specifies a timeout for validation of pooled connections. When specified, pooled connections are validated before being reused from the connection pool. The validation timeout is also used when the connection manager validates connections in response to a stale connection for PurgePolicy=ValidateAllConnections. A value of 0 means that connections are validated without applying any timeout. Validation timeout requires a JDBC driver that complies with the JDBC 4.0 specification or higher. Specify a …
> issue #2077 - add validationTimeout to datasource dropins

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/fast/ExportJobListener.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/system/ExportJobListener.java
Note: this may not be ideal... since resources which are Zero'd out, are not returned in a list, back to the end user. 
So we may not want to do this... and may want to raise 2018 to a P2
> Bulk Data aborts when setting the ExitStatus #2018

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/FileProvider.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ImportOperationTest.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/FilePreflight.java
#2103
File-based exports should be organized by subdirectory #2087
> Relative path enables malicious content to be imported or /dev/null

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/checkpoint/ExportCheckpointAlgorithm.java
- fhir-server/liberty-config/config/default/fhir-server-config-db2.json
- fhir-server/liberty-config/config/default/fhir-server-config.json
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/ConfigurationAdapter.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/AbstractSystemConfigurationImpl.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/LegacyConfigurationImpl.java
Previously, the file-based export would use the COS properties for
checkpointing. This is a bit confusing and, additionally, I think we'd
want a different default for "when to start writing" (in COS there are
constraints on the size and count of the parts, while writing to local
disk has different concerns).
> Issue #2112 - checkpoint after each item for file-based export

- docs/src/data/nav-items.yaml
- docs/src/pages/index.mdx
and move the announcement under the blog header...its pretty old now and shouldn't be so prominent on the site.  i tried to preserve the URL though, so anything linking to it should be ok.
> fix touchstone conformance link

- docs/src/pages/index.mdx
This way we can control the exact results that we link to without committing to this repo every time we want to change it.
Currently, I'm the owner of the vanity URL.
> take 2: use an ibm.biz link

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/export/group/resource/GroupHandler.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/export/patient/resource/PatientResourceHandler.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/export/system/resource/SystemExportResourceHandler.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/context/BatchContextAdapter.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/group/ChunkReader.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/patient/ChunkReader.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/patient/PatientExportPartitionMapper.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/system/ChunkReader.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/system/SystemExportPartitionMapper.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/FileProvider.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchCompartmentTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractCompartmentTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ExportOperationTest.java
- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ExportOperation.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ImportOperation.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/PreflightFactory.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/FilePreflight.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/HttpsPreflight.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/NopPreflight.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/S3Preflight.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/type/BulkDataContext.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/type/JobParameter.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/type/OperationFields.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java
1. Introduces SearchUtil.buildInclusionCriteria() for building the
inclusion criteria parameter with multiple compartmentId values (maybe
this should go in CompartmentUtil instead?)
2. Updates JDBCQueryBuilder.processInclusionCriteria to use all of the
inclusionCriteria values; previously it used `=` against the first value
but now it uses `IN (val1,val2,val3,...)` instead.
And update 3 places to use it:
1. A new test in AbstractSearchCompartmentTest
2. com.ibm.fhir.bulkdata.export.patient.resource.PatientResourceHandler.fillChunkDataBuffer()
This should be much simpler now and also much more efficient.
Instead of searching with a value of `id1,id2,id3,...` on each and every
inclusion criteria, we can do a single query with a whole page of
patient ids.
3. …
> issue #2094 - add support for 'or' within inclusion criteria

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/audit/BulkAuditLogger.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/checkpoint/ExportCheckpointAlgorithm.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/FileProvider.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/AbstractSystemConfigurationImpl.java
Also, set more status fields in transient user data (chunkData) to
facilitate logging / debug.
> issue #2121 - skip file creation when the buffer is empty

- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchNearTest.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/FHIRPersistenceTransaction.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/MockTransactionAdapter.java
FHIRPersistenceTransaction #1304
> Remove deprecated commit() and rollback() methods from

- fhir-core/src/main/java/com/ibm/fhir/core/util/URLSupport.java
- fhir-core/src/test/java/com/ibm/fhir/core/util/test/URLSupportTest.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/FHIRPathAbstractTermFunction.java
- fhir-registry/src/main/java/com/ibm/fhir/registry/resource/FHIRRegistryResource.java
- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/provider/GraphTermServiceProvider.java
- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/registry/SnomedRegistryResourceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/registry/ImplicitValueSetRegistryResourceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/util/CodeSystemSupport.java
- fhir-term/src/test/java/com/ibm/fhir/term/service/test/CodeSystemSupportTest.java
1. Refactored common code for working with URLs into a utility class called `URLSupport`
2. Created abstract base class for implicit value set registry resource providers
3. Added `getAncestorsAndSelf` and `getDescedantsAndSelf` methods to `CodeSystemSupport` (for #1733)
4. Added unit tests for 1. and 3.
5. Added `hasLabel("Concept")` when `ValueSet` include filters list is empty
NOTE: I "sorted members" on `CodeSystemSupport`, therefore, it looks like more changes than are actually there. The only substantive changes are the addition of the new methods mentioned in 3. above.
> Issue #2092, Issue #1733, Issue #1980 - miscellaneous updates

- fhir-install/Dockerfile
- fhir-install/src/main/resources/scripts/install.bat
- fhir-install/src/main/resources/scripts/install.sh
- fhir-parent/pom.xml
> upgrade to liberty 21.0.0.3

- fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/provider/RegistryTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/spi/FHIRTermServiceProvider.java
1. clarify the contract for FHIRTermServiceProvider.getConcept
2. update stale javadoc for FHIRTermServiceProvider.subsumes
3. clarify that ConceptSubsumptionOutcome can come back null
> issue #1530 - javadoc updates

- fhir-install/Dockerfile
- fhir-install/src/main/resources/scripts/install-fhir.sh
this change splits the COPY /opt/ol/wlp/usr /opt/ol/wlp/usr into two
steps:
* first we move just the server.xml and configDropins
* then, after installing the liberty features, we add the application
* finally, we add the bootstrap.sh script and related tools
> issue #923 - run features.sh earlier to enable layer caching

- fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
- fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java
Issue #1846 - Add compartment variants to generated swagger/openapi
> Issue #1846 - Add compartment variants to generated swagger/openapi

- fhir-install/Dockerfile
Image size and startup time are comparable (java 11 was ~400 MB larger and starts about 1 second slower).
Image build time was significantly slower on the first build, but then comparable on every build after that, even with `--no-cache` (not sure why).
first java 11 build:
```
$ docker build fhir-install -t ibmcom/ibm-fhir-server 
...
=> [stage-1 5/9] RUN features.sh                                                     144.2s 
=> [stage-1 6/9] COPY --chown=1001:0 --from=base /opt/ol/wlp/usr /opt/ol/wlp/usr       1.1s 
=> [stage-1 7/9] RUN configure.sh                                                    193.5s
...
```
second build with java 11 (with no-cache):
```
$ docker build fhir-install -t ibmcom/ibm-fhir-server --no-cache   
...
=> [stage-1 5/9] RUN features.sh …
```
> change to java 11 in the docker image

- fhir-path/src/main/java/com/ibm/fhir/path/function/ExpandFunction.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/LookupFunction.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/TranslateFunction.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/ValidateCSFunction.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/ValidateVSFunction.java
- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/provider/GraphTermServiceProvider.java
- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/registry/SnomedRegistryResourceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/ExpansionParameters.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/LookupOutcome.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/LookupParameters.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/TranslationOutcome.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/TranslationParameters.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/ValidationOutcome.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/ValidationParameters.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/provider/RegistryTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/spi/FHIRTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/util/CodeSystemSupport.java
- fhir-term/src/test/java/com/ibm/fhir/term/service/test/CodeSystemSupportTest.java
- fhir-term/src/test/java/com/ibm/fhir/term/service/test/FHIRTermServiceTest.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/AbstractTermOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/CodeSystemValidateCodeOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/ExpandOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/LookupOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/TranslateOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/ValueSetValidateCodeOperation.java
Updates include:
1. Added the following methods to `CodeSystemSupport`
`getConcepts(CodeSystem, Function)`
`getConcepts(CodeSystem, List<Filter>, Function)`
`getConcepts(Concept, Function)`
2. Added the following methods to the `FHIRTermServiceProvider` interface:
`getConcepts(CodeSystem, Function)`
`getConcepts(CodeSystem, List<Filter>, Function)`
NOTE: included default implementation of these methods in the `FHIRTermServiceProvider` interface
3. Added the following methods to `FHIRTermService`:
`getConcepts(CodeSystem, Function)`
`getConcepts(CodeSystem, List<Filter>, Function)`
4. Moved all `Parameters` and `Outcome` classes from the `com.ibm.fhir.term.spi` package to the `com.ibm.fhir.term.service` package which is where they are …
> Issue #2162 - miscellaneous updates

- fhir-parent/pom.xml
> ch.qos.logback:logback-core is vulnerable to CVE-2017-5929 #2216

- fhir-bucket/src/main/java/com/ibm/fhir/bucket/reindex/DriveReindexOperation.java
This addresses issue 2219.
The new behavior allows `callReindexOperation` to catch expected exceptions from `FHIRBucketClient.post` and allow the thread count to be decremented AND for running be set to false.  These two changes will allow `monitorLoop` to attempt to refill the request pool.  It is likely that will fail and the program will exit allowing the caller to fix the connection problem and restart the reindex program.
Log excerpt showing `monitorLoop` successfully exiting once a connection cannot be made to FHIR server:
```
java -jar "${JAR}" --tenant-name $MY_TENANT  --max-concurrent-fhir-requests 100 --no-scan --reindex-tstamp 2021-03-30T00:00:00Z --reindex-resource-count 100 --reindex-concurrent-requests 5 --fhir-properties $FHIR_PROPERTIES
Apr 08, 2021 11:58:36 AM …
```
> fhir-bucket: Allow clean exit when connection to FHIR server cannot be made

- fhir-path/src/main/java/com/ibm/fhir/path/util/FHIRPathUtil.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRPatchTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
previously we threw 500 Sever Error, even in cases where we knew it was
likely a bad patch.  now we favor 400 errors for those, but unexpected
errors should still result in 500 errors
> issue #2207 - throw a 400 for bad patches

- fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
- fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java
specifically, we were missing the definitions for Resource and
DomainResource, which are referenced from the CapabilityStatement
definition
> add missing definitions to the metatadata swagger

- fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
In swagger 2.0, this was a simple string.
However, in OpenAPI 3.0, this became an object (as documented at
https://swagger.io/specification#discriminator-object ) and we just
never noticed til now.
> update the Resource type discriminator for OpenAPI 3

- fhir-provider/src/main/java/com/ibm/fhir/provider/FHIRJsonProvider.java
- fhir-provider/src/main/java/com/ibm/fhir/provider/FHIRProvider.java
- fhir-provider/src/test/java/com/ibm/fhir/provider/FHIRProviderTest.java
This change is needed to allow fhir-provider to execute in other
environments such as from within a standalone RestEasy client.
I also converted the static 'isPretty' helper to a member function to
allow access to the instance-level RuntimeType.
I also added javadoc to help distinguish FHIRProvider from
FHIRJsonProvider.
> Avoid use of injected httpHeaders and uriInfo when in client mode

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/common/BulkDataUtils.java
- fhir-provider/pom.xml
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRUrlParser.java
- fhir-server/src/test/java/com/ibm/fhir/server/util/FHIRUrlParserTest.java
I actually like having this one in fhir-provider, but I was trying to
slim down `fhir-provider` and it was easier to move this than to remove
its unusual dependency on httpclient.
For those using just fhir-provider (and its runtime dependencies), its not a huge savings (9.6 MB to 8.1 MB) but its 4 fewer libs and it'll be nice not to pull in a whole http client for what should be a simple layer on top of fhir-model.
> Move FHIRUrlParser from fhir-provider to fhir-server

- fhir-model/src/main/java/com/ibm/fhir/model/util/FHIRUtil.java
- fhir-provider/pom.xml
- fhir-provider/src/main/java/com/ibm/fhir/provider/FHIRProvider.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/ServerSpecTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
- Updated fhir-provider/pom.xml to include OWASP Encoder
- Added FHIRProvider encoding for OperationOutcome Messages
- Add defensive code to FHIRUtil, FHIRResource to escape simple HTML
> WHFFHIR-108

- fhir-core/src/main/java/com/ibm/fhir/core/util/handler/IPHandler.java
- Specific to some setups where the name lookup fails.
> Failure acquiring local host IP address results in 400 #2243

- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java
1. getPatientRefValue now uses ReferenceUtil to obtain the id of the
target Patient being referenced. This technique matches what we do
during the extraction of the compartment membership param and is more
robust to special reference values like versioned references or absolute
references that match the base server url.
2. getPatientIdFromToken will now split the patient_id claim on spaces.
This sets us up for scenarios where a single token can grant access to
multiple patient records. Additionally, I removed the log statement
about expecting patient_id to be a string and not a list.
3. Patient search is now allowed. Because we convert all searches into
compartment searches, there is no longer a risk of exposing whether a
given Patient resource by a given id exists or not. Therefore, we …
> AuthzPolicyEnforcement changes

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/RemoteTermServiceProviderTest.java
- fhir-term-remote/src/main/java/com/ibm/fhir/term/remote/provider/RemoteTermServiceProvider.java
`RemoteTermServiceProvider.getConcept` throws an Exception for responses other than OK (200). However, in order to be aligned with the `getConcept` contract, we should return null instead.
> Issue #2198 - getConcept should return null for responses other than 200

- fhir-server/src/main/java/com/ibm/fhir/server/operation/spi/FHIROperationContext.java
- fhir-server/src/main/java/com/ibm/fhir/server/operation/spi/FHIRResourceHelpers.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Batch.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Create.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Delete.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/History.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Operation.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Patch.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Read.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Search.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Update.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/VRead.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/InteractionValidationConfigTest.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/ProfileValidationConfigTest.java
- fhir-server/src/test/java/com/ibm/fhir/server/util/FHIRRestHelperTest.java
- operation/fhir-operation-apply/src/main/java/com/ibm/fhir/operation/apply/ApplyOperation.java
- operation/fhir-operation-document/src/main/java/com/ibm/fhir/operation/document/DocumentOperation.java
- operation/fhir-operation-everything/src/main/java/com/ibm/fhir/operation/everything/EverythingOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/AbstractTermOperation.java
And also from the OperationContext.
Also updated javadoc in FHIRResourceHelpers (lots of missing params).
> issue #1852 - remove requestProperties from all FHIRRestHelper methods

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BundleTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/MockPersistenceImpl.java
- fhir-server/src/test/java/com/ibm/fhir/server/util/FHIRRestHelperTest.java
1. FHIRRestHelper.validateBundle now returns a sparse array (modeled as
a map) of bundle response entries with errors / warnings. It used to construct an
entire response bundle.
2. FHIRRestHelper.processEntriesByMethod replaces
FHIRRestHelper.processEntriesForMethod and iterates the request entries
a single time, instead of once-per-method.
3. Entries are collected into an array instead of "modifying" the
responseBundle with each one (which forced lots of needless copying
since our model is now immutable).
4. Stop duplicating custom operation results in the
`Bundle.entry.response.outcome` field of the response. We already copy
the operation's result in the `Bundle.entry.resource` and that should be
sufficient.
I also made significant formatting changes in FHIRRestHelper.
Signed-off-by: …
> issues #2281 and #864 - batch/transaction bundle processing changes

- fhir-cache/pom.xml
- fhir-core/pom.xml
Initially John added Caffeine to fhir-core but he later refactored this
caching work to a separate module.  This commit updates the dependency
hierarchy to match.
> Move caffeine dependency from fhir-core to fhir-cache

- fhir-path/src/main/java/com/ibm/fhir/path/util/FHIRPathUtil.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BundleTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/operation/spi/FHIRResourceHelpers.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Batch.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/InteractionValidationConfigTest.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/ProfileValidationConfigTest.java
- fhir-server/src/test/java/com/ibm/fhir/server/util/FHIRRestHelperTest.java
If `X-FHIR-UPDATE-IF-MODIFIED` is set to true on the request, then all
updates (including patches) in the bundle will be processed in accordance 
with this update optimization.
> issue #2284 - support skippable updates for batch/transaction methods

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractIncludeRevincludeTest.java
> Issue #2305 - fix _include search with _total=none when no 'match'

- fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
- fhir-term-remote/src/main/java/com/ibm/fhir/term/remote/provider/RemoteTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/provider/RegistryTermServiceProvider.java
- fhir-term/src/main/java/com/ibm/fhir/term/util/ValueSetSupport.java
- fhir-term/src/test/java/com/ibm/fhir/term/service/provider/test/RegistryTermServiceProviderPerformanceTest.java
> Issue #2292 - error handling and memberOf optimization

- fhir-cache/src/main/java/com/ibm/fhir/cache/util/CacheSupport.java
- fhir-model/src/main/java/com/ibm/fhir/model/util/ValidationSupport.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
- fhir-term-remote/src/main/java/com/ibm/fhir/term/remote/provider/RemoteTermServiceProvider.java
- fhir-term-remote/src/test/java/com/ibm/fhir/term/remote/provider/test/RemoteTermServiceProviderTest.java
- fhir-term/src/main/java/com/ibm/fhir/term/service/provider/RegistryTermServiceProvider.java
- Fixed minor spacing issue in `CacheSupport` class
- Renamed `advancedCodeableConceptValidation` to `extendedCodeableConceptValidation` to match the configuration property name
- Added `maximumSize` to the `@Cacheable` annotation on the `RegistryTermServiceProvider.getConcept` method
- Added code to optionally log remote term service requests when log level is set to FINEST
- Updated error message in `MemberOfFunction`
> Issue #2292 - miscellaneous clean-up

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterVisitorBatchDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dto/QuantityParmVal.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/ParameterExtractionTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
Issue #2041 - Make quantity values searchable even without unit or code
> Issue #2041 - Make quantity values searchable even without unit or code

- fhir-registry/src/main/java/com/ibm/fhir/registry/FHIRRegistry.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/CapabilitiesTest.java
> Issue #2342 - add support for TerminologyCapabilities

- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/GetTenantInfo.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/GetTenantList.java
Issue #2352 - Fix drop tenants when schema name less than 8 chars
Issue #2353 - Fix list tenants when schema name less than 8 chars
> Issue #2352 - Fix list/drop tenants when schema name less than 8 chars

- fhir-registry/src/main/resources/hl7/fhir/core/package/SearchParameter-clinical-patient.json
- fhir-registry/src/test/java/com/ibm/fhir/registry/tool/IndexGenerator.java
The built-in SearchParameter-clinical-patient search parameter should
have a single target of type "Patient" but instead it has a target of
both "Patient" and "Group".
In this commit, I move the fhir-registry IndexGenerator from
src/main/java to src/test/java and add a step to modify this one spec
resource so that users can search on the `patient` search parameter
without needing a type modifier.
> issue #1674 - workaround for HL7 FHIR-13601

- fhir-install/src/main/docker/ibm-fhir-schematool/Dockerfile
- fhir-install/src/main/docker/ibm-fhir-schematool/run.sh
- fhir-install/src/main/docker/ibm-fhir-schematool/tests/2349/2349.sh
- fhir-install/src/main/docker/ibm-fhir-schematool/tests/2349/docker-compose.yml
> Allocate Tenant without TenantKey Fails in the ibm-fhir-schematool on db2 #2349

- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
Issue #1885 - Include search parameter URLs in conflict warning message (in additional code path found during QA)
> Issue #1885 - Include search parameter URLs in conflict warning message

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/DeleteTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Issue #2365 - Show resource ids in conditional delete operation outcome
> Issue #2365 - Show resource ids in conditional delete operation outcome

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-server/liberty-config/server.xml
- fhir-server/pom.xml
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/util/FHIRRestHelperTest.java
This allows the interceptors to modify the incoming resource.
> issue #2369 - use the resource from the event after interceptor calls

- fhir-server-test/src/main/java/com/ibm/fhir/server/test/persistence/TaggingInterceptor.java
> issue #2369 - fix the TaggingInterceptor

- conformance/fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/C4BBPatientConstraintGeneratorTest.java
- conformance/fhir-ig-carin-bb/src/test/resources/JSON/StructureDefinition-C4BB-Patient.json
- fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
- fhir-path/src/test/java/com/ibm/fhir/path/test/MemberOfFunctionTest.java
- fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
Changes made:
- Updated `ConstraintGenerator.generatePatternValueConstraint` to support the pattern value constraints that are also slices with a discriminator path of `$this`
- Updated `FHIRPathEvaluator` to remove "workaround" for `in` operator. Previously we turned an `in` operator expression into a `memberOf` function invocation in some circumstances.
- disabled test in `MemberOfFunctionTest`
- added unit test using latest version of C4BB Patient structure definition
> Issue #2377 - update ConstraintGenerator

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/DerbyResourceDAO.java
- fhir-persistence-schema/src/main/resources/db2/add_any_resource.sql
- fhir-persistence-schema/src/main/resources/postgres/add_any_resource.sql
- fhir-server/liberty-config/configDropins/defaults/datasource.xml
- fhir-server/liberty-config/configDropins/disabled/datasource-derby.xml
Also aligned the stored procedures for Db2 and PostgreSQL so they match the logic of the Derby DAO. This ended up eliminating an update statement which we were executing for new resources which could be avoided. This should help PostgreSQL in particular, because it avoids tombstones which would need to be vacuumed.
> issue 2420 set Derby isolationLevel to avoid deadlock during ingestion

- fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/ConformsToFunction.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/ResolveFunction.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/FHIRPathUtil.java
- fhir-path/src/test/resources/FHIRPath/tests-fhir-r4.xml
- fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
- fhir-profile/src/main/java/com/ibm/fhir/profile/ProfileSupport.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/ServerResolveFunctionTest.java
- fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
Miscellaneous Updates
- Fold `resolveRelativeReferences` into the `EvaluationContext` class. Typically FHIRPath "external constants" are treated as data. In this case, however, we are using an external constant as configuration parameter. It makes more sense to make this a field in the `EvaluationContext` class itself.
- Created `hasResourceAssertedProfile` method in `ProfileSupport`
- Added validation logic to the `FHIRPathUtil.compile` method to prevent partial expressions from being evaluated without throwing an exception
> Issue #2296, Issue #2377 - miscellaneous FHIRPath updates

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-install/Dockerfile
- fhir-server/liberty-config/config/default/fhir-server-config.json
Issue #2086 - Change default bulkdata directory
> Issue #2086 - Change default bulkdata directory

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/SingleResourceResult.java
- fhir-server/src/main/java/com/ibm/fhir/server/operation/spi/FHIRResourceHelpers.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Read.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/InteractionValidationConfigTest.java
- operation/fhir-operation-apply/src/main/java/com/ibm/fhir/operation/apply/ApplyOperation.java
- operation/fhir-operation-document/src/main/java/com/ibm/fhir/operation/document/DocumentOperation.java
- operation/fhir-operation-erase/src/test/java/com/ibm/fhir/operation/erase/mock/MockFHIRResourceHelpers.java
- operation/fhir-operation-everything/src/main/java/com/ibm/fhir/operation/everything/EverythingOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/AbstractTermOperation.java
> issue 2283 - eliminate redundant reads during ingestion

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/RemoteTermServiceProviderTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/listener/FHIRServletContextListener.java
- fhir-term-remote/src/main/java/com/ibm/fhir/term/remote/provider/RemoteTermServiceProvider.java
> Issue #2431 - add support for headers in RemoteTermServiceProvider

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/S3Provider.java
> Vanity URLs with AWS result in bucket NOT_FOUND on  #2411

- conformance/fhir-ig-davinci-pdex/src/test/java/com/ibm/fhir/ig/davinci/pdex/tool/SearchParameterAugmenter.java
- conformance/fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/tool/SearchParameterAugmenter.java
- fhir-client/src/test/java/com/ibm/fhir/client/test/mains/JaxrsClientTestMain.java
- fhir-core/src/main/java/com/ibm/fhir/core/FHIRConstants.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
- fhir-search/src/main/java/com/ibm/fhir/search/compartment/CompartmentUtil.java
- fhir-search/src/main/java/com/ibm/fhir/search/reference/value/CompartmentReference.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchExtensionsTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/operation/spi/AbstractOperation.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/IssueTypeToHttpStatusMapper.java
- fhir-server/src/test/java/com/ibm/fhir/server/util/IssueTypeToHttpStatusMapperTest.java
- operation/fhir-operation-apply/src/main/java/com/ibm/fhir/operation/apply/ApplyOperation.java
- operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/LookupOperation.java
The CompartmentDefinition resource has a required binding to a fixed
list of compartment types. To support a custom compartments, we will now
look for the `http://ibm.com/fhir/extension/custom-compartment-type`
extension on this element (when it has no value).
Additionally, I created a constant in fhir-core FHIRConstants for our
base extension url and I updated all the different places we have
extension urls to use it.
> issue #2143 - support custom compartment types via extension

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BasicServerTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
- Add implementation for the various Capabilities statements
- Add FHIRPath validation to IT tests
- Add configuration property for URL
> IBM FHIR Server CapabilityStatement is invalid #2436

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/export/patient/resource/PatientResourceHandler.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/group/ChunkReader.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/patient/ChunkReader.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/interceptor/impl/FHIRPersistenceInterceptorMgr.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchCompartmentTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/date/DateTimeHandler.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/MockPersistenceImpl.java
These changes add special-case logic for List resources:
1. even though Lists can be in the patient compartment, searches for
Lists will no longer become automatically scoped to the patient
compartment because some lists (e.g. Formulary Coverage Plans) must be
accessible to the patient despite being exist outside the compartment
(affects beforeSearch).
2. access to List resources that conform to the DaVinci Drug Formulary
Coverage Plan will be allowed without compartment membership checking
(affects afterRead, afterVRead, afterHistory, and afterSearch).
I also converted the compartmentLogicalIds from a List to a Set because
the set of compartmentLogicalIds is order-independent and shouldn't have
duplicates.
Finally, I loosened the compartment-search constraint in the interceptor
so that …
> Be more lenient for List in the fhir-smart authz interceptor

- fhir-client/src/main/java/com/ibm/fhir/client/FHIRParameters.java
- fhir-client/src/test/java/com/ibm/fhir/client/test/testng/FHIRParametersTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
Issue #2427 - Add missing modifiers to FHIRParameters in FHIR Client
> Issue #2427 - Add missing modifiers to FHIRParameters in FHIR Client

- docs/src/pages/Conformance.md
- fhir-core/src/main/java/com/ibm/fhir/core/FHIRMediaType.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BasicServerTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/PrettyServerFormatTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/exception/FHIRRestServletRequestException.java
- fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java
- fhir-server/src/test/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilterTest.java
Issue #896 - Add checking for MIME-type parameter fhirVersion
> Issue #896 - Add checking for MIME-type parameter fhirVersion

- fhir-client/src/main/java/com/ibm/fhir/client/FHIRClient.java
- fhir-client/src/main/java/com/ibm/fhir/client/impl/FHIRClientImpl.java
- fhir-client/src/test/java/com/ibm/fhir/client/test/mains/FHIRClientSample.java
- fhir-client/src/test/java/com/ibm/fhir/client/test/testng/FHIRClientImplTest.java
- fhir-client/src/test/resources/test.basic.properties
- fhir-server-test/src/test/java/com/ibm/fhir/client/test/FHIRClientTestBase.java
- fhir-server-test/src/test/java/com/ibm/fhir/client/test/oauth/FHIROAuth2Test.java
- fhir-server-test/src/test/resources/test.oauth2.properties
> FHIRClient.getWebTarget(String baseURL) throws NPE #2450

- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
Issue #2445 - Log warning messages about deprecated tables
> Issue #2445 - Log warning messages about deprecated tables

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/TimestampPrefixedUUIDTest.java
1. refactored common logic from across create, update, and delete
methods into private helpers `copyAndSetResourceMetaFields` and
`createResourceDTO`
2. set the resourceBuilder to non-validating in
copyAndSetResourceMetaFields since the resource has already been
validated by this point
3. use try-with-catch for the GZIPOutputStream to ensure we never leak
resources
> Miscelaneous FHIRPersistenceJDBCImpl changes

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/tenant/DeleteTenantKeyDAO.java
- fhir-persistence-schema/README.md
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/util/CommonUtil.java
> Support revocation of tenant keys #2211

- fhir-registry/src/test/java/com/ibm/fhir/registry/tool/IndexGenerator.java
Per https://jira.hl7.org/browse/FHIR-32876 this search parameter is
wrong in the latest draft of the spec.  I thought it was wrong in our
packaged version (4.0.1) as well, but it turns out I was mistaken.
Still, I thought it would be good to keep this logic in place for when
we move to the R5 artifacts.
> modify Provenance-patient parameter during index generation

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java
> Audit record uses the exact value of: X-FHIR-FORWARDED-URL header as the URL called for the log entry #2473

- fhir-benchmark/pom.xml
- fhir-benchmark/src/main/java/com/ibm/fhir/benchmark/FHIRIndexParserBenchmark.java
Instead of parsing a single file, this variant parses a set of files.
I included benchmark variants for single threaded parsing vs a
parallelStream to parse the examples in parallel.
> Added new parser benchmark that works against an examples index

- fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/AddingVisitor.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/DeletingVisitor.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/FHIRPathUtil.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/InsertingVisitor.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/MovingVisitor.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/ReplacingVisitor.java
- fhir-path/src/test/java/com/ibm/fhir/path/patch/test/FHIRPathUtilTest.java
- fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
FHIRPathUtil was using a shared static FHIRPathEvaluator but this is not
thread-safe. Now we construct a new evaluator for each request.
> issue #2510 - make FHIRPathUtil threadsafe

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
- fhir-notification/pom.xml
- fhir-notification/src/main/java/com/ibm/fhir/notification/util/FHIRNotificationUtil.java
- fhir-notification/src/test/java/com/ibm/fhir/notification/util/FHIRNotificationUtilTest.java
- fhir-notification/src/test/resources/config/empty/fhir-server-config.json
- fhir-notification/src/test/resources/config/omit/fhir-server-config.json
- fhir-notification/src/test/resources/config/subset/fhir-server-config.json
- notification/fhir-notification-kafka/src/main/java/com/ibm/fhir/notifications/kafka/impl/FHIRNotificationKafkaPublisher.java
- Updated fhir server's users guide to outline new preferences and add
missing fields
- Updated FHIRNotificationUtil to support new max Size behavior and
bytes so that it can be tuned to each use case by subset or omit when it
hits a limit. (There is no spanning/splitting to avoid delivery order
issues)
- Add Synchronous support to Kafka Notification and documentation how to
enable (users can now chose if they want a lossy approach or not)
- Add test coverage for fhir-notification and FHIRNotificationUtil
> fhir-notification: Limit handling for 1M #1948

- fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/ConformsToFunction.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/FHIRPathAbstractFunction.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/ResolveFunction.java
- fhir-path/src/test/java/com/ibm/fhir/path/test/ResolveInternalFragmentReferenceTest.java
- fhir-registry/src/main/java/com/ibm/fhir/registry/util/FHIRRegistryResourceProviderAdapter.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/ConformsToLoopTest.java
1. update ResolveFunction.resolveInternalFragmentReference 
2. introduce function result caching in evaluation context
> Issue #2516, #2518 - FHIRPath updates

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/DateParmBehaviorUtil.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/NewDateParmBehaviorUtil.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/NewNumberParmBehaviorUtil.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/NumberParmBehaviorUtil.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/DateParmBehaviorUtilTest.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/LastUpdatedParmBehaviorUtilTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchCompositeTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchQuantityTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractIncludeRevincludeTest.java
- fhir-persistence/src/test/resources/logging.unitTest.properties
- fhir-search/src/main/java/com/ibm/fhir/search/date/DateTimeHandler.java
We use the range interpretation of the search prefixes for both date and
number/quantity searches.  The spec says:
* `lt` means "the range below the search value intersects (i.e. overlaps) with the
range of the target value"
* `gt` means "the range above the search value intersects (i.e. overlaps) with the
range of the target value"
For numbers, the spec additionally says:
* When a comparison prefix in the set gt, lt, ge, le, sa & eb is provided, the implicit precision of the number is ignored, and they are treated as if they have arbitrarily high precision
Previously, we interpreted date search in the same way and so a search like `gt2016`
would return any value above `2016-01-01 00:00:00` in the server's
timezone.  However, we were not consistent with this because, for some reason,
we …
> issue #2528 - change interpretation of lt and gt for date searches

- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
In addition to copying their OperationOutcomeIssues, we now include the original
exception in the CausedBy of the FHIRRestBundledRequestExceptions created in 
`FHIRRestHelper.processEntriesByMethod`.
This way, if the FHIROperationException was unexpected and has no
corresponding issues, when it gets mapped to a 500 Server Error we will
automatically log the exception from
FHIRResource.exceptionResponse(FHIROperationException, Status).
> issue #2535 - wrap exceptions instead of losing them

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ChunkWriter.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/AzureProvider.java
- fhir-bulkdata-webapp/src/test/java/com/ibm/fhir/bulkdata/provider/impl/AzureProviderMain.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/AzurePreflight.java
- Increase the BlobRange size for Read Speed
- Add Preflight Checks for Azure
- Improve handling of the edge of an $Import read window for Azure Blobs
- Add AzureProviderMain tests for driving tests from local
> Per Testing with Azure Provider and Fix Skippable Logic

- fhir-bucket/src/main/java/com/ibm/fhir/bucket/reindex/ClientDrivenReindexOperation.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/ReindexOperationTest.java
Issue #2195 - Have client-driven reindex exit if no work to do
> Issue #2195 - Have client-driven reindex exit if no work to do

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/ServerSpecTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Create.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Delete.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/History.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Operation.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Patch.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Read.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Search.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Update.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/VRead.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/InteractionValidationConfigTest.java
Because we use "Resource" as the resource type for whole-system search
and whole-system history interactions, it wasn't as simple as just
checking for abstract types in FHIRRestHelper.validateInteraction().
Instead, I now check that the type in the request path is valid directly
from the JAX-RS endpoints / bundle entry processing.
This has the additional benefit of catching URL path errors up front,
avoiding almost all work associated with this type of bad request.
> issue #2526 - deprecate the /Resource and /DomainResource endpoints

- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/MigrateV0014LogicalResourceIsDeletedLastUpdated.java
Theres no need for the `WHERE lr.resource_type_id = " +
this.resourceTypeId` because we're selecting from the
resourceType-specific logical resources table.
> issue #2588 - fix V0014 migration runForDerby select statement

- fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/FHIRValidatorTest.java
- Moved `validateProfileReferences(...)` method from `FHIRValidator` to `FHIRValidator.ValidatingNodeVisitor`
- Updated main `FHIRValidator.validate(...)` method / entry point to be more consistent with main `FHIRPathEvaluator.evaluate(...)` method / entry point
- Updated main `FHIRValidator.ValidatingNodeVisitor.validate(...)` method to be more consistent with `FHIRPathEvaluator.EvaluatingVisitor.evaluate(...)` method
- Updated `ValidatingNodeVisitor.validate(FHIRPathElementNode)` and `ValidatingNodeVisitor.validate(FHIRPathResourceNode)` methods to be more consistent in structure
> Issue #2582, #2583 - general refactoring / clean-up

- fhir-bucket/src/main/java/com/ibm/fhir/bucket/reindex/ClientDrivenReindexOperation.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/RetrieveIndexOperationTest.java
- operation/fhir-operation-reindex/src/main/java/com/ibm/fhir/operation/reindex/RetrieveIndexOperation.java
Issue #2195 - Add additional logging
> Issue #2195 - Add additional logging

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/db2/Db2ResourceReferenceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- Remove an incorrect retry
- optimize the  db2 specific reindexing to retry when SQL Constraint on Common Token values.
> update db2 reindex constraint violation

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/export/system/resource/SystemExportResourceHandler.java
Previously, we added the entire size of the buffer after each page of
results was read. This leads us to think that we have a lot more data
than we actually do. Now we will add only the new bytes.
This change fixes the over-counting but also started causing us to hit transaction timeouts.
It especially happens if you use an `_elements` filter because the search queries take just as long
but the size of the resources is much smaller and so we need many more resources to reach our
partUploadTriggerSizeMB for the checkpoint.
In the short term, it should be possible to either:
A. increase the transaction timeout (so we can gather more bytes before the timeout occurs); and/or
B. decrease the partUploadTriggerSizeMB (our default is 10 but we can go as low as 5 for S3)
In the longer term, we …
> issue #2666 - fix for currentUploadSize tracking

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Issue #2607 - Do not show next link when not necessary
> Issue #2607 - Do not show next link when not necessary

- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java
In addition to checking the scopes for each resource on the way out (via
the afterX methods), we now check that the requested interaction is
permitted by the passed scopes on the way in (the beforeX methods).
Two reasons:
1. We prevent some unnecessary work for invalid requests
2. We prevent leaking info about the presence/absence of resourceTypes
for which a given application has not been granted access
The request scopes are already checked before create, update, and
delete.
> issue #2669 - validate request scopes before read, vread, history, and search

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/common/BulkDataUtils.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/AzureProvider.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/FileProvider.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/S3Provider.java
Now the FileProvider follows the same pattern as the S3Provider...we
update the resourceTypeSummary at the end of each "currentUpload".
> issue #2673 - Set the resourceTypeSummary at the end of each file export

- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java
Importantly, access tokens with `user/<resourceType>.<permission>`
scopes will now have this permission for *all* resources of this type.
In most cases, operators using `user/` scopes will need to layer on
their own permissions model on top of what is provided in this
authorization interceptor.
> Add support for user/ scopes

- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/query/expression/StringStatementRenderer.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/cache/CommonTokenValuesCacheImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/ICommonTokenValuesCache.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/IResourceReferenceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/JDBCIdentityCache.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/JDBCIdentityCacheImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceReferenceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/DerbyResourceReferenceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchQueryRenderer.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dto/CommonTokenValue.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dto/CommonTokenValueResult.java
Added:
* getCommonTokenValueIds to JDBCIdentityCache
* resolveCommonTokenValueIds to ICommonTokenValuesCache
* readCommonTokenValueIds to ResourceReferenceDAO
Updated SearchQueryRenderer to use this mechanism in two cases:
* getReferenceFilter for reference params without the `:identifier` modifier (including compartment params)
* getTokenFilter for token params with the IN, ABOVE, BELOW, and NOT-IN modifiers
Also includes cleanup in getReferenceFilter and populateCodesSubSegment (used by getTokenFilter):
* removal of code in getReferenceFilter for handling modifier that we don't support for reference params
* removal of code that uses the token ref view for token filters...I believe that the IN, ABOVE, BELOW, and NOT-IN cases can be handled with COMMON_TOKEN_VALUES now
Needs testing on …
> issue #2184 - support getting all the common token value ids in one go

- CONTRIBUTING.md
Fixes https://github.com/IBM/FHIR/issues/2695
Update instructions in CONTRIBUTING.md to reference the wiki pages
instead of duplicating build commands.
> issue 2695 fix CONTRIBUTING.md build instructions

- fhir-notification/src/main/java/com/ibm/fhir/notification/FHIRNotificationService.java
Example output 
```
CreateTime:1629206705007	{"lastUpdated":"2021-08-17T13:25:04.975288Z","location":"Patient/7b4ab90d-e97b-42c3-bc9a-0595353cf36b/_history/2","operationType":"patch","resourceId":"7b4ab90d-e97b-42c3-bc9a-0595353cf36b","datasourceId":"default","tenantId":"default","resource":{"resourceType":"Patient","id":"7b4ab90d-e97b-42c3-bc9a-0595353cf36b","meta":{"versionId":"2","lastUpdated":"2021-08-17T13:25:04.975288Z"},"text":{"status":"generated","div":"<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative</b></p></div>"},"active":false,"name":[{"family":"Doe","given":["John"]}],"birthDate":"1980-01-01"}}
```
I ran through our Patch IT tests with the change.
> FHIRNotificationService should emit event for patch update #2692

- fhir-model/src/main/java/com/ibm/fhir/model/visitor/EncodingVisitor.java
- fhir-model/src/test/java/com/ibm/fhir/model/visitor/test/CopyingVisitorTest.java
- fhir-model/src/test/java/com/ibm/fhir/model/visitor/test/EncodingVisitorTest.java
- fhir-model/src/test/java/com/ibm/fhir/model/visitor/test/PathAwareVisitorTest.java
- fhir-provider/src/main/java/com/ibm/fhir/provider/FHIRProvider.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/ServerSpecTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/operation/spi/AbstractOperation.java
- fhir-server/src/main/java/com/ibm/fhir/server/operation/spi/FHIROperationContext.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Operation.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Initially, I thought we could use this EncodingVisitor to encode all string 
fields from OperationOutcome resources that we construct (before returning
them to the client).
However, after further discussion, I think we'll tackle that under #2596 by
encoding the content more selectively.
Additionally, I removed some redundant resource type checking from AbstractOperation.
Now that we ensure that the resource type is valid prior to invoking the
operation, there's no need for having this check in AbstractOperation
and therefor also no need to have the PROPNAME_PATH_PARAMETER in the
OperationContext.
I left the PR open because I still think the EncodingVisitor could be generically useful (and
because some of the other cleanup in here still seems worthwhile to me).
> Introduce EncodingVisitor and remove redundant resource type checking in AbstractOperation

- fhir-model/src/test/java/com/ibm/fhir/model/test/TestUtil.java
- fhir-model/src/test/java/com/ibm/fhir/model/util/test/ResourceFingerprintVisitorTest.java
- fhir-model/src/test/java/com/ibm/fhir/model/visitor/test/EncodingVisitorTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchIdAndLastUpdatedTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractWholeSystemSearchTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/FHIRPersistenceEventTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractChangesTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractCompartmentTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractDeleteTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractEraseTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractExportTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractIncludeRevincludeTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractMultiResourceTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPagingTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractReverseChainTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractSortTest.java
- fhir-persistence/src/test/java/com/ibm/fhir/test/InterceptorTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BasicServerTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/DeleteTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchChainTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchIncludeTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchRevIncludeTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchReverseChainTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/MockPersistenceImpl.java
Our object model is immutable and so its safe to re-use the same
resources across all the tests. This could avoid I/O, parse, and parse
validation time each time its re-used.
I had originally designed TestUtil.getMinimalResource to accept a single
argument of type ResourceType. However, I've always regretted that
because the generic type is more useful if it can be gleaned from an
input argument of type class<T extends Resource> instead of forcing java
to try figuring it out based on the call context.
Finally, we had quite a few search tests that were using the 
`getMinimalResourceType(ResourceType, Format.JSON)` variant.
However, which format the resource we're reading from the examples jar
is in is quite irrelevant to the actual tests, so now these will use the single
argument flavor …
> add caching to TestUtil.getMinimalResource and standardize on this

- fhir-model/src/main/java/com/ibm/fhir/model/parser/FHIRJsonParser.java
- fhir-model/src/main/java/com/ibm/fhir/model/parser/FHIRParser.java
- fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java
* remove throws declaration from FHIRParser.parse javadoc...its always
wrapped in a FHIRParserException
* add javadoc for FHIRJsonParser parse(JsonObject) and parseAndFilter
methods
> minor javadoc updates

- fhir-install/src/main/docker/ibm-fhir-schematool/run.sh
> WHFFHIR-207 Write to a protected directory that is not needed, and fails when running SchemaTool/Db2 with a restricted user in openshift

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRPatchTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
When running a FHIR Patch operation using JsonPatch on a field
**Response**
Payload: {"resourceType":"OperationOutcome","id":"c0-a8-56-16-0a786fde-71f2-4de1-b932-db54b0ad5c35","issue":[{"severity":"error","code":"invalid","details":{"text":"Invalid patch: Non-existing name/value pair in the object for key active"},"expression":["<no-path>"]}]}
> issue-2712 NPE when using a JsonPatch Remove on an already removed Field

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/listener/StepChunkListener.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRDocumentOperationTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRPatchTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/OperationConstants.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/ConfigurationAdapter.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/V2ConfigurationImpl.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/PollingLocationResponse.java
- operation/fhir-operation-document/src/main/java/com/ibm/fhir/operation/document/DocumentOperation.java
- Bulk Export Status #2715
- Added a default Error
- Bulk Export Status Report #2714
- Added property for requiresAccessToken
- Composition reports a 500 when it's a bad user request #2717
- Mutate 500 to 400 in $document
- Add Test for $document when bad request
- add patch integration tests for Move and Copy to additionally confirm behaviors 
-  For the JSON Patch path for the test option, it is not handled correctly #2720 
- Skippable updates enabled for patch scenarios 
-  bulkdata preflight checks should verify output provider config #2709 
- put into an exception handling due to virtualhost and api host handling. 
> Minor Fixes

- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/ParameterDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/ParameterNameDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/ParameterTransactionDataImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/CodeSystemsCache.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/CodeSystemsCacheUpdater.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/ParameterNamesCache.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/ParameterNamesCacheUpdater.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/ResourceTypesCache.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/ResourceTypesCacheUpdater.java
These were largely replaced by JDBCIdentityCache and the JDBCIdentityCacheImpl.
A couple of the older caches are still used by live code, so we should only
deprecate them if we know that they aren't really needed.
For example, the ParameterNamesCache is used (transitively) from
JDBCIdentityCacheImpl.getParameterNameId.
> Deprecate our old static jdbc caches for future removal

- fhir-parent/pom.xml
- fhir-server/src/main/java/com/ibm/fhir/server/listener/FHIRServletContextListener.java
- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/FHIRTermGraph.java
- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/factory/FHIRTermGraphFactory.java
- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/impl/FHIRTermGraphImpl.java
- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/loader/impl/AbstractTermGraphLoader.java
- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/loader/impl/CodeSystemTermGraphLoader.java
- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/provider/GraphTermServiceProvider.java
- fhir-term-graph/src/test/java/com/ibm/fhir/term/graph/test/CodeSystemTermGraphLoaderTest.java
- fhir-term-graph/src/test/java/com/ibm/fhir/term/graph/test/GraphTermServiceProviderTest.java
- fhir-term-graph/src/test/java/com/ibm/fhir/term/graph/test/GraphTermServiceProviderTimeLimitTest.java
- fhir-term-graph/src/test/java/com/ibm/fhir/term/graph/test/SnomedGraphTermServiceProviderTest.java
The previous version included versions of jackson-databind and netty that had known vulnerabilities.
> Update to the latest janusgraph and gremlin

- .github/workflows/build.yml
- fhir-server/pom.xml
- fhir-term-graph/pom.xml
When we bumped to JanusGraph 0.6.0, our webapp went from 82MB to 126MB.
Most of this is from the `janusgraph-cql` module pulling in all of
Cassandra.
Since this is an experimental feature, I think it makes sense to require
user action to enable cassandra and elasticsearch options for graphs.
In our experience, the berkeleyje + lucene option performs better and is
easier to manage anyway.
Note: we don't actually have any compile-time dependencies on these
modules at this time, but I opted to mark the as provided (instead of
omitting them entirely) to make it as easy as possible to bring them back in.
This is similar to what we did with our optional Spark dependencies in
fhir-bulkdata-webapp.
> Mark janusgraph-cql and janusgraph-es as provided

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/PlanDefinitionApplyOperationTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/EraseOperationTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/ReindexOperationTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/operation/spi/AbstractOperation.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIROperationUtil.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ImportOperation.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/StatusOperation.java
- operation/fhir-operation-bulkdata/src/main/resources/import.json
- operation/fhir-operation-reindex/src/main/java/com/ibm/fhir/operation/reindex/ReindexOperation.java
- operation/fhir-operation-reindex/src/main/java/com/ibm/fhir/operation/reindex/RetrieveIndexOperation.java
- operation/fhir-operation-test/src/test/java/com/ibm/fhir/operation/test/MyOperation.java
Issue #2504 - Check affectsState
> Issue #2504 - Check affectsState

- build/docker/copy-server-config.sh
- build/docker/docker-compose.yml
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/context/BatchContextAdapter.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/patient/PatientExportPartitionMapper.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/system/SystemExportPartitionMapper.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ImportPartitionMapper.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/load/partition/transformer/impl/S3Transformer.java
- fhir-bulkdata-webapp/src/main/resources/META-INF/batch-jobs/FhirBulkExportFastJob.xml
- fhir-server/liberty-config/configDropins/defaults/bulkdata.xml
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/OperationConstants.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/action/batch/BatchCancelRequestAction.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/JobInstanceResponse.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/PollingLocationResponse.java
I found that the liberty implementation of java batch has a "feature"
where it only restarts partitions that have *not* completed
successfully.
Unfortunately, I couldn't find a simple way to get the ExitStatus of
successful partitions from previous executions and stuff those into the
ExitStatus of the latest execution.
Therefore, to get a complete list of partition results, it is necessary
for the status endpoint to aggregate the Exit Status of *all* of the
jobs executions for a particular job instance.
Previously we were only checking the last execution and that was leading
to confusing behavior where the status shows partial results from the
export (even though the entire job was completed).
> issue #2742 - aggregate exit status of all executions in bulkdata-status

- fhir-install/src/main/docker/ibm-fhir-server/bootstrap.properties
- fhir-model/src/main/java/com/ibm/fhir/model/util/XMLSupport.java
The javadocs say that these system properties are the first things consulted.
I think we shied away from relying on system properties for proper functionality in the past,
but with Java 17 around the corner it would be nice to remove the reflection here before it breaks.
If we drop java 8 support, we could possibly just use these methods instead:
* https://docs.oracle.com/en/java/javase/11/docs/api/java.xml/javax/xml/stream/XMLInputFactory.html#newDefaultFactory()
* https://docs.oracle.com/en/java/javase/11/docs/api/java.xml/javax/xml/stream/XMLOutputFactory.html#newDefaultFactory()
* https://docs.oracle.com/en/java/javase/11/docs/api/java.xml/javax/xml/transform/TransformerFactory.html#newDefaultInstance()
> issue #2266 - avoid reflection while instantiating XML factories

- fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/factory/FHIRTermGraphFactory.java
I accidentally used a placeholder "myconfig.properties" instead of the
propFileName argument when I switched over to apache commons config 2.
> cleanup after https://github.com/IBM/FHIR/pull/2755

- fhir-bucket/src/main/java/com/ibm/fhir/bucket/reindex/ClientDrivenReindexOperation.java
Same regression as a prior issue - same fix in this case. 
> fhir-bucket process should exit after reindex failure #2752

- fhir-server/liberty-config/configDropins/disabled/db2-cloud/bulkdata.xml
- fhir-server/liberty-config/configDropins/disabled/derby/bulkdata.xml
In the future, we may want to use this as the default instead of the default in-memory store because its better aligned with our default db config.
The biggest advantage is that the derby-backed store supports delete (purge) whereas the in-memory store does not.
> introduce disabled configDropin for a derby-backed job repository

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/ConcurrentEraseUpdateTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/concurrent/InteractionFactory.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/EraseOperationTest.java
Introduced an Interaction Factory with a public final class to support Concurrent Tests which mix a number of various test cases so we can test the locking.  Good news is that it worked properly and the concurrency didn't show any deadlock situations with the test (it's a very aggressive test and can be tuned up or down appropriately).
> Potential race condition when create overlaps with erase (hard-delete) #2454

- fhir-cache/src/main/java/com/ibm/fhir/cache/CacheManager.java
- fhir-cache/src/test/java/com/ibm/fhir/cache/test/FHIRCacheManagerTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/registry/ServerRegistryResourceProvider.java
- fhir-server/src/main/java/com/ibm/fhir/server/resolve/ServerResolveFunction.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
- fhir-term/src/main/java/com/ibm/fhir/term/util/CodeSystemSupport.java
- Added CacheStats hooks to the CacheManager.getCache callers
- Adding logging trace string to activate:
- Cache on the Capabilities class
com.ibm.fhir.server.resources.Capabilities=finest
- Server Registry provider
:com.ibm.fhir.server.registry.ServerRegistryResourceProvider=finest
- paired with the CacheManager stats guard
com.ibm.fhir.cache.CacheManager=fine
- The intent of the pairing means that meaningless CacheManager stats
are not dumped into the sysout syserror (the output is at the FINE
level)
Examples of the output:
- initial load
```
[9/23/21, 15:50:02:900 UTC] 00000038 Capabilities  1   CacheStats for
'com.ibm.fhir.server.resources.Capabilities.statementCache'
averageLoadPenalty=[0.0],evictionCount=[0],hitCount=[0],hitRate=[1.0],loadCount=[0],missCount=[0],requestCount=[0],miss …
```
> Investigate cache stats / cache management #2733

- fhir-config/src/main/java/com/ibm/fhir/config/PropertyGroup.java
- fhir-config/src/test/java/com/ibm/fhir/config/test/FHIRConfigHelperTest.java
- fhir-config/src/test/java/com/ibm/fhir/config/test/PropertyGroupTest.java
- fhir-config/src/test/resources/config/default/fhir-server-config.json
- fhir-server/src/main/java/com/ibm/fhir/server/registry/ServerRegistryResourceProvider.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Previously, we'd throw an IllegalStateException if we encountered a
null value. This came up because the helm `toJson` function produces all
possible fields for an object, even when some are null.
Additionally, if we have an invalid config (such as described above), in
FHIRRestHelper.validateResource we were swallowing the underlying
exception and instread constructing a generic OperationOutcomeIssue with
message "Error retrieving profile configuration". This meant we were missing
the root cause in our logs and also meant that this exception was being handled
just like any other validation error and so, even though it was a server
config issue, this was not clear to the client.
> Handle null values in fhir-server-config and throw for exceptional case

- fhir-parent/pom.xml
It seems like depend-a-bot is only opening PRs for dependencies with their versions inlined in fhir-parent/pom.xml
so I drafted these changes to help dependabot  help us...but first we should probably confirm the assumption
> inline version vars

- fhir-audit/pom.xml
- fhir-audit/src/main/java/com/ibm/fhir/audit/impl/KafkaService.java
- fhir-parent/pom.xml
- Need to make a slight code change and dependency change. 
- Added slf4j-api to fhir-audit
- KafkaService - Change timeout to use Duration.of 
> Move kafka-clients from 2.8.1 to 3.0.0 #2923

- fhir-parent/pom.xml
- fhir-search/pom.xml
- fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersMap.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/MultiTenantSearchParameterTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/ParametersMapTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/ParametersSearchUtilTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/ParametersUtilTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/ExtractParameterValuesTest.java
- fhir-search/src/test/resources/config/tenant4/fhir-server-config.json
- fhir-search/src/test/resources/config/tenant5/fhir-server-config.json
To make this simpler, I also updated the way we apply the filter rules.
Note: this changeset introduces the fhir-ig-us-core as a test dependency for
fhir-search. This was strictly out of convenience...the alternative
would be to create a new test-only PackagedRegistryResourceProvider that
provides multiple versions of the same search parameter(s).
> Issue 2843 - store both versioned and unversioned canonicals in ParametersMap

- .github/workflows/build.yml
- fhir-model/src/test/java/com/ibm/fhir/model/spec/test/R4ExamplesDriver.java
- fhir-search/pom.xml
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/MultiTenantSearchParameterTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/ParametersSearchUtilTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/ExamplesDriverTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/SampleRegistryResourceProvider.java
- fhir-search/src/test/resources/META-INF/services/com.ibm.fhir.registry.spi.FHIRRegistryResourceProvider
- fhir-search/src/test/resources/config/tenant4/fhir-server-config.json
- fhir-search/src/test/resources/config/tenant5/fhir-server-config.json
- term/fhir-term/src/main/java/com/ibm/fhir/term/util/ValueSetSupport.java
With a SampleRegistryResourceProvider that contains multiple versions of
a dummy search parameter.
> Replace the fhir-search test dependency on US Core

- fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/InputOutputByteStream.java
- fhir-persistence/src/test/java/com/ibm/fhir/test/InputOutputByteStreamTest.java
- Add mark/reset to the InputStream
- Add Test for mark/reset
> ByteInputStream does not implement mark/reset #2940

- fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java
> Audit record for PUTs should not always use "Update" #2471

- operation/fhir-operation-everything/src/main/java/com/ibm/fhir/operation/everything/EverythingOperation.java
> Stop swallowing exceptions in the $everything operation

- operation/fhir-operation-member-match/src/main/java/com/ibm/fhir/operation/davinci/hrex/provider/MemberMatchFactory.java
- operation/fhir-operation-member-match/src/test/java/com/ibm/fhir/operation/davinci/hrex/test/MemberMatchTest.java
- MemberMatchFactory should throw custom exception when Strategy is not found
> MemberMatchFactory should throw custom exception when Strategy is not found

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ChunkWriter.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ImportOperationTest.java
- operation/fhir-operation-member-match/src/main/java/com/ibm/fhir/operation/davinci/hrex/provider/strategy/DefaultMemberMatchStrategy.java
1 - Regression on $import - Bulk Data Import skipping a resource marked
deleted #2958 (https://github.com/IBM/FHIR/commit/3d877c59542#diff-ad9adffb91185e4b3058adfc485a5a90f173fbd23b223afd39dbaba9fb7911f4R222 introduced the regression as `delete status` is not checked)
2 - Fix for edge case when no identifier exists in MemberMatch
> Two Fixes - MemberMatch and BulkData Regression

- fhir-examples/pom.xml
- fhir-parent/pom.xml
I guess `additionalparam` went away with javadoc plugin 3.0.0.
In Eclipse its just a warning, but in IDEA its an error (by default).
> remove outdated property

- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaVersion.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/MigrateV0021AbstractTypeRemoval.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/UnusedTableRemovalNeedsV0021Migration.java
- fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/derby/DerbySchemaVersionsTest.java
> issue 2979 fix schema version tracking regression

- fhir-search/src/test/java/com/ibm/fhir/search/date/DateTimeHandlerTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/ChainParameterParseTest.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/RevChainParameterParseTest.java
Issue #2981 - Update testcases to handle date with 0 milliseconds field
> Issue #2981 - Update testcases to handle date with 0 milliseconds field

- .github/workflows/audit.yml
- .github/workflows/build.yml
- .github/workflows/integration.yml
- .github/workflows/javadocs_force_build.txt
- .github/workflows/migration.yml
- .github/workflows/notification.yml
- .github/workflows/persistence.yml
- .github/workflows/reindex.yml
- .github/workflows/windows.yml
With multiple commits to the same branch, we hit... 
```
e2e-db2-with-bulkdata (11)
Canceling since a higher priority waiting request for 'integration-3014' exists
```
> Automation: Add Concurrency Controls to GitHub Workflow Actions #3013

- docs/package.json
- docs/yarn.lock
json-schema is vulnerable to Improperly Controlled Modification of Object Prototype Attributes ('Prototype Pollution')
> docs update only

- fhir-search/src/test/java/com/ibm/fhir/search/parameters/ParametersUtilTest.java
this setting gates a lot of output and I had accidentally set it to true in the build, producing lots of noise
> turn off DEBUG in ParametersUtilTest

- docs/src/pages/guides/FHIRServerUsersGuide.md
Add known limitation for fhir-persistence interceptor to the BulkData section. 
> bulkdata: Add known limitation for fhir-persistence interceptor

- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/util/FHIRRestHelperTest.java
FHIRRestHelper.performSearchReferenceChecks showed up as a hot spot on a
recent profiling exercise.  I think we can add some simple checks to
avoid most of the work in this method for most cases, so I prototyped
that here.  Needs evaluation.
> Perf improvement - guard FHIRPath evaluation during search interaction

- fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRHttpServletRequestWrapper.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Search.java
1. We had an undocumented / untested feature where you can override the
HTTP method via a header. This changeset removes that. CXF has a
slightly different header for doing exactly the same thing. Not sure
about RESTEasy.
2. We had a whole lot of unnecessary override methods in
FHIRHttpServletRequestWrapper. Since the parent class defaults to
calling the delegate already, its cleaner to leave those out of this
subclass.
3. Committing minor edits to the JAX-RS Search resource...it doesn't
actually consume APPLICATION_FHIR media types in any of the methods and
there's no need to override the class-level path with the same value
> Remove undocumented feature for overriding the http method via header and related cleanup

- fhir-model/src/main/java/com/ibm/fhir/model/util/XMLSupport.java
- fhir-persistence-schema/README.md
> issue 3044 - use correct TransformerFactory impl class

- fhir-parent/pom.xml
somehow I missed this one when I edited our parent pom and validation didn't catch it
> fix unresolved version var

- fhir-validation/src/test/java/com/ibm/fhir/validation/test/FHIRValidatorTest.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/MaxValueSetTest.java
- term/fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
- term/fhir-term/src/main/java/com/ibm/fhir/term/service/ValidationOutcome.java
- term/fhir-term/src/test/java/com/ibm/fhir/term/service/test/FHIRTermServiceTest.java
Two main changes:
* split Coding display validation logic into its own separate private method `FHIRTermService.validateDisplay`
* build the ValidationOutcome with an appropriate message when we first know the response instead of passing it around
> beef up error messages in the FHIRTermService

- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/CarinBlueButtonV100Test.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/CarinBlueButtonV110Test.java
Two of these tests were sensitive to the resources on the system.
This is a quick fix to make them less sensitive, but a more thoughtful
approach would be to remove the problem altogether.
> bandaid for senstivie CARIN BB search tests

- conformance/fhir-ig-davinci-pdex/src/test/java/com/ibm/fhir/ig/davinci/pdex/test/ProvenanceValidationTest.java
- fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
- fhir-path/src/test/java/com/ibm/fhir/path/test/MemberOfFunctionTest.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/MaxValueSetTest.java
For extensible and preferred binding we now emit failed membership check issues with a
severity of INFORMATION instead of WARNING.
> Reduce severity of failed membership checks

- term/fhir-term-graph-loader/pom.xml
Excluded Three Dependencies which are not used
> Sonatype lift reports three vulnerabilities on fhir-term-graph-loader #3067

- fhir-parent/pom.xml
its only a provided dependency, but there's a few vulnerabilities in the transitive dependencies for 3.1.0.
dependabot opened this for it in the past https://github.com/IBM/FHIR/pull/2985 ...we closed but I forget why
> bump spark-sql version to 3.2.0

- docs/src/pages/guides/DB2OnCloudSetup.md
This is for additional information for making it more clear what to do to configure DB2 with IBM FHIR server.
Signed-off-by: Dag Roppe <roppe@us.ibm.com>
> Clarifications for DB2 connection for FHIR

- conformance/fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/v100/ProviderTest.java
- conformance/fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/v110/ProviderTest.java
- conformance/fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/v311/ProviderTest.java
- conformance/fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/v400/ProviderTest.java
Karen is opening the issue for this one.  testConstraintGenerator not targetting intended version #3095 
She discovered this during testing, and we did a screenshare to diagnose.
> Update Test to use the specific version

- fhir-server-webapp/src/main/webapp/META-INF/microprofile-config.properties
it was scanning the dependencies, using the trace I found:
`org.jboss.*=FINE:io.openliberty.microprofile.*=FINE`
```
[12/8/21, 0:53:23:733 UTC] 00000032 ApplicationRe 1   Application Processor: Adding application started: appInfo=com.ibm.ws.container.service.app.deploy.internal.ApplicationInfoImpl@63b34b5c[fhir-server]
[12/8/21, 0:53:23:733 UTC] 00000032 ApplicationPr 1   Application Processor: Processing application started: appInfo=com.ibm.ws.container.service.app.deploy.internal.ApplicationInfoImpl@63b34b5c[fhir-server]
[12/8/21, 0:53:23:733 UTC] 00000032 ApplicationPr 1   WebModule: Processing started : deploymentName=fhir-server-webapp : contextRoot=/fhir-server/api/v4
[12/8/21, 0:53:23:746 UTC] 00000032 OLSmallRyeCon 1   Config created with profile: null …
```
> ArrayIndexOutOfBoundsException during startup (while running in dev mode) #3092

- fhir-client/pom.xml
- fhir-client/src/main/java/com/ibm/fhir/client/impl/FHIRClientImpl.java
- fhir-parent/pom.xml
- fhir-server-test/pom.xml
- Turns out the LoggingFeature is moved and slightly different
- Updated to make it work, and not-use the deprecated feature
> CXF LoggingFeature is deprecated, and it'd be nice to move the fhir-client to the latest approach #2453

- CONTRIBUTING.md
the template was like `issue #<number> - short description` but the `<number>` bit wasn't visible on the page (stripped due to looking like an xml tag)
> update convention template to avoid string that looks like xml element

- conformance/fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/tool/CapabilitiesToConfigGeneratorMain.java
- conformance/fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/tool/LiveCapabilitiesToConfigGeneratorMain.java
- conformance/fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/tool/CapabilitiesToConfigGeneratorMain.java
- fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersUtil.java
- This class processes the Live CapabilityStatements to fhir-server-config.json.
- The output is to the sysout, and the user is expected to specify default versions.
- java LiveCapabilitiesToConfigGeneratorMain
http://hl7.org/fhir/us/core/|3.1.1,http://hl7.org/fhir/us/carin-bb/|1.0.0
- Fix this error message in ParametersUti 1   Skipping search
parameter 'http://hl7.org/fhir/us/core/SearchParameter/us-core-observation-patient|4.0.0' because code '{  "code": "patient" }' is already configured. so it's not split
> Small Utility to Live Convert Capability Statements to fhir-server-config.json

- conformance/fhir-ig-carin-bb/CHANGELOG
- conformance/fhir-ig-carin-bb/src/main/resources/hl7/fhir/us/carin-bb/110/package/StructureDefinition-C4BB-ExplanationOfBenefit.json
- conformance/fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/v110/ProviderTest.java
C4BB-ExplanationOfBenefit warning received - constraint not generated #3096
- small limit on the C4BB warning... as the discriminator isn't different when there is no pattern to match
> C4BB-ExplanationOfBenefit warning received - constraint not generated #3096

- docs/src/pages/Conformance.md
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfigHelper.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/EverythingOperationTest.java
- operation/fhir-operation-everything/src/main/java/com/ibm/fhir/operation/everything/EverythingOperation.java
- operation/fhir-operation-everything/src/test/java/com/ibm/fhir/operation/everything/EverythingOperationTest.java
- Fixed issue where Patient $everything returned "Error retrieving $everything resources of type 'Appointment' for patient" when config has the list of resource types restricted
- Fixed issue where Patient $everything wasn't reading tenant-specific config 
- Tested on our tenant-specific config server that a test patient resource was returned along with the related EOB and Coverage resources
Signed-off-by: Susan Crowell sfc@us.ibm.com
> Fix issues with Patient $everything #2963

- docs/src/pages/guides/FHIRServerUsersGuide.md
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/ConfigurationAdapter.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/V2ConfigurationImpl.java
- Adjustment on how the accessToken's are handled or indicated.
- False is the default, and ensures that presigned is not set.
> AccessTokens should not be set with Presigned URLs #3188

- cql/fhir-cql/src/main/java/com/ibm/fhir/cql/helpers/LibraryHelper.java
- cql/fhir-quality-measure/src/main/java/com/ibm/fhir/ecqm/r4/MeasureHelper.java
- cql/operation/fhir-operation-cpg/src/main/java/com/ibm/fhir/operation/cpg/AbstractCqlOperation.java
- cql/operation/fhir-operation-cpg/src/main/java/com/ibm/fhir/operation/cpg/CqlOperation.java
- cql/operation/fhir-operation-cpg/src/main/java/com/ibm/fhir/operation/cpg/ParameterConverter.java
- cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/AbstractDataRequirementsOperation.java
- cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/AbstractMeasureOperation.java
- cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/CareGapsOperation.java
- cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/EvaluateMeasureOperation.java
- cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/MeasureDataRequirementsOperation.java
- cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/MeasureSubmitDataOperation.java
- cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/OperationHelper.java
- cql/operation/fhir-operation-cqf/src/test/java/com/ibm/fhir/operation/cqf/BaseDataRequirementsOperationTest.java
- cql/operation/fhir-operation-cqf/src/test/java/com/ibm/fhir/operation/cqf/EvaluateMeasureOperationTest.java
- cql/operation/fhir-operation-cqf/src/test/java/com/ibm/fhir/operation/cqf/MeasureDataRequirementsOperationTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/cqf/BaseMeasureOperationTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/cqf/ServerEvaluateMeasureOperationTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/cqf/ServerMeasureCollectDataOperationTest.java
- fhir-server-test/src/test/resources/testdata/Measure-MissingLibrary.json
- fhir-server-test/src/test/resources/testdata/Measure-NoLibrary.json
I applied a fix before the holiday that corrected a category of NPE
errors related to execution against measure or library resources that
don't exist. It turns out that wasn't the core of the issue 3061. This
goes back and addresses when a valid measure reference is used, but that
Measure refers to a Library resource that does not exist. I also added
some handling that allows resolution of Library resources by reference
in addition to by canonical URL in the registry and also updated the
error handling around retrieving the primary library reference from the
Measure resource.
Signed-off-by: Corey Sanders <corey.thecolonel@gmail.com>
> #3061 - Fix NPE when Measure refers to non-existent library

- fhir-audit/src/main/java/com/ibm/fhir/audit/mapper/impl/AuditEventMapper.java
- fhir-audit/src/main/java/com/ibm/fhir/audit/mapper/impl/CADFMapper.java
- Timing of start/end leads to Outcome.pending to be reported
- It should be success/failure rather then pending
- I traced through the code and think it might have been a method to filter out fast running operations and snuck into the code. We set endTime/startTime on every request.
> Erroneous reporting of Pending Outcome in Audit #3204

- fhir-bucket/src/main/java/com/ibm/fhir/bucket/app/Main.java
- fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/schema/SchemaVersionsManager.java
- fhir-database-utils/src/test/java/com/ibm/fhir/database/utils/schema/DerbySchemaVersionsTest.java
- fhir-persistence-schema/README.md
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/menu/Menu.java
- fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/derby/DerbySchemaVersionsTest.java
Also added `--force` option which will cause the schema upgrade steps to be performed (partially bypassing the whole-schema-version check) but only if the code schema version is equal to the database schema version. Note that if the database schema version is behind the code schema version, you don't need `--force` because the changes will be applied anyway.
> issue #3032 only update when current schema is behind code version

- .github/workflows/rebuild.yml
attempt number 2 to fix the rebuild workflow
because i'm checking out the tagged version, it doesn't have our updated release script.
so we need to either copy/move the logic of those scripts into the action or patch them in place...I chose the latter.
> patch the release script to avoid bad test

- cql/operation/fhir-operation-cpg/src/main/java/com/ibm/fhir/operation/cpg/AbstractCqlOperation.java
- cql/operation/fhir-operation-cpg/src/main/java/com/ibm/fhir/operation/cpg/CqlOperation.java
- cql/operation/fhir-operation-cpg/src/main/java/com/ibm/fhir/operation/cpg/LibraryEvaluateOperation.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/cpg/ServerCqlOperationTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/cqf/ServerEvaluateMeasureOperationTest.java
The CQL operations were wrapping the exception from the CQL engine in a
FHIROperationException and assuming that the nested exception would
automatically be included in the issues list which isn't the case at
all. I added logic to manually add the details from the CQLException to
the issues list so that it shows up in the OperationOutcome.
Signed-off-by: Corey Sanders <corey.thecolonel@gmail.com>
> #3195 - Bubble up exception message from CQL engine

- build/pre-integration-test.sh
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/DavinciHealthRecordExchangeTest.java
- operation/fhir-operation-member-match/src/main/java/com/ibm/fhir/operation/davinci/hrex/provider/strategy/DefaultMemberMatchStrategy.java
- During the Bundle behavior refactoring, the Bundle.Entry.id is no longer populated. The member-match needs this id (which was a proxy for the Resource.id). 
- The code change redirects to Resource.id. 
- The shell script change makes sure we test Member-Match
> Bundle Change impacted the member-match behavior. #3212

- fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersUtil.java
search parameter doesn't exist
Signed-off-by: Susan Crowell <sfc@us.ibm.com>
> Issue 3219 - issue warning statement when an explicitly-configured

- .github/workflows/rebuild.yml
- build/release/bin/20_test/1_code_coverage.sh
attempt number 3 to fix the rebuild workflow
the previous run is failing with an error like this:
> 2022-01-20T07:21:43.0000022Z [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project fhir-openapi: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.) -> [Help 1]
> tell maven its ok if some modules have no tests

- fhir-parent/pom.xml
- fhir-server-test/pom.xml
- fhir-server/pom.xml
- term/fhir-term-graph/pom.xml
- Remove unused surface area. 
- Address 
fhir-persistence-blob:
kotlin-stdlib-1.3.72.jar (pkg:maven/org.jetbrains.kotlin/kotlin-stdlib@1.3.72, cpe:2.3:a:jetbrains:kotlin:1.3.72:*:*:*:*:*:*:*) : CVE-2020-29582
kotlin-stdlib-common-1.3.70.jar (pkg:maven/org.jetbrains.kotlin/kotlin-stdlib-common@1.3.70, cpe:2.3:a:jetbrains:kotlin:1.3.70:*:*:*:*:*:*:*) : CVE-2020-29582
- also an issue in bulkdata.
> Update to clean up the dependency trees

- fhir-examples/pom.xml
- Updating the plugins saves 10 seconds in the build. 
- Also useful to stay up to date. 
> Update to fhir-examples consistent with updated plugins

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchQuery.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractWholeSystemSearchTest.java
example from test:
```
runQueryTest(Resource.class, "_type", "Basic,EvidenceVariable,ServiceRequest")`
```
before:
```
SELECT LR0.RESOURCE_TYPE_ID, LR0.LOGICAL_RESOURCE_ID 
FROM LOGICAL_RESOURCES AS LR0
WHERE LR0.IS_DELETED = 'N'
AND LR0.RESOURCE_TYPE_ID IN (8,52,126)
AND EXISTS (
SELECT 1 
FROM LOGICAL_RESOURCES AS LR1
WHERE LR1.LOGICAL_RESOURCE_ID = LR0.LOGICAL_RESOURCE_ID)
ORDER BY LR0.LOGICAL_RESOURCE_ID
FETCH FIRST 10 ROWS ONLY
```
after:
```
SELECT LR0.RESOURCE_TYPE_ID, LR0.LOGICAL_RESOURCE_ID 
FROM LOGICAL_RESOURCES AS LR0
WHERE LR0.IS_DELETED = 'N'
AND LR0.RESOURCE_TYPE_ID IN (8,52,126)
AND EXISTS (
SELECT 1 
FROM LOGICAL_RESOURCES AS LR1
WHERE LR1.LOGICAL_RESOURCE_ID = LR0.LOGICAL_RESOURCE_ID
AND LR0.RESOURCE_TYPE_ID IN (8,52,126))
ORDER BY LR0.LOGICAL_RESOURCE_ID
FETCH FIRST 10 …
```
> issue #3232 - add resourceType IN where clause to whole-system search subquery

- build/audit/kafka/docker-compose.yml
- build/derby-bootstrap.sh
- build/docker/docker-compose.yml
- build/migration/db2/4_current-migrate.sh
- build/migration/postgres/4_current-migrate.sh
- build/notifications/kafka/docker-compose.yml
- build/persistence/postgres/docker-compose.yml
- build/pre-integration-test.ps1
- build/pre-integration-test.sh
- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/EverythingOperationTenant1Test.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/EverythingOperationTest.java
- fhir-server-test/src/test/resources/testdata/everything-operation/Antonia30_Acosta403.json
- fhir-server-test/src/test/resources/testdata/everything-operation/Patient999.json
- fhir-server/liberty-config-tenants/config/tenant1/fhir-server-config.json
- operation/fhir-operation-everything/src/main/java/com/ibm/fhir/operation/everything/EverythingOperation.java
Add search for related resources and make extra resources in patient $everything configurable
Signed-off-by: Susan Crowell <sfc@us.ibm.com>
> Add search for related resources and make extra resources in patient $everything configurable

- operation/fhir-operation-member-match/src/main/java/com/ibm/fhir/operation/davinci/hrex/provider/strategy/DefaultMemberMatchStrategy.java
- Facilitate throwing the actual exception
> $member-match should throw FHIROperationException instead of rewrapping the exception #3298

- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/util/FHIRRestHelperTest.java
Issue #3276 - now both resource and prevResource should be available in the beforeDelete method, preventing the NPE.
Signed-off-by: Jorn van Wier <mail@jornvanwier.com>
> Issue #3276 - Set both resource and prevResource for beforeDelete event in FHIRRestHelper

- fhir-config/src/main/java/com/ibm/fhir/config/ResourcesConfigAdapter.java
- fhir-core/src/main/java/com/ibm/fhir/core/FHIRVersionParam.java
- fhir-core/src/main/java/com/ibm/fhir/core/ResourceTypeName.java
- fhir-core/src/main/java/com/ibm/fhir/core/util/ResourceTypeHelper.java
- fhir-core/src/test/java/com/ibm/fhir/core/util/test/ResourceTypeHelperTest.java
- fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/PopulateResourceTypes.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/FHIRPersistenceUtil.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
- fhir-server-spi/src/main/java/com/ibm/fhir/server/spi/operation/FHIRResourceHelpers.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Replace getNewOrBreakingResourceTypeNames() with a more
generic `isCompatible(resType, fhirVersion1, fhirVersion2)` method.
To implement it, I introduced new members to the ResourceTypeName enums
so that we can compute which resource types are associated with which
FHIR versions.
The compatibility knowledge is still encapsulated in
ResourceTypeHelper, but now we more cleanly distinguish between
R4B_ONLY_RESOURCE_TYPES and BACKWARD_BREAKING_R4B_ENUMS (previously they
were both together in the R4B_ONLY_RESOURCE_TYPES list). And now we have
a way to get the inverse (valid 4.3 resources that maybe not be valid in
4.0), although this isn't currently used by the server.
> Refactor ResourceTypeHelper and update callers

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchQuery.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchWholeSystemFilterQuery.java
Previously, we were adding this extra IN clause for the _type parameter
in all cases.
In the case of a whole-system search *count* query, this was slowing
things down a bit. We still add the IN clause to the query where it
seemed to help, but now we avoid that for the count query.
> issue #3232- add the extra IN clause more selectively

- fhir-server-webapp/src/main/liberty/config/configDropins/disabled/db2-cloud/bulkdata.xml
- fhir-server-webapp/src/main/liberty/config/configDropins/disabled/db2/bulkdata.xml
- fhir-server-webapp/src/main/liberty/config/configDropins/disabled/postgres/bulkdata.xml
- add validationTimeout=30s to the bulkdata datasources
>  Datasource hits an I/IO exception with bulkdata datasource #3039

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/audit/BulkAuditLogger.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ChunkWriter.java
- Switched the conditionalUpdate to skip and pass in the oldResource as
- they exactly match rather than the Meta updated version with the unused new version
- update the Create to ignore the Version when passed in
- Enable the Version on Update by using the Create with Version.
- Refactor the BulkAuditLogger to eliminate the dual resource usage
> Bulk Data Import with missing 'id' on Audit #3016

- build/audit/kafka/docker-compose.yml
- build/derby-bootstrap.sh
- build/docker/docker-compose.yml
- build/migration/db2/2_compose.sh
- build/migration/db2/4_current-migrate.sh
- build/migration/postgres/2_compose.sh
- build/migration/postgres/4_current-migrate.sh
- build/notifications/kafka/docker-compose.yml
- build/persistence/postgres/docker-compose.yml
- build/pre-integration-test.ps1
- build/pre-integration-test.sh
- fhir-server-webapp/src/test/liberty/config/config/tenant1/fhir-server-config.json
- operation/fhir-operation-everything/src/main/java/com/ibm/fhir/operation/everything/EverythingOperation.java
1. Use SearchUtil.getSearchParameters(compartmentMemberType) instead of loading them from the ParametersUtil
2. Change the tenant1 fhir-server-config to use `"open": false`, otherwise the set of supportedResourceTypes includes types that aren't actually included in the db schema (e.g. Appointment)
3. Added in other fhirServer/resources resource configs as needed by the e2e tests
> EverythingOperation fixup

- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
- missing null return, otherwise it hits an empty pollingresponse.
Unfortunately, this depends on calls to the batch framework underneath to test, and is not ideal for Unit or Integration Test.
> bulk data delete followed by status caused no output #3034

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ImportPartitionAnalyzer.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/data/ImportCheckPointData.java
ImportPartitionAnalyzer - modify the infly rate reporting message and changed the message to report out Resources/second and report which  workitem is triggering the message.
Improve accuracy of the infly rate calculation
Sample Message: 
```
[INFO ] Import in-fly rate:
[286/286/r4_AllergyIntolerance.ndjson/AllergyIntolerance]
reportingThreshold=[2000] resources imported in 12610 milliseconds,
ImportRate: [0.064] Resources/milliseconds
Instance/Execution/File/ResourceType threshold milliseconds and
rate.
```
> ImportPartitionAnalyzer not reporting infly rate on threshold #3000

- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/PollingLocationResponse.java
- operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/model/PollingLocationResponseTest.java
- Update polling response to match http://hl7.org/fhir/uv/bulkdata/export.html#response---complete-status
- Ensure conformance with anticipated `deleted` array.
> Bulk Data 2.0.0 Export Response needs updates to PollingLocationResponse #3087

- cql/fhir-cql/src/main/java/com/ibm/fhir/cql/engine/model/FHIRModelResolver.java
- cql/fhir-cql/src/test/java/com/ibm/fhir/cql/engine/model/FHIRModelResolverTest.java
- cql/operation/fhir-operation-cpg/src/test/java/com/ibm/fhir/operation/cpg/CqlOperationTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/cpg/ServerCqlOperationTest.java
We found while testing the EXM104 measure from the fhir401 connectathon repo that when the CQL tries to reference the Resource.id field (such as in `[Encounter] e return Last(Split(e.id,'/'))`) that we would get an error saying could not resolve function 
FHIRHelpers.ToString(java.lang.String). The core problem is that the IBM FHIR model implements Resource.id as java.lang.String and the HAPI model which is used as the reference for the CQL implementation defines Resource.id as a FHIR.String. The CQL translator automatically inserts a FHIRHelpers.ToString into the ELM whenever Resource.id is used and the only way around that would be to create a complete new modelinfo and I don't really want to do that, so I patched our ModelResolver to do the type conversion to FHIR String whenever an …
> Patch ModelResolver to return Resource.id as FHIR.string

- fhir-model/src/main/java/com/ibm/fhir/model/util/FHIRUtil.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/UpdateIfNoneMatchTest.java
- fhir-server/src/test/java/com/ibm/fhir/server/util/FHIRRestHelperTest.java
Issue #2999 - Omit OperationOutcome issue fields with no useful value
> Issue #2999 - Omit OperationOutcome issue fields with no useful value

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/S3Provider.java
- fhir-server/pom.xml
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ImportOperation.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/S3ClientGenerator.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/AbstractSystemConfigurationImpl.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/Preflight.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/S3Preflight.java
- Move the Client Generation to the Server (AmazonS3) 
- Added cos to the fhir-server/pom.xml 
- Enhanced preflight with a write check 
- Example warning that occurs with the operation now (storageProvider id/bad
bucketName)
```
{
"resourceType": "OperationOutcome",
"id": "c0-a8-56-25-977e7573-20c9-4a0b-ba92-b07e640ddc1c",
"issue": [
{
"severity": "error",
"code": "exception",
"diagnostics": "The bucket does not exist
&#39;minio/fhirbulkdataxx&#39;"
}
]
}
```
And 
https://github.com/IBM/FHIR/issues/3003
- Relaxed the S3Preflight to support http connection with warning
```
MSG: BulkData Request is using a provider that connects to an
insecure url: http://bucket.bucket:9000/
```
- Improved the Response Handling to capture the ex and package it back up the stack
> bulkdata preflight checks should verify output provider config #2709

- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/FilePreflight.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java
- operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/FilePreflightTest.java
- operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtilTest.java
- added a check for result = empty and added supportedResourceTypes
- added small fix to FilePreflight to this commit
> Issue with QA on #3083

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/context/BatchContextAdapter.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ChunkReader.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ChunkWriter.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ImportPartitionCollector.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/data/ImportCheckPointData.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/data/ImportTransientUserData.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/Provider.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/AzureProvider.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/FileProvider.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/S3Provider.java
- fhir-bulkdata-webapp/src/main/resources/META-INF/batch-jobs/FhirBulkImportChunkJob.xml
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ExportOperation.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/V2ConfigurationImpl.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java
- operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtilTest.java
- Enabled OperationOutcomes to be Recorded for S3
- Added Prefixes to the Outcomes
- Added to the BatchContextAdapter to propagate the prefixes.
- Switched the default to disable operationoutcomes
- Support outcomes for Azure, File, S3
- Add Success Outcomes
> Bulk Data import fails when disableOperationOutcomes is false #2910

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
Issue #3336 - $healthcheck warning when deployment update required
> Issue #3336 - $healthcheck warning when deployment update required

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
originally I had this at a WARNING level, but then I realized its an expected/normal case and so I meant to flip it to FINE but only did half the job
this PR changes it to FINER since we see a lot of these messages during ingestion if level=FINE
> reduce log level for non-error case

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/context/FHIRPersistenceEvent.java
- fhir-server-spi/src/main/java/com/ibm/fhir/server/spi/operation/FHIRResourceHelpers.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestBundleHelper.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java
- operation/fhir-operation-erase/src/test/java/com/ibm/fhir/operation/erase/mock/MockFHIRResourceHelpers.java
- operation/fhir-operation-member-match/src/test/java/com/ibm/fhir/operation/davinci/hrex/test/MemberMatchTest.java
Issue #2300 - Add calls to beforeHistory and afterHistory
1. System-level history: Requires `user/*.read` or `system/*.read` authority
Example: https://localhost:9443/fhir-server/api/v4/_history
1. System-level history (with `_type` parameter): Requires `user/<resource_type>.read` or `system/<resource_type>.read` authority to each resource type in the `_type` parameter.
Example: https://localhost:9443/fhir-server/api/v4/_history?_type=Patient,Observation
1. Type-level history: Requires `user/<resource_type>.read` or `system/<resource_type>.read` authority to the resource type.
Example: https://localhost:9443/fhir-server/api/v4/Patient/_history
> Issue #2300 - Add calls to beforeHistory and afterHistory

- fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java
Addresses NPE
[3/4/22, 12:21:15:842 UTC] 00000051 com.ibm.fhir.server.resources.Batch                          E An error occurred while writing the audit log message.
java.lang.NullPointerException
at com.ibm.fhir.server.util.RestAuditLogger.logBundleBatch(RestAuditLogger.java:470)
at com.ibm.fhir.server.util.RestAuditLogger.logBundle(RestAuditLogger.java:368)
at com.ibm.fhir.server.resources.Batch.bundle(Batch.java:105)
at com.ibm.fhir.server.resources.Batch$Proxy$_$$_WeldClientProxy.bundle(Unknown Source)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java: …
> Update Rest Audit Logger

- docs/src/pages/guides/FHIRPerformanceGuide.md
- docs/src/pages/guides/FHIRSearchConfiguration.md
- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchHelper.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/CompartmentParseQueryParmsTest.java
- fhir-search/src/test/resources/config/tenant2/fhir-server-config.json
- fhir-server-webapp/src/main/liberty/config/config/default/fhir-server-config.json
This compatibility config property is from 4.5.1 and its time to
remove this optionality from the code.
Also updated tests and docs.
> issue #2886 - remove useStoredCompartmentParam property

- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/patient/PatientExportPartitionMapper.java
- fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/system/SystemExportPartitionMapper.java
- fhir-server-webapp/src/main/liberty/config/config/default/fhir-server-config-db2.json
- fhir-server-webapp/src/main/liberty/config/config/default/fhir-server-config.json
- Optimization to keep from establishing unnecessary Partitions. 
- Change the Defaults to match the actual fhir-server defaults.
> Update BulkData 2.0.0: Update the OperationDefinitions and CapabilityStatement #3082 

- docs/src/pages/guides/FHIRSearchConfiguration.md
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractCompartmentTest.java
- fhir-search/src/main/java/com/ibm/fhir/search/compartment/CompartmentHelper.java
- fhir-search/src/main/java/com/ibm/fhir/search/util/SearchHelper.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/EverythingOperationTenant1Test.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/EverythingOperationTest.java
This works for Patient, Encounter, Practitioner, and RelatedPerson compartments.
For Device, we still extract the membership parameter, but `GET
Device/{id}/Device` is considered an invalid search.
This addresses the issue outlined in #3091 because the `fhir-smart`
module is turning our searches into Patient compartment searches under the
covers. Now the Patient resource that corresponds to the in-context
patient will be returned from that.
> issue #3091 - Add resources to their own compartment

- demo/fhir/config/default/fhir-server-config.json
- demo/postgres/Dockerfile
1. updates to fhir-server-config to stay in line with our default config
2. updates to openapi.json to reflect the latest updates in main
3. update to postgresql 14.2
> update demo env

- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Issue #2300 - Fix buildPersistenceEventProperties
> Issue #2300 - Fix buildPersistenceEventProperties

- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfigHelper.java
- fhir-config/src/test/java/com/ibm/fhir/config/test/FHIRConfigHelperTest.java
- fhir-config/src/test/resources/config/default/fhir-server-config.json
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/ParameterHashVisitor.java
- fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/ParameterHashTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/EraseOperationTest.java
Includes fixes for the following issues:
* #3446 fixes computation of parameter hash for fields using ByteBuffer
* #3416 prevent payload configuration falling back to default tenant
* #3439 handle null data after version-specific erase
> Issue #3446 reference version missing from parameter hash

- docs/src/pages/Conformance.md
- fhir-install/Dockerfile
- fhir-install/src/main/resources/scripts/install.bat
- fhir-install/src/main/resources/scripts/install.sh
- fhir-parent/pom.xml
- fhir-server-spi/pom.xml
- fhir-server-spi/src/main/java/com/ibm/fhir/server/spi/operation/FHIROperationUtil.java
- fhir-server-spi/src/test/java/com/ibm/fhir/server/spi/operation/test/FHIROperationUtilTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ExportOperationTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ExportOperation.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/url/DownloadUrl.java
- operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java
- operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtilTest.java
- operation/fhir-operation-everything/src/main/java/com/ibm/fhir/operation/everything/EverythingOperation.java
Previously, I updated whole-system search to support combining multiple
instances of the `_type` parameter.  Now we will handle multiple '_type'
parameters in the extended operations $everything and $export as well.
I updated the search section in Conformance.md to indicate this change
and added a note in the extended operations section to indicate that
query parameters will be ignored for operations invoked via POST.
> issue #3319 - normalize handling of _type parameters

- fhir-client/src/main/java/com/ibm/fhir/client/FHIRClient.java
- fhir-client/src/main/java/com/ibm/fhir/client/impl/FHIRClientImpl.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/DerbyResourceDAO.java
- fhir-search/src/test/java/com/ibm/fhir/search/test/TypeParameterParseTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BasicServerTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BundleTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SystemHistoryTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Create.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Operation.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Patch.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Update.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
We had duplicate logic in two classes:
* FHIRResource.getRequestBaseUri
* FHIRRestHelper.getRequestBaseUri
For #2965, we fixed the version in FHIRResource but missed the one in
FHIRRestHelper.
Now I combined the two implementations into FHIRRestHelper, made it
static, and removed the version from FHIRResource.
I also added commits for the discrepencies between system-level and
instance-level history identified in #3501
> issue #3501 - apply fix for #2965 more universally

- cql/operation/fhir-operation-cqf/pom.xml
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/cqf/ServerMeasureSubmitDataOperationTest.java
- fhir-server-test/src/test/resources/testdata/MeasureReport-EXM104.json
the test data had a contained Patient resource that was not valid per US
Core 4.0.0 because its race and ethnicity extensions were missing a
required "text" value
> issue #3469 - add missing jar to shaded jar and fixup test data for conformance to us core 4.0

- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/DerbyResourceDAO.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgres/PostgresResourceNoProcDAO.java
- fhir-persistence-schema/src/main/resources/db2/add_any_resource.sql
- fhir-persistence-schema/src/main/resources/postgres/add_any_resource.sql
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/BundleTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SystemHistoryTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/EraseOperationTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Update db2 and postgresql add_any_resource.sql stored procs (and
DerbyResourceDAO.storeResource) to write a 'C' instead of a 'U' for this
case. This way, system and type-level history interactions can properly
report the response status as a 201 instead of a 200.
Update FHIRRestHelper.createHistoryBundle to handle this same case for
the instance-level history. Note, however, that there are ongoing
limitations for the accuracy of the instance-level history entries as
outlined at https://github.com/IBM/FHIR/issues/3507#issuecomment-1081157116
> issue #3507 - treat "undelete" updates like create-on-update in changes

- fhir-server/src/main/java/com/ibm/fhir/server/interceptor/FHIRPersistenceInterceptorMgr.java
- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- fhir-smart/src/main/java/com/ibm/fhir/smart/Scope.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/JWTTest.java
Specifically, avoid adding the implicit compartment parameter(s) when
the interaction is allowed by one or more scopes with the 'user/' or
'system/' prefix ("context type")
> issue #3495 - more selectively scope searches to patient compartment

- fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/CapabilitiesTest.java
- fhir-server/src/test/resources/config/empty/fhir-server-config.json
1. Advertise support for the system and type-level history interactions
2. Update Capabilities.getSupportedResourceTypes to use the new
ResourcesConfigAdapter
Backported from https://github.com/IBM/FHIR/commit/c9cadcb75bc6b5d1ba44004190c51fd5e2867f38
> issues #3184 and #3186 - update Capabilities

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
- fhir-config/src/main/java/com/ibm/fhir/config/PropertyGroup.java
- fhir-config/src/main/java/com/ibm/fhir/config/ResourcesConfigAdapter.java
- fhir-core/src/main/java/com/ibm/fhir/core/FHIRUtilities.java
- fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/FHIRPersistenceUtil.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/util/FHIRPersistenceUtilTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/test/InteractionValidationConfigTest.java
Previously, validateInteraction was using FHIRConfigHelper to look up
sub-properties of fhirServer/resources which, due to fallback behavior,
may conflict with the configured interactions for the tenant.
Because validateInteraction is invoked by most interactions, I moved
ResourcesConfigAdapter initialization to the FHIRRestHelper constructor.
This should help a tad in bundle processing (no need to process this same
config over and over within the scope of a single request).
To avoid a potentially null ResourcesConfigAdapter, I updated
fhir-config to remove some unneccessary "throws Exception" cases...all
stemming from a possible UnsupportedEncodingException for UTF-8 from
FHIRUtilities.decode (a case we should never hit).
> issue #3536 - use ResourcesConfigAdapter from validateInteraction

- fhir-config/src/test/java/com/ibm/fhir/config/test/ResourcesConfigAdapterTest.java
- fhir-core/src/main/java/com/ibm/fhir/core/ResourceTypeName.java
- fhir-model/src/test/java/com/ibm/fhir/model/test/ResourceTypeNameTest.java
- fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
I could have sworn I did this before, but its definitely out-of-sync in
main. This changeset re-aligns the two so that:
1. we don't end up trying to use a resource type that doesn't exit in R4
2. we don't miss any resource types that existed in R4 but are being
removed for R4B
> issue #3390 - align ResourceTypeName with the R4 ResourceType enum

- .github/workflows/rebuild.yml
The rebuild process has been failing for the prior releases, but I think it might work starting with 4.11.0
> issue #1412 - only rebuild the last release

- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
Now that our persistence layer requires resources to have proper
metadata (id, versionId, and lastUpdated) prior to calling create/update/delete, I thought that resources
will always have an id before we call the persistence interceptors.
However, it turns out that we call the beforeCreate from the REST layer
BEFORE setting this metadata on the resource.
After a brief discussion, we decided to leave that as-is and update the
interceptor to allow a null resourceId.
> issue #3576 - remove unnecessary guard against null resourceId

- fhir-model/src/main/java/com/ibm/fhir/model/visitor/PathAwareVisitor.java
- fhir-model/src/main/java/com/ibm/fhir/model/visitor/ResourceFingerprintVisitor.java
- fhir-model/src/test/java/com/ibm/fhir/model/util/test/ResourceComparatorVisitor.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathAbstractSystemValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathBooleanValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathDateTimeValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathDateValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathDecimalValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathIntegerValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathStringValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathSystemValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathTimeValue.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathTree.java
- fhir-path/src/main/java/com/ibm/fhir/path/FHIRPathTypeInfoNode.java
- fhir-path/src/main/java/com/ibm/fhir/path/util/DeletingVisitor.java
- fhir-path/src/test/java/com/ibm/fhir/path/patch/test/FHIRPathUtilPatchTest.java
Previously we had "interesting" behavior for fields like Element.id that
are of type System.String (rather than FHIR.String).  Now these nodes
will become children in the EvaluationContext tree.
This allows users to remove fields like Resource.id and Element.id via
FHIRPath and it even allows you to remove the value of primitive FHIR
elements (e.g. Patient.active.value) in cases where those primitives
already have an extension (otherwise they need to have a value).
I also updated the javadoc (relates to #2153) because the user was
confused about the FHIRPathNode API and I thought it could use further
clarification.
> issue #3619 - populate 'path' field for SystemValueNodes in context tree

- build/docker/copy-server-config.sh
- build/docker/docker-compose.yml
- build/docker/minio/Dockerfile
- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-client/src/main/java/com/ibm/fhir/client/FHIRClient.java
- fhir-client/src/main/java/com/ibm/fhir/client/impl/FHIRClientImpl.java
- fhir-client/src/test/java/com/ibm/fhir/client/sample/FHIRClientSample.java
- fhir-client/src/test/resources/test.basic.properties
- fhir-client/src/test/resources/test.properties
- fhir-install/Dockerfile
- fhir-install/src/main/docker/ibm-fhir-server/bootstrap.properties
- fhir-server-test/src/test/java/com/ibm/fhir/client/test/FHIRClientTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchAllTest.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ImportOperationTest.java
- fhir-server-test/src/test/resources/test.properties
- fhir-server-webapp/src/main/liberty/config/bootstrap.properties
- fhir-server-webapp/src/main/webapp/WEB-INF/web.xml
- fhir-server/src/main/java/com/ibm/fhir/server/resources/filters/FHIRVersionRequestFilter.java
and document how to set it via the `fhirclient.default.mimetype`
configuration property (PROPNAME_DEFAULT_MIMETYPE)
The change highlighted an underlying issue with our FHIRVersionRequestFilter and also with how we're processing `_type` query parameters, and so I've addressed those issues in this PR as well.
> issue #3256 - change the default fhirclient MIME type to specify fhirVersion 4.3

- conformance/fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/v311/ConformanceTest.java
- conformance/fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/v400/ConformanceTest.java
- conformance/fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/v500/ConformanceTest.java
- fhir-profile/src/main/java/com/ibm/fhir/profile/ConstraintGenerator.java
- fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
1. ConstraintGenerator.generateExtensionConstraint will now include a
`conformsTo` clause on all extension constraints
2. ConstraintGenerator.generate will assign such extension constraints a
special constraint id that uses the form:  `prefix~path<url>`
3. FHIRValidator will look for these special constraints and avoid
generating instance-specific extension constraints if they overlap with
an existing profile constraint
> issue #3661 - Only generate instance-specific constraints when needed

- fhir-path/src/test/java/com/ibm/fhir/path/test/ResolveFunctionTest.java
technically we were already testing this under
testResolveBundleReference_HttpFullUrl, but having a dedicated test for
this case makes sense
> issue #3475 - add test for multiple context nodes

- fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/AppointmentTest.java
- fhir-validation/src/test/java/com/ibm/fhir/validation/test/BloodPressureObservationTest.java
- term/fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
Previously, FHIRTermServer.validateCode(ValueSet, CodeableConcept)
returned a false ValidationOutcome in cases where the code was a valid
member of the ValueSet but includes a display value that we couldn't
validate (e.g. due to missing the corresponding CodeSystem).
Now, we will return true in the ValidationOutcome for this case, but we
include a message alongside it to indicate that we didn't actually
validate the display value. From the FHIRPath MemberOfFunction, we
translate that into an informational OperationOutcomeIssue and add it to
the EvaluationContext.
For example:
> Unable to validate display value 'Diastolic Blood Pressure' for code
'8462-4' in system 'http://loinc.org'
> issue #3665 - handle coding in valueset when we can't validate display

- README.md
- docs/_config.yml
- docs/src/pages/Conformance.md
- docs/src/pages/guides/BringYourOwnPersistence.md
- docs/src/pages/guides/FHIRClinicalReasoningGuide.md
- docs/src/pages/guides/FHIROperationFramework.md
- docs/src/pages/guides/FHIRPerformanceGuide.md
- docs/src/pages/guides/FHIRSearchConfiguration.md
- docs/src/pages/guides/FHIRServerUsersGuide.md
Added new conformance modules (fhir-core-r4, fhir-core-r4b, and fhir-hl7-terminology) to the README.
For Conformance.md, I added a section titled "FHIR Versions" near the top and detailed the
behavior with respect to supporting both versions 4.0.1 and 4.3.0 and
the use of the fhirVersion MIME-type parameter.
I also normalized all the links to https://hl7.org/fhir/R4B
...previously there was a lot of www.hl7.org links and a mix of
versioned (`fhir/R4/`) and non-versioned (`fhir/`) URLs.
> issue #3331 - update README.md and Conformance.md for FHIR R4B

- docs/src/pages/guides/FHIRServerUsersGuide.md
- fhir-search/src/main/java/com/ibm/fhir/search/parameters/IncludesUtil.java
- fhir-search/src/test/java/com/ibm/fhir/search/parameters/IncludesUtilTest.java
- operation/fhir-operation-everything/src/main/java/com/ibm/fhir/operation/everything/EverythingOperation.java
- operation/fhir-operation-everything/src/test/java/com/ibm/fhir/operation/everything/EverythingOperationTest.java
Instead of a big if/else with all the manually preconfigured search parameters, we now look up the applicable search parameters for the given resource type for this tenant and then process those into the set of includes.
It should work mostly the same, except that:
1. we now support "includeTypes" for all resource types; previously it only supported "Medication", "Location", "Practitioner", and "Organization
2. for the 4 types that were previously supported, we include a few additional includes that were missed in the manually computed list
3. we fix a single issue with an include value from ExplanationOfBenefit (it used to add "insurer" but this is not a valid search parameter in the core specification)
> Support additional extraResources types from Patient/$everything

- fhir-server/pom.xml
- fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
- fhir-server/src/main/java/com/ibm/fhir/server/resources/Operation.java
For some reason, our exception handling for
`invoke(String,String,Resource)` differs from the exception handling in
all the other invoke methods.
I assume that was done so that the $invoke operation properly returns a
200 OK in cases where the data is invalid.
But this is not the right level for that logic and it can prevent us
from seeing important server issues in the logs.
I double-checked and the ValidateOperation is
already returning a valid OperationOutcome response for successful
validation of invalid resources, so I think we just need to remove the
special handling at the Operation JAX-RS resource.
Additionally, we found "interesting" liberty behavior that was
preventing us from seeing the exception stack trace even when FINE
logging is enabled; that log message is now level INFO …
> issue #3735 - remove invoke(String,String,Resource) special processing

- fhir-audit/src/main/java/com/ibm/fhir/audit/configuration/type/KafkaType.java
I was poking around these classes and noticed we define these constants
but then we didn't actual use them. Very minor.
> Use string constants

- conformance/fhir-core-r4b/pom.xml
- fhir-server-test/pom.xml
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/smart/SMARTTest.java
- fhir-server-test/src/test/java/testng.xml
- fhir-smart/src/main/java/com/ibm/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- fhir-smart/src/test/java/com/ibm/fhir/smart/test/AuthzPolicyEnforcementTest.java
- operation/fhir-operation-everything/src/main/java/com/ibm/fhir/operation/everything/EverythingOperation.java
In addition to the change, I added a new e2e test package under
fhir-server-test to confirm the fix. The test will conditionally execute
based on whether the server advertises its
.well-known/smart-configuration (which we only serve when its
configured). There's a ton of cases we could add, but for now I just
wanted to cover the specific case in #3503. Previously, we had only unit
tests for the fhir-smart interceptor.
I also removed an unused private method from the fhir-smart interceptor.
Finally, I snuck in a couple very minor updates:
* removed an unused test-jar dependency from fhir-core-r4b
* a single word change to a specific AuthzPolicyEnforcement message to
hint that only "SMART" scopes are echoed back to the client (and not
other scopes that may have been passed)
Signed-off-by: …
> issue #3503 - special case underlying $everything "Forbidden" exceptions

- cql/fhir-cql-server/src/main/java/com/ibm/fhir/cql/engine/server/retrieve/ServerFHIRRetrieveProvider.java
In my opinion, neither the old behavior (500 server error) nor the new
behavior (200 OK with a null expression result) are ideal.
However, since we didn't intend to change it, I've restored the previous
behavior for now.
The most relevant advantage is we'll now get a reasonable error message
when the user tries to evaluate expressions on resources that don't
exist.
> issue #3655 - throw from ServerFHIRRetrieveProvider for failed reads

- build/docker/docker-compose.yml
Our other postgres compose environments use an init script that modifies a lot of postgres settings as follows:
```
sed -i -e"s/^max_connections = 100.*$/max_connections = 100/" /db/data/postgresql.conf
sed -i -e"s/^max_prepared_transactions = 100.*$/max_prepared_transactions = 100/" /db/data/postgresql.conf
sed -i -e"s/^max_locks_per_transaction = .*$/max_locks_per_transaction = 128/" /db/data/postgresql.conf
sed -i -e"s/^shared_buffers =.*$/shared_buffers = 4GB/" /db/data/postgresql.conf
sed -i -e"s/^#effective_cache_size = 128MB.*$/effective_cache_size = 2GB/" /db/data/postgresql.conf
sed -i -e"s/^#work_mem = 1MB.*$/work_mem = 1MB/" /db/data/postgresql.conf
sed -i -e"s/^#maintenance_work_mem = 16MB.*$/maintenance_work_mem = 512MB/" /db/data/postgresql.conf
sed -i …
```
> tweak postgres settings

- fhir-persistence/src/main/java/com/ibm/fhir/persistence/SingleResourceResult.java
- fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/SingleResourceResultTest.java
- fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
- fhir-server/src/test/java/com/ibm/fhir/server/util/FHIRRestHelperTest.java
Allows persistence interceptors to modify the resource when processing the following events:
- afterRead
- afterVread
- afterSearch
- afterHistory
Currently the interceptor is trusted to not do anything which would invalidate the resource for the given interaction.
> issue #3787 allow afterSearch interceptor to modify resource

- fhir-model/src/test/java/com/ibm/fhir/model/spec/test/DriverMetrics.java
- fhir-model/src/test/java/com/ibm/fhir/model/spec/test/R4ExamplesDriver.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/examples/ExampleRequestProcessor.java
- fhir-server-test/src/test/java/com/ibm/fhir/server/test/examples/R4ExampleServerTest.java
The method signature indicates that Exception is thrown, but the
implementation was throwing AssertionErrors instead.
This lead us to miss these in our exception handling and, since they
were within an ExecutorPool, it never got bubbled up to the test thread.
After this change, 3 examples from our MINIMAL set were failing due to 
the server defaulting to fhirVersion 4.0 and so we now explicitly set the 
fhirVersion to 4.3 in ExampleRequestProcessor.
I made some other minor changes (mostly style preference stuff) along
the way and included those in the commit.
> issue #3304 - favor Exceptions over Errors in ExampleRequestProcessor

- fhir-bulkdata-webapp/pom.xml
- fhir-config/src/main/java/org/linuxforhealth/fhir/config/FHIRConfigHelper.java
- operation/fhir-operation-bulkdata/src/main/java/org/linuxforhealth/fhir/operation/bulkdata/config/impl/V2ConfigurationImpl.java
A cleaner approach would be to add a method to FHIRPersistence so that
implementations can indicate whether they support fetchResourcePayloads
which is what we use for the fast export. Then we could pass that into
BulkDataClient.submitExport where we decide which export implementation
to use.
However, ideally we'd just add this support...then we probably wouldn't
need those changes.
Therefor, for now, I opted for the quick and dirty fix.
> issue #3874 - use legacy export when payload offloading is configured

- .github/workflows/audit.yml
- .github/workflows/build.yml
- .github/workflows/integration.yml
- .github/workflows/javadocs.yml
- .github/workflows/migration.yml
- .github/workflows/notification.yml
- .github/workflows/persistence.yml
- .github/workflows/rebuild.yml
- .github/workflows/reindex.yml
- .github/workflows/release.yml
- .github/workflows/security.yml
- .github/workflows/windows.yml
- fhir-persistence-jdbc/src/test/java/org/linuxforhealth/fhir/persistence/jdbc/test/JDBCSortTest.java
- fhir-persistence/src/test/java/org/linuxforhealth/fhir/persistence/search/test/AbstractWholeSystemSearchTest.java
- fhir-persistence/src/test/java/org/linuxforhealth/fhir/persistence/test/common/AbstractSortTest.java
- term/fhir-term-graph-loader/src/test/java/org/linuxforhealth/fhir/term/graph/test/GraphTermServiceProviderTimeLimitTest.java
- term/fhir-term-graph/src/main/java/org/linuxforhealth/fhir/term/graph/provider/GraphTermServiceProvider.java
There must have been some environmental change to the github actions windows-2019 environment because today a couple tests started failing due to multiple resources being assigned the same timestamp (`Instant.now()` truncated to nearest microsecond).
JDBCSortTest creates 6 resources in a row and in this environment (and only this environment) a number of them were assigned the same lastUpdated time.  To address the issue, I added a 10ms pause between the creates.  I also kept some of the logging statements that I added to AbstractSortTest in case we need to further debug.
JDBCWholeSystemSearchTest was failing for a similar reason...one of the test cases searched by lastUpdated time and was expecting a single match (but was getting 2). I fixed it by checking the lastUpdated time in each …
> issue #3888 - work around timestamp-related issues in test environment

- .github/workflows/javadocs.yml
- .github/workflows/rebuild.yml
- .github/workflows/release.yml
- .github/workflows/site.yml
- build/release/bin/10_build/3_build.sh
I also added `-Dsurefire.failIfNoSpecifiedTests=false` to the release script to avoid an issue I saw where the lack of tests in one module caused the entire release process to fail.
> use GITHUB_TOKEN and set permissions

- .github/workflows/javadocs.yml
- fhir-examples/pom.xml
- fhir-tools/pom.xml
It looks like we no longer need to trigger a build after pushing the change to gh-pages
> Remove redundant step from javadocs workflow

- .github/workflows/rebuild.yml
GitHub executes the "current" rebuild.yml workflow, but I forgot that this workflow
checks out an older version of the repo and thus the release scripts that are used
are actually from that older version and the dockerhub one was named `1_dockerhub.sh`
and required the DOCKERHUB_USERNAME and DOCKERHUB_TOKEN env vars to be populated.
> make dockerhub rebuild workflow compatible with previously tagged scripts

- fhir-install/src/main/docker/fhir-bucket-tool/build.sh
- fhir-install/src/main/docker/fhir-schematool/build.sh
- fhir-install/src/main/docker/fhir-term-graph-loader/build.sh
In 5.0.0-RC1, only the linuxforhealth/fhir-server image was successfully pushed to
the GitHub container registry. I'm hoping that, with these changes, when we tag
RC2 it will push all of the desired images to the registry.
> add ghcr.io prefix to build scripts for the other container images

- fhir-examples/pom.xml
- fhir-parent/pom.xml
1. lock in to specific versions for a few transitive dependencies that were flagged by sonatype
* manage commons-configuration2 to 2.8.0
* manage netty-handler to 4.1.79.Final (we already managed other netty modules but com.datastax.oss:java-driver-core specifically depends on the handler)
* manage icu4j to 71.1
2. group the apache commons dependencies together in fhir-parent
3. add a version for the nexus-staging-maven-plugin plugin
4. update the fhir-examples plugin versions to match the plugin versions from fhir-parent
> dependency version bumps

- conformance/fhir-core-r4b/src/main/resources/hl7/fhir/core/430/package/SearchParameter-ClinicalUseDefinition-contraindication-reference.json
- conformance/fhir-core-r4b/src/main/resources/hl7/fhir/core/430/package/SearchParameter-ClinicalUseDefinition-contraindication.json
- conformance/fhir-core-r4b/src/main/resources/hl7/fhir/core/430/package/SearchParameter-ClinicalUseDefinition-effect-reference.json
- conformance/fhir-core-r4b/src/main/resources/hl7/fhir/core/430/package/SearchParameter-ClinicalUseDefinition-effect.json
- conformance/fhir-core-r4b/src/main/resources/hl7/fhir/core/430/package/SearchParameter-ClinicalUseDefinition-indication-reference.json
- conformance/fhir-core-r4b/src/main/resources/hl7/fhir/core/430/package/SearchParameter-ClinicalUseDefinition-indication.json
- fhir-search/src/test/java/org/linuxforhealth/fhir/search/tool/SearchParameterAugmenter.java
Initially I had planned to add support in JDBCParameterBuildingVisitor
for visiting CodeableReference elements. However, because the FHIR
community decided that expressions should *not* target CodeableReference
elements, I decided to patch the offending R4B SearchParameter
definitions instead.
> issue #3854 - patch ClinicalUseDefinition search params

- build/migration/postgres/8_teardown.sh
- build/post-integration-test-docker.sh
- fhir-database-utils/src/main/java/org/linuxforhealth/fhir/database/utils/model/Table.java
- fhir-database-utils/src/main/java/org/linuxforhealth/fhir/database/utils/model/View.java
- fhir-persistence-schema/src/main/java/org/linuxforhealth/fhir/schema/app/Main.java
- fhir-persistence-schema/src/main/java/org/linuxforhealth/fhir/schema/control/FhirResourceTableGroup.java
- fhir-persistence-schema/src/main/java/org/linuxforhealth/fhir/schema/control/FhirSchemaGenerator.java
After the previous changes, dropping a schema that was created with a
4.x version of fhir-persistence-schema was failing because we never
dropped the tables that have been removed from the model.
With these changes, we flag the removed resource types as "retired" and
avoid their creation in new schemas that way (vs. leaving them out of
the model entirely).
We could potentially remove this logic if we ever get to
https://github.com/LinuxForHealth/FHIR/issues/3263
I also added `@Deprecated` annotations for old migration steps in our fhir-persistence-schema
Main which I'm thinking we can remove whenever we bump to 6.0 (so we'll continue to support 
any 4.x to 5.x migration, but not 4.x to 6.x).
> issue #3859 - track retired tables (and views) in the model so we can drop them

- operation/fhir-operation-validate/src/main/java/org/linuxforhealth/fhir/operation/validate/ValidateOperation.java
- operation/fhir-operation-validate/src/test/java/org/linuxforhealth/fhir/operation/validate/ValidateOperationTest.java
I also did some major refactoring so that we can return 200 OK for more cases.
Specifically, I tried to split the types of validation into two:
* If preconditions of the $validate operation are not met, we continue
to throw and thus return HTTP 400 Bad Request responses.
* If preconditions pass, but the interaction being validated (via
'mode') is not supported for the passed input, we now return HTTP 200 OK
with an OperationOutcome that contains one or more issues with severity
ERROR.
Example of the first type:
* mode 'update' is not allowed when invoking $validate at the resource type level
* 'resource' parameter is required when invoking $validate with mode=create
Example of the second type:
* the 'update' would not be valid at the passed URL because the passed resource does not have an …
> issue #3919 - validate Resource.id when invoked at instance level

- .github/workflows/rebuild.yml
1. No need to rebuild 5.0.0-RC1 any more now that 5.0.0-RC2 is out
2. No need to rebuild ibmcom/ibm-fhir-server 4.11.0 ... just do the latest (4.11.1).
> update the rebuild workflow

- .github/workflows/audit.yml
- .github/workflows/build.yml
- .github/workflows/integration.yml
- .github/workflows/migration.yml
- .github/workflows/notification.yml
- .github/workflows/persistence.yml
- .github/workflows/reindex.yml
- .github/workflows/windows.yml
- fhir-path/src/main/java/org/linuxforhealth/fhir/path/FHIRPathType.java
- fhir-persistence-jdbc/src/main/java/org/linuxforhealth/fhir/persistence/jdbc/connection/FHIRTestTransactionAdapter.java
- fhir-persistence-jdbc/src/test/java/org/linuxforhealth/fhir/persistence/jdbc/test/spec/R4JDBCExamplesProcessor.java
- fhir-persistence-params/src/main/java/org/linuxforhealth/fhir/persistence/params/database/PlainBatchParameterProcessor.java
- fhir-validation/src/main/java/org/linuxforhealth/fhir/validation/FHIRValidator.java
So that the callback for inserting search parameter values is invoked.
I'm expecting this to fail until #4021 is addressed... which actually means its working.
> issue #4023 - use FHIRPersistenceTransaction instead of ITransactionProvider

- fhir-server-test/src/test/java/org/linuxforhealth/fhir/client/test/FHIRClientTest.java
- fhir-server-test/src/test/java/org/linuxforhealth/fhir/server/test/BasicServerTest.java
- fhir-server/src/main/java/org/linuxforhealth/fhir/server/resources/Capabilities.java
The HL7 validator issues a warning on our current CapabilityStatement because `name` is intended for computer processing (so they recommend against whitespace but still allow it).
`CapabilityStatement.title` is the field intended for human consumption and so I think its cleaner to use that instead.
I also removed the no-longer-needed calls to the static `string()` factory...because thats what I do.
> Another `capabilities` change

- conformance/fhir-ig-davinci-pdex-formulary/CHANGELOG.md
- conformance/fhir-ig-davinci-pdex-formulary/src/main/resources/hl7/fhir/us/davinci-pdex-formulary/200/package/SearchParameter-Basic-subject.json
- conformance/fhir-ig-davinci-pdex-formulary/src/main/resources/hl7/fhir/us/davinci-pdex-formulary/200/package/StructureDefinition-usdf-PayerInsurancePlan.json
1. fixed the version suffix on the reference to http://hl7.org/fhir/us/davinci-pdex-plan-net/ValueSet/InsuranceProductTypeVS
2. fixed the "code" in SearchParameter-Basic-subject.json (and opened a corresponding spec bug, https://jira.hl7.org/browse/FHIR-39401 )
> Formulary fixes

- fhir-smart/src/main/java/org/linuxforhealth/fhir/smart/AuthzPolicyEnforcementPersistenceInterceptor.java
- fhir-smart/src/test/java/org/linuxforhealth/fhir/smart/test/AuthzPolicyEnforcementTest.java
and add corresponding tests to AuthzPolicyEnforcementTest.java
> issue #4101 - handle patch in fhir-smart interceptor

- fhir-server/src/main/java/org/linuxforhealth/fhir/server/util/FHIRRestHelper.java
Previously, a skippable update (one that would not affect the contents of the resource being updated) would result in a success without invoking beforeUpdate or beforePatch interceptor methods.
For users of fhir-smart, this behavior is confusing because the user may not have write access to this resource type, but the server is "allowing" the write anyway (even though its really being optimized away).
> issue #4101 - call beforeX interceptor methods prior to checking if update is skippable

- fhir-database-utils/src/main/java/org/linuxforhealth/fhir/database/utils/common/DataDefinitionUtil.java
Solves #4193 
When there are dashes (-) in the Postgres username, the schematool fails with an exception. In Postgres, dashes are legal in usernames, so the verifying pattern is adapted accordingly.
> Schematool: allow `-` in database usernames
